//go:build integration

package app_test

import (
	"bytes"
	"context"
	"crypto/rand"
	"fmt"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"
	"time"

	lkauth "github.com/livekit/protocol/auth"
	"github.com/livekit/protocol/livekit"
	"github.com/twitchtv/twirp"

	v1 "github.com/calaba/calaba/server/gen/calaba/v1"
	"github.com/calaba/calaba/server/internal/gptunnel/gptunneltest"
)

// Meeting recording (ADR-0025) against fakes: the Egress service is the twirp server
// generated by livekit/protocol (so our minimal client is checked against the real wire
// format) with an in-memory implementation; GPTunneL is gptunneltest. The egress file is
// written by the test into RECORDINGS_PATH, as the egress container would.

var (
	gptFake   *gptunneltest.Server
	egFake    *fakeEgress
	recordDir string
)

// fakeEgress implements the Egress RPCs the server uses; the others are not expected.
type fakeEgress struct {
	livekit.Egress
	mu     sync.Mutex
	seq    int
	items  map[string]*livekit.EgressInfo
	starts []*livekit.RoomCompositeEgressRequest
	stops  []string
	fail   bool // StartRoomCompositeEgress answers unavailable
}

func (f *fakeEgress) StartRoomCompositeEgress(_ context.Context, req *livekit.RoomCompositeEgressRequest) (*livekit.EgressInfo, error) {
	f.mu.Lock()
	defer f.mu.Unlock()
	if f.fail {
		return nil, twirp.NewError(twirp.Unavailable, "no egress available")
	}
	if !req.GetAudioOnly() || len(req.GetFileOutputs()) != 1 || req.GetFileOutputs()[0].GetFileType() != livekit.EncodedFileType_MP4 ||
		!strings.HasPrefix(req.GetFileOutputs()[0].GetFilepath(), "/out/") || req.GetLayout() != "" {
		return nil, twirp.InvalidArgumentError("request", fmt.Sprintf("unexpected request %v", req))
	}
	f.seq++
	info := &livekit.EgressInfo{EgressId: fmt.Sprintf("EG_%d_%d", time.Now().UnixNano(), f.seq), RoomName: req.GetRoomName(),
		Status: livekit.EgressStatus_EGRESS_STARTING, StartedAt: time.Now().UnixNano()}
	f.items[info.EgressId] = info
	f.starts = append(f.starts, req)
	return info, nil
}

func (f *fakeEgress) StopEgress(_ context.Context, req *livekit.StopEgressRequest) (*livekit.EgressInfo, error) {
	f.mu.Lock()
	defer f.mu.Unlock()
	info := f.items[req.GetEgressId()]
	if info == nil {
		return nil, twirp.NotFoundError("egress not found")
	}
	f.stops = append(f.stops, req.GetEgressId())
	if info.Status > livekit.EgressStatus_EGRESS_ENDING {
		return nil, twirp.NewError(twirp.FailedPrecondition, "egress with status "+info.Status.String()+" cannot be stopped")
	}
	info.Status = livekit.EgressStatus_EGRESS_ENDING
	return info, nil
}

func (f *fakeEgress) ListEgress(_ context.Context, req *livekit.ListEgressRequest) (*livekit.ListEgressResponse, error) {
	f.mu.Lock()
	defer f.mu.Unlock()
	out := &livekit.ListEgressResponse{}
	for _, info := range f.items {
		if (req.GetRoomName() != "" && info.RoomName != req.GetRoomName()) || (req.GetEgressId() != "" && info.EgressId != req.GetEgressId()) ||
			(req.GetActive() && info.Status > livekit.EgressStatus_EGRESS_ENDING) {
			continue
		}
		out.Items = append(out.Items, info)
	}
	return out, nil
}

// end marks an egress complete with its file and returns the info LiveKit would send.
func (f *fakeEgress) end(id string, size int64) *livekit.EgressInfo {
	f.mu.Lock()
	defer f.mu.Unlock()
	info := f.items[id]
	info.Status = livekit.EgressStatus_EGRESS_COMPLETE
	info.EndedAt = time.Now().UnixNano()
	info.FileResults = []*livekit.FileInfo{{Filename: "x.mp4", Size: size, Duration: int64(90 * time.Second)}}
	return info
}

func (f *fakeEgress) stopped(id string) bool {
	f.mu.Lock()
	defer f.mu.Unlock()
	for _, s := range f.stops {
		if s == id {
			return true
		}
	}
	return false
}

// startRecordingFakes starts the fakes; the egress server checks our token carries the
// roomRecord grant like LiveKit does.
func startRecordingFakes() (egressURL string, stop func(), err error) {
	gptFake = gptunneltest.New()
	egFake = &fakeEgress{items: map[string]*livekit.EgressInfo{}}
	twirpSrv := livekit.NewEgressServer(egFake)
	egSrv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		v, err := lkauth.ParseAPIToken(strings.TrimPrefix(r.Header.Get("Authorization"), "Bearer "))
		if err != nil {
			http.Error(w, "no token", http.StatusUnauthorized)
			return
		}
		if _, grants, err := v.Verify("secret"); err != nil || grants.Video == nil || !grants.Video.RoomRecord {
			http.Error(w, "missing roomRecord", http.StatusUnauthorized)
			return
		}
		twirpSrv.ServeHTTP(w, r)
	}))
	recordDir, err = os.MkdirTemp("", "calaba-it-recordings-")
	if err != nil {
		return "", nil, err
	}
	return egSrv.URL, func() { egSrv.Close(); gptFake.Close(); _ = os.RemoveAll(recordDir) }, nil
}

// inCall puts u into the voice room (join + participant_joined), so a call is running.
func inCall(t *testing.T, u *user, ws *v1.Workspace, rid string) string {
	t.Helper()
	var j v1.JoinVoiceResponse
	u.must(200, "POST", "/api/rooms/"+rid+"/join", nil, &j)
	if st := webhook(t, whEvent("participant_joined", "ws_"+ws.GetId()+"_room_"+rid, j.GetIdentity(), nil), "secret"); st != 200 {
		t.Fatalf("participant_joined: %d", st)
	}
	return j.GetIdentity()
}

func pairWorkspace(t *testing.T, o *user, wsID string) {
	t.Helper()
	const alphabet = "ABCDEFGHJKMNPQRSTUVWXYZ23456789"
	b := make([]byte, 8)
	_, _ = rand.Read(b)
	for i := range b {
		b[i] = alphabet[int(b[i])%len(alphabet)]
	}
	code := string(b)
	gptFake.AddCode(code)
	var resp v1.PairGptunnelResponse
	o.must(200, "POST", "/api/workspaces/"+wsID+"/integrations/gptunnel", &v1.PairGptunnelRequest{Code: code[:4] + "-" + code[4:]}, &resp)
	if !resp.GetIntegration().GetPaired() || resp.GetIntegration().GetAccount() != "Test Account" || resp.GetIntegration().GetPairedBy() != o.id {
		t.Fatalf("pair: %v", resp.GetIntegration())
	}
}

func recState(t *testing.T, id string) (status, errCode, webURL string, fileDeleted bool) {
	t.Helper()
	var deleted *time.Time
	if err := testDB.Pool.QueryRow(context.Background(), `SELECT status, error, web_url, file_deleted_at FROM room_recordings WHERE id = $1`, id).
		Scan(&status, &errCode, &webURL, &deleted); err != nil {
		t.Fatal(err)
	}
	return status, errCode, webURL, deleted != nil
}

func card(e *v1.DispatchEvent) *v1.RecordingCard {
	m := e.GetMessageCreate().GetMessage()
	if m == nil {
		m = e.GetMessageUpdate().GetMessage()
	}
	if m.GetKind() != v1.MessageKind_MESSAGE_KIND_SYSTEM {
		return nil
	}
	return m.GetSystem().GetRecording()
}

func TestRecordingFlow(t *testing.T) {
	liveKitUp(t)
	o, bob, ws, room := setupTeam(t)
	rid := room.GetId()
	if !room.GetAllowRecording() {
		t.Fatal("new rooms allow recording")
	}

	// Not paired: 409 NOT_PAIRED (even before anybody is in the call).
	if e := bob.rawErr("POST", "/api/rooms/"+rid+"/recording/start"); e.GetCode() != v1.ErrorCode_ERROR_CODE_NOT_PAIRED {
		t.Fatalf("not paired: %v", e)
	}
	// Integration: members see the status, only MANAGE_WORKSPACE pairs.
	var gi v1.GetGptunnelIntegrationResponse
	bob.must(200, "GET", "/api/workspaces/"+ws.GetId()+"/integrations/gptunnel", nil, &gi)
	if gi.GetIntegration().GetPaired() {
		t.Fatal("paired before pairing")
	}
	gptFake.AddCode("BOBC2345")
	bob.must(403, "POST", "/api/workspaces/"+ws.GetId()+"/integrations/gptunnel", &v1.PairGptunnelRequest{Code: "BOBC-2345"}, nil)
	if st, e := o.apiErrBody("POST", "/api/workspaces/"+ws.GetId()+"/integrations/gptunnel", &v1.PairGptunnelRequest{Code: "ZZZZ-9999"}); st != 422 || e.GetCode() != v1.ErrorCode_ERROR_CODE_CODE_INVALID {
		t.Fatalf("wrong code: %d %v", st, e)
	}
	o.must(422, "POST", "/api/workspaces/"+ws.GetId()+"/integrations/gptunnel", &v1.PairGptunnelRequest{Code: "short"}, nil)
	pairWorkspace(t, o, ws.GetId())

	// Nobody in the call: 409 CONFLICT.
	if e := bob.rawErr("POST", "/api/rooms/"+rid+"/recording/start"); e.GetCode() != v1.ErrorCode_ERROR_CODE_CONFLICT {
		t.Fatalf("empty call: %v", e)
	}
	inCall(t, bob, ws, rid)

	g := dialGW(t)
	g.identify(o.token)
	var start v1.StartRecordingResponse
	bob.must(200, "POST", "/api/rooms/"+rid+"/recording/start", nil, &start)
	rec := start.GetRecording()
	if rec.GetState() != v1.RoomRecordingState_ROOM_RECORDING_STATE_ACTIVE || rec.GetByUserId() != bob.id || rec.GetRoomId() != rid || rec.GetSince() == nil {
		t.Fatalf("start: %v", rec)
	}
	g.wait("ROOM_RECORDING active", func(e *v1.DispatchEvent) bool {
		r := e.GetRoomRecording()
		return r.GetRecordingId() == rec.GetRecordingId() && r.GetState() == v1.RoomRecordingState_ROOM_RECORDING_STATE_ACTIVE
	})
	// Duplicate: 409 ALREADY_RECORDING.
	if e := o.rawErr("POST", "/api/rooms/"+rid+"/recording/start"); e.GetCode() != v1.ErrorCode_ERROR_CODE_ALREADY_RECORDING {
		t.Fatalf("duplicate: %v", e)
	}
	// READY of a new session lists the running recording.
	g2 := dialGW(t)
	ready := g2.identify(bob.token)
	found := false
	for _, snap := range ready.GetWorkspaces() {
		for _, r := range snap.GetRecordings() {
			found = found || r.GetRecordingId() == rec.GetRecordingId()
		}
	}
	if !found {
		t.Fatal("READY lacks the active recording")
	}

	// Stop → STOPPED at once; the egress is told to stop.
	var stop v1.StopRecordingResponse
	o.must(200, "POST", "/api/rooms/"+rid+"/recording/stop", nil, &stop)
	if stop.GetRecording().GetState() != v1.RoomRecordingState_ROOM_RECORDING_STATE_STOPPED || stop.GetRecording().GetStopReason() != "user" || stop.GetRecording().GetStoppedBy() != o.id {
		t.Fatalf("stop: %v", stop.GetRecording())
	}
	g.wait("ROOM_RECORDING stopped", func(e *v1.DispatchEvent) bool {
		return e.GetRoomRecording().GetState() == v1.RoomRecordingState_ROOM_RECORDING_STATE_STOPPED
	})
	o.must(404, "POST", "/api/rooms/"+rid+"/recording/stop", nil, nil)
	egFake.mu.Lock()
	var egressID string
	for id, info := range egFake.items {
		if strings.HasSuffix(info.RoomName, rid) {
			egressID = id
		}
	}
	filePath := egFake.starts[len(egFake.starts)-1].GetFileOutputs()[0].GetFilepath()
	egFake.mu.Unlock()
	if !egFake.stopped(egressID) || filePath != "/out/"+ws.GetId()+"/"+rec.GetRecordingId()+".mp4" {
		t.Fatalf("egress stop / path: %v %s", egFake.stopped(egressID), filePath)
	}

	// The egress writes the file and LiveKit sends egress_ended.
	data := make([]byte, 64<<10)
	_, _ = rand.Read(data)
	local := filepath.Join(recordDir, strings.TrimPrefix(filePath, "/out/"))
	if err := os.WriteFile(local, data, 0o600); err != nil {
		t.Fatal(err)
	}
	gptFake.Lock()
	gptFake.Statuses = []string{"transcribing", "done"}
	gptFake.Unlock()
	ended := egFake.end(egressID, int64(len(data)))
	if st := webhook(t, &livekit.WebhookEvent{Event: "egress_ended", Id: uniq("EV_eg"), CreatedAt: time.Now().Unix(), EgressInfo: ended}, "secret"); st != 200 {
		t.Fatalf("egress_ended: %d", st)
	}
	// Card: posted (uploading), then processing, then done — in the room chat, by the starter.
	created := g.wait("card posted", func(e *v1.DispatchEvent) bool { return card(e) != nil && e.GetMessageCreate() != nil })
	msg := created.GetMessageCreate().GetMessage()
	if msg.GetRoomId() != rid || msg.GetAuthorId() != bob.id || card(created).GetDurationSec() != 90 || card(created).GetRecordingId() != rec.GetRecordingId() {
		t.Fatalf("card: %v", msg)
	}
	deadline := time.Now().Add(10 * time.Second)
	var last *v1.RecordingCard
	for time.Now().Before(deadline) && last.GetStatus() != v1.RecordingStatus_RECORDING_STATUS_DONE {
		e := g.wait("card update", func(e *v1.DispatchEvent) bool {
			return card(e) != nil && e.GetMessageUpdate().GetMessage().GetId() == msg.GetId()
		})
		last = card(e)
	}
	if last.GetStatus() != v1.RecordingStatus_RECORDING_STATUS_DONE || !strings.HasPrefix(last.GetWebUrl(), "https://gptunnel.test/meetings/") {
		t.Fatalf("final card: %v", last)
	}
	// GPTunneL got exactly the file, as video/mp4, under our recording id.
	up, ok := gptFake.ByClientID(rec.GetRecordingId())
	if !ok || !bytes.Equal(up.Data, data) || up.Mime != "video/mp4" || up.Kind != "video" || up.DurationSec != 90 || !strings.HasPrefix(up.Title, "voice · ") {
		t.Fatalf("uploaded: ok=%v equal=%v %s %s %d %q", ok, bytes.Equal(up.Data, data), up.Mime, up.Kind, up.DurationSec, up.Title)
	}
	status, _, web, deleted := recState(t, rec.GetRecordingId())
	if status != "done" || web == "" || !deleted {
		t.Fatalf("row: %s %s deleted=%v", status, web, deleted)
	}
	if _, err := os.Stat(local); !os.IsNotExist(err) {
		t.Fatalf("file kept after done: %v", err)
	}
	// The card is in the history and cannot be edited.
	var list v1.ListMessagesResponse
	bob.must(200, "GET", "/api/rooms/"+rid+"/messages", nil, &list)
	if len(list.GetMessages()) == 0 || list.GetMessages()[0].GetSystem().GetRecording().GetStatus() != v1.RecordingStatus_RECORDING_STATUS_DONE {
		t.Fatalf("history: %v", list.GetMessages())
	}
	content := "x"
	bob.must(403, "PATCH", "/api/messages/"+msg.GetId(), &v1.UpdateMessageRequest{Content: content}, nil)
	// Redelivered egress_ended changes nothing.
	if st := webhook(t, &livekit.WebhookEvent{Event: "egress_ended", Id: uniq("EV_eg"), CreatedAt: time.Now().Unix(), EgressInfo: ended}, "secret"); st != 200 {
		t.Fatalf("redelivery: %d", st)
	}
}

func TestRecordingRightsAndLimits(t *testing.T) {
	liveKitUp(t)
	o, bob, ws, room := setupTeam(t)
	rid := room.GetId()
	pairWorkspace(t, o, ws.GetId())
	inCall(t, bob, ws, rid)

	// A guest cannot record, even with access to the room.
	gus := register(t, invite(t, o, ws.GetId()))
	guest := v1.WorkspaceRole_WORKSPACE_ROLE_GUEST
	o.must(200, "PATCH", "/api/workspaces/"+ws.GetId()+"/members/"+gus.id, &v1.UpdateMemberRequest{Role: &guest}, nil)
	o.must(200, "PUT", "/api/rooms/"+rid+"/permissions", &v1.SetRoomPermissionsRequest{Overrides: []*v1.RoomPermissionOverride{
		{TargetType: v1.PermissionTargetType_PERMISSION_TARGET_TYPE_ROLE, TargetId: "guest", Allow: 1}, // VIEW_ROOM
	}}, nil)
	gus.must(403, "POST", "/api/rooms/"+rid+"/recording/start", nil, nil)
	gus.must(403, "GET", "/api/workspaces/"+ws.GetId()+"/integrations/gptunnel", nil, nil)

	// allow_recording: only MANAGE_WORKSPACE changes it; off = 403 for everybody.
	off := false
	bob.must(403, "PATCH", "/api/rooms/"+rid, &v1.UpdateRoomRequest{AllowRecording: &off}, nil)
	var upd v1.UpdateRoomResponse
	o.must(200, "PATCH", "/api/rooms/"+rid, &v1.UpdateRoomRequest{AllowRecording: &off}, &upd)
	if upd.GetRoom().GetAllowRecording() {
		t.Fatal("allow_recording not switched off")
	}
	bob.must(403, "POST", "/api/rooms/"+rid+"/recording/start", nil, nil)
	on := true
	o.must(200, "PATCH", "/api/rooms/"+rid, &v1.UpdateRoomRequest{AllowRecording: &on}, nil)

	// Server-wide limit: RECORDING_MAX_CONCURRENT (2 in tests) running elsewhere → 409.
	var others []string
	for range testCfg.RecordingMaxConcurrent {
		var cr v1.CreateRoomResponse
		o.must(201, "POST", "/api/workspaces/"+ws.GetId()+"/rooms", &v1.CreateRoomRequest{Type: v1.RoomType_ROOM_TYPE_VOICE, Name: "busy"}, &cr)
		var id string
		// 'pending' (a start in progress): the worker's reconcile leaves it alone for 2 min.
		if err := testDB.Pool.QueryRow(context.Background(), `INSERT INTO room_recordings (workspace_id, room_id, status, file)
			VALUES ($1, $2, 'pending', 'x.mp4') RETURNING id`, ws.GetId(), cr.GetRoom().GetId()).Scan(&id); err != nil {
			t.Fatal(err)
		}
		others = append(others, id)
	}
	e := bob.rawErr("POST", "/api/rooms/"+rid+"/recording/start")
	if e.GetCode() != v1.ErrorCode_ERROR_CODE_RECORDING_LIMIT || fmt.Sprint(e.GetLimit()) != fmt.Sprint(testCfg.RecordingMaxConcurrent) {
		t.Fatalf("limit: %v", e)
	}
	if _, err := testDB.Pool.Exec(context.Background(), `DELETE FROM room_recordings WHERE id = ANY($1::uuid[])`, others); err != nil {
		t.Fatal(err)
	}

	// Recorder unavailable: 503, the attempt is logged as failed and does not block the room.
	egFake.mu.Lock()
	egFake.fail = true
	egFake.mu.Unlock()
	bob.must(503, "POST", "/api/rooms/"+rid+"/recording/start", nil, nil)
	egFake.mu.Lock()
	egFake.fail = false
	egFake.mu.Unlock()

	// Unpair: DELETE revokes the token in GPTunneL; starting needs pairing again.
	bob.must(403, "DELETE", "/api/workspaces/"+ws.GetId()+"/integrations/gptunnel", nil, nil)
	o.must(204, "DELETE", "/api/workspaces/"+ws.GetId()+"/integrations/gptunnel", nil, nil)
	if e := bob.rawErr("POST", "/api/rooms/"+rid+"/recording/start"); e.GetCode() != v1.ErrorCode_ERROR_CODE_NOT_PAIRED {
		t.Fatalf("after unpair: %v", e)
	}
}

// TestRecordingFailuresAndReconcile: an egress that ended without a webhook is taken over by
// reconcile; GPTunneL's insufficient_balance fails the recording with that reason on the
// card; a device revoked in GPTunneL disconnects the workspace.
func TestRecordingFailuresAndReconcile(t *testing.T) {
	liveKitUp(t)
	o, bob, ws, room := setupTeam(t)
	rid := room.GetId()
	pairWorkspace(t, o, ws.GetId())
	inCall(t, bob, ws, rid)
	g := dialGW(t)
	g.identify(o.token)

	var start v1.StartRecordingResponse
	bob.must(200, "POST", "/api/rooms/"+rid+"/recording/start", nil, &start)
	recID := start.GetRecording().GetRecordingId()
	egFake.mu.Lock()
	req := egFake.starts[len(egFake.starts)-1]
	var egressID string
	for id, info := range egFake.items {
		if info.RoomName == req.GetRoomName() && info.Status == livekit.EgressStatus_EGRESS_STARTING {
			egressID = id
		}
	}
	egFake.mu.Unlock()
	local := filepath.Join(recordDir, strings.TrimPrefix(req.GetFileOutputs()[0].GetFilepath(), "/out/"))
	if err := os.WriteFile(local, []byte("mp4 bytes"), 0o600); err != nil {
		t.Fatal(err)
	}
	gptFake.Lock()
	gptFake.CreateError = "insufficient_balance"
	gptFake.Unlock()
	defer func() {
		gptFake.Lock()
		gptFake.CreateError = ""
		gptFake.Unlock()
	}()
	egFake.end(egressID, 9) // the call ended by itself; the webhook is lost
	if err := testApp.Recording.Reconcile(context.Background()); err != nil {
		t.Fatal(err)
	}
	g.wait("ROOM_RECORDING stopped by reconcile", func(e *v1.DispatchEvent) bool {
		r := e.GetRoomRecording()
		return r.GetRecordingId() == recID && r.GetState() == v1.RoomRecordingState_ROOM_RECORDING_STATE_STOPPED && r.GetStopReason() == "egress"
	})
	g.wait("failed card", func(e *v1.DispatchEvent) bool {
		c := card(e)
		return c.GetRecordingId() == recID && c.GetStatus() == v1.RecordingStatus_RECORDING_STATUS_FAILED && c.GetError() == "insufficient_balance"
	})
	if status, code, _, _ := recState(t, recID); status != "failed" || code != "insufficient_balance" {
		t.Fatalf("row: %s %s", status, code)
	}

	// Device revoked in GPTunneL: the upload fails with device_revoked and the workspace shows
	// as not connected.
	gptFake.Lock()
	gptFake.CreateError = ""
	gptFake.Unlock()
	bob.must(200, "POST", "/api/rooms/"+rid+"/recording/start", nil, &start)
	recID = start.GetRecording().GetRecordingId()
	egFake.mu.Lock()
	req = egFake.starts[len(egFake.starts)-1]
	for id, info := range egFake.items {
		if info.RoomName == req.GetRoomName() && info.Status == livekit.EgressStatus_EGRESS_STARTING {
			egressID = id
		}
	}
	egFake.mu.Unlock()
	local = filepath.Join(recordDir, strings.TrimPrefix(req.GetFileOutputs()[0].GetFilepath(), "/out/"))
	if err := os.WriteFile(local, []byte("mp4 bytes"), 0o600); err != nil {
		t.Fatal(err)
	}
	gptFake.RevokeAll()
	ended := egFake.end(egressID, 9)
	if st := webhook(t, &livekit.WebhookEvent{Event: "egress_ended", Id: uniq("EV_eg"), CreatedAt: time.Now().Unix(), EgressInfo: ended}, "secret"); st != 200 {
		t.Fatalf("egress_ended: %d", st)
	}
	g.wait("revoked card", func(e *v1.DispatchEvent) bool {
		c := card(e)
		return c.GetRecordingId() == recID && c.GetStatus() == v1.RecordingStatus_RECORDING_STATUS_FAILED && c.GetError() == "device_revoked"
	})
	var gi v1.GetGptunnelIntegrationResponse
	o.must(200, "GET", "/api/workspaces/"+ws.GetId()+"/integrations/gptunnel", nil, &gi)
	if gi.GetIntegration().GetPaired() {
		t.Fatal("still paired after the device was revoked")
	}
	// Janitor: failed recordings keep their file for 7 days, then it goes.
	testApp.Recording.Janitor(context.Background())
	if _, err := os.Stat(local); err != nil {
		t.Fatalf("file of a fresh failed recording removed: %v", err)
	}
	if _, err := testDB.Pool.Exec(context.Background(), `UPDATE room_recordings SET stopped_at = now() - interval '8 days' WHERE id = $1`, recID); err != nil {
		t.Fatal(err)
	}
	testApp.Recording.Janitor(context.Background())
	if _, err := os.Stat(local); !os.IsNotExist(err) {
		t.Fatalf("old file kept: %v", err)
	}
}

// lastEgress returns the id of the newest egress of room rid.
func lastEgress(t *testing.T, rid string) string {
	t.Helper()
	egFake.mu.Lock()
	defer egFake.mu.Unlock()
	var id string
	var at int64
	for eid, info := range egFake.items {
		if strings.HasSuffix(info.RoomName, "_room_"+rid) && info.StartedAt >= at {
			id, at = eid, info.StartedAt
		}
	}
	return id
}

// TestRecordingAutoStop: 4 h limit and an empty call stop the recording (the worker's
// Maintain); an egress that ends without a file fails the recording with no_audio.
func TestRecordingAutoStop(t *testing.T) {
	liveKitUp(t)
	o, bob, ws, room := setupTeam(t)
	rid := room.GetId()
	pairWorkspace(t, o, ws.GetId())
	identity := inCall(t, bob, ws, rid)
	g := dialGW(t)
	g.identify(o.token)
	ctx := context.Background()
	endWithoutFile := func(recID string) {
		t.Helper()
		id := lastEgress(t, rid)
		egFake.mu.Lock()
		info := egFake.items[id]
		info.Status = livekit.EgressStatus_EGRESS_COMPLETE
		egFake.mu.Unlock()
		if st := webhook(t, &livekit.WebhookEvent{Event: "egress_ended", Id: uniq("EV_eg"), CreatedAt: time.Now().Unix(), EgressInfo: info}, "secret"); st != 200 {
			t.Fatalf("egress_ended: %d", st)
		}
		g.wait("no_audio card", func(e *v1.DispatchEvent) bool {
			c := card(e)
			return c.GetRecordingId() == recID && c.GetStatus() == v1.RecordingStatus_RECORDING_STATUS_FAILED && c.GetError() == "no_audio"
		})
	}

	var start v1.StartRecordingResponse
	bob.must(200, "POST", "/api/rooms/"+rid+"/recording/start", nil, &start)
	recID := start.GetRecording().GetRecordingId()
	if _, err := testDB.Pool.Exec(ctx, `UPDATE room_recordings SET started_at = now() - interval '5 hours' WHERE id = $1`, recID); err != nil {
		t.Fatal(err)
	}
	testApp.Recording.Maintain(ctx)
	g.wait("stopped at 4 h", func(e *v1.DispatchEvent) bool {
		r := e.GetRoomRecording()
		return r.GetRecordingId() == recID && r.GetState() == v1.RoomRecordingState_ROOM_RECORDING_STATE_STOPPED && r.GetStopReason() == "max_duration"
	})
	if !egFake.stopped(lastEgress(t, rid)) {
		t.Fatal("egress not stopped at the limit")
	}
	endWithoutFile(recID)

	bob.must(200, "POST", "/api/rooms/"+rid+"/recording/start", nil, &start)
	recID = start.GetRecording().GetRecordingId()
	if st := webhook(t, whEvent("participant_left", "ws_"+ws.GetId()+"_room_"+rid, identity, nil), "secret"); st != 200 {
		t.Fatalf("participant_left: %d", st)
	}
	testApp.Recording.Maintain(ctx) // notes the empty call
	var empty *time.Time
	if err := testDB.Pool.QueryRow(ctx, `SELECT empty_since FROM room_recordings WHERE id = $1`, recID).Scan(&empty); err != nil || empty == nil {
		t.Fatalf("empty_since: %v %v", empty, err)
	}
	if _, err := testDB.Pool.Exec(ctx, `UPDATE room_recordings SET empty_since = now() - interval '3 minutes' WHERE id = $1`, recID); err != nil {
		t.Fatal(err)
	}
	testApp.Recording.Maintain(ctx)
	g.wait("stopped when empty", func(e *v1.DispatchEvent) bool {
		r := e.GetRoomRecording()
		return r.GetRecordingId() == recID && r.GetState() == v1.RoomRecordingState_ROOM_RECORDING_STATE_STOPPED && r.GetStopReason() == "empty"
	})
	endWithoutFile(recID)
}
