import type { ReactNode } from 'react';
// Bundled by Vite straight from build/icons (as the guest screen does): one source of truth.
import logoUrl from '../../../build/icons/web/icon-192.png';
import { cx } from './ui';

/**
 * The owner's app icon (build/icons/web/icon-192.png, generated by scripts/gen-icons.sh from
 * build/icons/src/icon_other.svg). Decorative next to the «Calab» wordmark: alt is empty.
 */
export function Logo({ size = 64, className, alt = '' }: { size?: number; className?: string; alt?: string }): ReactNode {
  return <img src={logoUrl} width={size} height={size} alt={alt} draggable={false} className={cx('shrink-0 select-none', className)} />;
}
