// Package db owns the Postgres pool, embedded migrations and transactions.
// Queries are generated by sqlc into internal/db/sqlc (see sqlc.yaml).
package db

import (
	"context"
	"embed"
	"errors"
	"fmt"
	"io/fs"
	"log/slog"
	"strings"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/jackc/pgx/v5/stdlib"
	"github.com/pressly/goose/v3"
	"github.com/pressly/goose/v3/lock"

	"github.com/calaba/calaba/server/internal/db/sqlc"
)

//go:embed migrations/*.sql
var migrationsFS embed.FS

// DB bundles the pool and the sqlc queries bound to it.
type DB struct {
	Pool *pgxpool.Pool
	Q    *sqlc.Queries
}

// Connect opens a pool and pings it.
func Connect(ctx context.Context, url string) (*DB, error) {
	cfg, err := pgxpool.ParseConfig(url)
	if err != nil {
		return nil, fmt.Errorf("db: parse url: %w", err)
	}
	// pgx's default (max(4, NumCPU)) is too small for IDENTIFY storms after a deploy
	// (review L16). ?pool_max_conns=N in DATABASE_URL overrides this.
	if !strings.Contains(url, "pool_max_conns") {
		cfg.MaxConns = 20
	}
	pool, err := pgxpool.NewWithConfig(ctx, cfg)
	if err != nil {
		return nil, fmt.Errorf("db: connect: %w", err)
	}
	if err := pool.Ping(ctx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("db: ping: %w", err)
	}
	return &DB{Pool: pool, Q: sqlc.New(pool)}, nil
}

// Close closes the pool.
func (d *DB) Close() { d.Pool.Close() }

// Tx runs fn in a transaction; it commits when fn returns nil and rolls back otherwise.
func (d *DB) Tx(ctx context.Context, fn func(q *sqlc.Queries) error) error {
	return pgx.BeginFunc(ctx, d.Pool, func(tx pgx.Tx) error {
		return fn(d.Q.WithTx(tx))
	})
}

func newProvider(d *DB) (*goose.Provider, error) {
	sub, err := fs.Sub(migrationsFS, "migrations")
	if err != nil {
		return nil, err
	}
	// Session-level pg_advisory_lock: with several replicas only one migrates, others wait.
	locker, err := lock.NewPostgresSessionLocker()
	if err != nil {
		return nil, err
	}
	return goose.NewProvider(goose.DialectPostgres, stdlib.OpenDBFromPool(d.Pool), sub,
		goose.WithSessionLocker(locker))
}

// Migrate applies all pending migrations under an advisory lock.
func (d *DB) Migrate(ctx context.Context) error {
	p, err := newProvider(d)
	if err != nil {
		return fmt.Errorf("migrate: %w", err)
	}
	res, err := p.Up(ctx)
	if err != nil {
		return fmt.Errorf("migrate: %w", err)
	}
	for _, r := range res {
		slog.Info("migration applied", "version", r.Source.Version, "file", r.Source.Path, "dur", r.Duration)
	}
	return nil
}

// MigrationStatus returns "version applied|pending" lines.
func (d *DB) MigrationStatus(ctx context.Context) ([]string, error) {
	p, err := newProvider(d)
	if err != nil {
		return nil, err
	}
	st, err := p.Status(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]string, 0, len(st))
	for _, s := range st {
		out = append(out, fmt.Sprintf("%05d %-8s %s", s.Source.Version, s.State, s.Source.Path))
	}
	return out, nil
}

// IsNotFound reports whether err is "no rows".
func IsNotFound(err error) bool { return errors.Is(err, pgx.ErrNoRows) }

// UniqueViolation returns the violated constraint name, or "" if err is not a unique violation.
func UniqueViolation(err error) string {
	var pe *pgconn.PgError
	if errors.As(err, &pe) && pe.Code == "23505" {
		return pe.ConstraintName
	}
	return ""
}

// IsForeignKeyViolation reports a 23503 error.
func IsForeignKeyViolation(err error) bool {
	var pe *pgconn.PgError
	return errors.As(err, &pe) && pe.Code == "23503"
}
