-- ADR-0058 §4: the board webhook and its outbox (the bot_webhook_deliveries pattern).

-- name: GetBoardWebhook :one
SELECT * FROM board_webhooks WHERE board_id = $1;

-- name: UpsertBoardWebhook :one
-- PUT: creates or replaces the webhook and (re)enables it; next_seq keeps counting.
INSERT INTO board_webhooks (board_id, url, secret_enc, created_by)
VALUES (sqlc.arg('board_id'), sqlc.arg('url'), sqlc.arg('secret_enc'), sqlc.narg('created_by'))
ON CONFLICT (board_id) DO UPDATE SET
    url = excluded.url, secret_enc = excluded.secret_enc, disabled_at = NULL,
    failing_since = NULL, last_error = '', updated_at = now()
RETURNING *;

-- name: DeleteBoardWebhook :execrows
DELETE FROM board_webhooks WHERE board_id = $1;

-- name: NextBoardWebhookSeq :one
-- Inside the change's transaction: takes the board's next sequence number of an enabled
-- webhook (no row = no webhook or disabled: nothing to queue). The row lock serializes the
-- board's writers until commit.
UPDATE board_webhooks SET next_seq = next_seq + 1
WHERE board_id = $1 AND disabled_at IS NULL
RETURNING (next_seq - 1)::bigint AS seq;

-- name: EnqueueBoardWebhookDelivery :exec
-- id is generated by the application (uuid v7): the body carries its delivery id.
INSERT INTO board_webhook_deliveries (id, board_id, seq, event_type, payload)
VALUES ($1, $2, $3, $4, $5);

-- name: ClaimBoardWebhookDeliveries :many
-- Takes due deliveries: next_at moves one lease ahead (a crashed worker's rows come back).
UPDATE board_webhook_deliveries SET next_at = now() + sqlc.arg('lease')::interval
WHERE id IN (
    SELECT d.id FROM board_webhook_deliveries d
    WHERE d.delivered_at IS NULL AND d.failed_at IS NULL AND d.next_at <= now()
    ORDER BY d.next_at, d.id
    LIMIT sqlc.arg('lim')
    FOR UPDATE SKIP LOCKED
)
RETURNING *;

-- name: MarkBoardWebhookDelivered :exec
UPDATE board_webhook_deliveries SET delivered_at = now(), payload = NULL, attempts = attempts + 1, error = ''
WHERE id = $1;

-- name: MarkBoardWebhookRetry :exec
UPDATE board_webhook_deliveries SET attempts = attempts + 1, next_at = $2, error = $3 WHERE id = $1;

-- name: MarkBoardWebhookFailed :exec
UPDATE board_webhook_deliveries SET attempts = attempts + 1, failed_at = now(), payload = NULL, error = $2
WHERE id = $1;

-- name: FailPendingBoardWebhookDeliveries :exec
UPDATE board_webhook_deliveries SET failed_at = now(), payload = NULL, error = $2
WHERE board_id = $1 AND delivered_at IS NULL AND failed_at IS NULL;

-- name: CountPendingBoardWebhookDeliveries :one
SELECT count(*)::integer FROM board_webhook_deliveries
WHERE board_id = $1 AND delivered_at IS NULL AND failed_at IS NULL;

-- name: DeleteOldBoardWebhookDeliveries :execrows
DELETE FROM board_webhook_deliveries
WHERE created_at < $1 AND (delivered_at IS NOT NULL OR failed_at IS NOT NULL);

-- name: BoardWebhookOK :exec
UPDATE board_webhooks SET last_ok_at = now(), failing_since = NULL, last_error = ''
WHERE board_id = $1;

-- name: BoardWebhookFailing :one
UPDATE board_webhooks SET failing_since = coalesce(failing_since, now()), last_error = $2
WHERE board_id = $1
RETURNING *;

-- name: DisableBoardWebhook :one
UPDATE board_webhooks SET disabled_at = now() WHERE board_id = $1 AND disabled_at IS NULL
RETURNING *;
