-- Initial schema, see docs/04-data-model.md.
-- All ids are uuid v7 generated by Postgres 18 (uuidv7()); all times are timestamptz.

-- +goose Up
CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE users (
    id             uuid PRIMARY KEY DEFAULT uuidv7(),
    email          citext NOT NULL UNIQUE,
    password_hash  text,                                  -- NULL for future OIDC-only users
    display_name   text NOT NULL CHECK (char_length(display_name) BETWEEN 1 AND 64),
    avatar_file_id uuid,                                  -- FK added below (files)
    status_text    text NOT NULL DEFAULT '' CHECK (char_length(status_text) <= 128),
    settings       jsonb NOT NULL DEFAULT '{}',           -- calaba.v1.UserSettings (protojson)
    created_at     timestamptz NOT NULL DEFAULT now(),
    disabled_at    timestamptz
);

CREATE TABLE sessions (
    id                      uuid PRIMARY KEY DEFAULT uuidv7(),
    user_id                 uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    refresh_token_hash      bytea NOT NULL,               -- sha256 of the current refresh secret
    prev_refresh_token_hash bytea,                        -- previous secret, for the concurrent-refresh grace window
    rotated_at              timestamptz,
    device_name             text NOT NULL DEFAULT '',
    ip                      text NOT NULL DEFAULT '',
    user_agent              text NOT NULL DEFAULT '',
    created_at              timestamptz NOT NULL DEFAULT now(),
    last_seen_at            timestamptz NOT NULL DEFAULT now(),
    expires_at              timestamptz NOT NULL,
    revoked_at              timestamptz
);
CREATE INDEX sessions_user_id_idx ON sessions (user_id) WHERE revoked_at IS NULL;

CREATE TABLE workspaces (
    id                         uuid PRIMARY KEY DEFAULT uuidv7(),
    slug                       text NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9-]{3,32}$'),
    name                       text NOT NULL CHECK (char_length(name) BETWEEN 1 AND 100),
    icon_file_id               uuid,                      -- FK added below (files)
    visibility                 text NOT NULL DEFAULT 'private' CHECK (visibility IN ('private', 'open')),
    owner_id                   uuid NOT NULL REFERENCES users (id),
    created_at                 timestamptz NOT NULL DEFAULT now(),
    default_audio_bitrate_kbps integer NOT NULL DEFAULT 32 CHECK (default_audio_bitrate_kbps IN (16, 24, 32, 48, 64)),
    default_max_stream_preset  text NOT NULL DEFAULT 'h1080'
        CHECK (default_max_stream_preset IN ('economy', 'h720', 'h1080', 'original')),
    default_max_streams        integer NOT NULL DEFAULT 3 CHECK (default_max_streams BETWEEN 0 AND 10),
    storage_quota_bytes        bigint NOT NULL DEFAULT 10737418240 CHECK (storage_quota_bytes >= 0), -- 10 GiB
    storage_used_bytes         bigint NOT NULL DEFAULT 0 CHECK (storage_used_bytes >= 0)
);

CREATE TABLE workspace_members (
    workspace_id uuid NOT NULL REFERENCES workspaces (id) ON DELETE CASCADE,
    user_id      uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role         text NOT NULL CHECK (role IN ('owner', 'admin', 'member', 'guest')),
    nickname     text NOT NULL DEFAULT '' CHECK (char_length(nickname) <= 64),
    joined_at    timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (workspace_id, user_id)
);
CREATE INDEX workspace_members_user_id_idx ON workspace_members (user_id);

CREATE TABLE workspace_invites (
    id           uuid PRIMARY KEY DEFAULT uuidv7(),
    workspace_id uuid NOT NULL REFERENCES workspaces (id) ON DELETE CASCADE,
    code         text NOT NULL UNIQUE,
    created_by   uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    max_uses     integer NOT NULL DEFAULT 0 CHECK (max_uses >= 0), -- 0 = unlimited
    uses         integer NOT NULL DEFAULT 0 CHECK (uses >= 0),
    expires_at   timestamptz,
    created_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX workspace_invites_workspace_id_idx ON workspace_invites (workspace_id);

CREATE TABLE rooms (
    id                 uuid PRIMARY KEY DEFAULT uuidv7(),
    workspace_id       uuid NOT NULL REFERENCES workspaces (id) ON DELETE CASCADE,
    type               text NOT NULL CHECK (type IN ('voice', 'text')),
    name               text NOT NULL CHECK (char_length(name) BETWEEN 1 AND 100),
    topic              text NOT NULL DEFAULT '' CHECK (char_length(topic) <= 1024),
    position           integer NOT NULL DEFAULT 0,
    is_private         boolean NOT NULL DEFAULT false,
    -- Media overrides; NULL = workspace default.
    audio_bitrate_kbps integer CHECK (audio_bitrate_kbps IN (16, 24, 32, 48, 64)),
    max_stream_preset  text CHECK (max_stream_preset IN ('economy', 'h720', 'h1080', 'original')),
    max_streams        integer CHECK (max_streams BETWEEN 0 AND 10),
    created_at         timestamptz NOT NULL DEFAULT now(),
    archived_at        timestamptz
);
CREATE INDEX rooms_workspace_id_idx ON rooms (workspace_id, position) WHERE archived_at IS NULL;

CREATE TABLE room_permissions (
    room_id     uuid NOT NULL REFERENCES rooms (id) ON DELETE CASCADE,
    target_type text NOT NULL CHECK (target_type IN ('role', 'user')),
    target_id   text NOT NULL,                            -- role name or user uuid
    allow       bigint NOT NULL DEFAULT 0,
    deny        bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (room_id, target_type, target_id)
);

CREATE TABLE files (
    id            uuid PRIMARY KEY DEFAULT uuidv7(),
    workspace_id  uuid NOT NULL REFERENCES workspaces (id) ON DELETE CASCADE,
    uploader_id   uuid NOT NULL REFERENCES users (id),
    key           text NOT NULL,                          -- blob.Store key, <workspace_id>/<file_id> (ADR-0011)
    thumbnail_key text,
    name          text NOT NULL,
    mime          text NOT NULL,
    size          bigint NOT NULL CHECK (size >= 0),
    width         integer,
    height        integer,
    sha256        text NOT NULL,
    created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX files_workspace_id_idx ON files (workspace_id);

ALTER TABLE users
    ADD CONSTRAINT users_avatar_file_id_fkey FOREIGN KEY (avatar_file_id) REFERENCES files (id) ON DELETE SET NULL;
ALTER TABLE workspaces
    ADD CONSTRAINT workspaces_icon_file_id_fkey FOREIGN KEY (icon_file_id) REFERENCES files (id) ON DELETE SET NULL;

CREATE TABLE messages (
    id          uuid PRIMARY KEY DEFAULT uuidv7(),        -- order of ids = order of commits
    room_id     uuid NOT NULL REFERENCES rooms (id) ON DELETE CASCADE,
    author_id   uuid NOT NULL REFERENCES users (id),
    content     text NOT NULL CHECK (char_length(content) <= 4000),
    reply_to_id uuid REFERENCES messages (id) ON DELETE SET NULL,
    nonce       text CHECK (char_length(nonce) <= 64),
    created_at  timestamptz NOT NULL DEFAULT now(),
    edited_at   timestamptz,
    deleted_at  timestamptz
);
CREATE INDEX messages_room_id_id_idx ON messages (room_id, id DESC);
CREATE UNIQUE INDEX messages_author_nonce_key ON messages (author_id, nonce) WHERE nonce IS NOT NULL;

CREATE TABLE message_attachments (
    message_id uuid NOT NULL REFERENCES messages (id) ON DELETE CASCADE,
    file_id    uuid NOT NULL REFERENCES files (id) ON DELETE CASCADE,
    position   smallint NOT NULL CHECK (position BETWEEN 0 AND 19),
    PRIMARY KEY (message_id, position),
    UNIQUE (message_id, file_id)
);
CREATE INDEX message_attachments_file_id_idx ON message_attachments (file_id);

CREATE TABLE read_states (
    user_id              uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    room_id              uuid NOT NULL REFERENCES rooms (id) ON DELETE CASCADE,
    last_read_message_id uuid NOT NULL,
    PRIMARY KEY (user_id, room_id)
);

-- +goose Down
DROP TABLE read_states;
DROP TABLE message_attachments;
DROP TABLE messages;
ALTER TABLE workspaces DROP CONSTRAINT workspaces_icon_file_id_fkey;
ALTER TABLE users DROP CONSTRAINT users_avatar_file_id_fkey;
DROP TABLE files;
DROP TABLE room_permissions;
DROP TABLE rooms;
DROP TABLE workspace_invites;
DROP TABLE workspace_members;
DROP TABLE workspaces;
DROP TABLE sessions;
DROP TABLE users;
