// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apps.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countWorkspaceApps = `-- name: CountWorkspaceApps :one
SELECT count(*)::integer FROM workspace_apps WHERE workspace_id = $1
`

func (q *Queries) CountWorkspaceApps(ctx context.Context, workspaceID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countWorkspaceApps, workspaceID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteWorkspaceApp = `-- name: DeleteWorkspaceApp :execrows
DELETE FROM workspace_apps WHERE id = $1
`

func (q *Queries) DeleteWorkspaceApp(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWorkspaceApp, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWorkspaceApp = `-- name: GetWorkspaceApp :one
SELECT id, workspace_id, name, url, icon_file_id, position, created_by, created_at, updated_at FROM workspace_apps WHERE id = $1
`

func (q *Queries) GetWorkspaceApp(ctx context.Context, id uuid.UUID) (WorkspaceApp, error) {
	row := q.db.QueryRow(ctx, getWorkspaceApp, id)
	var i WorkspaceApp
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Url,
		&i.IconFileID,
		&i.Position,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertWorkspaceApp = `-- name: InsertWorkspaceApp :one
INSERT INTO workspace_apps (workspace_id, name, url, icon_file_id, created_by, position)
VALUES ($1, $2, $3, $4, $5,
        (SELECT coalesce(max(a.position), 0) + 1 FROM workspace_apps a WHERE a.workspace_id = $1))
RETURNING id, workspace_id, name, url, icon_file_id, position, created_by, created_at, updated_at
`

type InsertWorkspaceAppParams struct {
	WorkspaceID uuid.UUID
	Name        string
	Url         string
	IconFileID  *uuid.UUID
	CreatedBy   *uuid.UUID
}

func (q *Queries) InsertWorkspaceApp(ctx context.Context, arg InsertWorkspaceAppParams) (WorkspaceApp, error) {
	row := q.db.QueryRow(ctx, insertWorkspaceApp,
		arg.WorkspaceID,
		arg.Name,
		arg.Url,
		arg.IconFileID,
		arg.CreatedBy,
	)
	var i WorkspaceApp
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Url,
		&i.IconFileID,
		&i.Position,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isWorkspaceAppIcon = `-- name: IsWorkspaceAppIcon :one
SELECT EXISTS (SELECT 1 FROM workspace_apps WHERE icon_file_id = $1)::boolean
`

// The file is the icon of a web app (files.CanRead: members of its workspace).
func (q *Queries) IsWorkspaceAppIcon(ctx context.Context, iconFileID *uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isWorkspaceAppIcon, iconFileID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listWorkspaceApps = `-- name: ListWorkspaceApps :many
SELECT id, workspace_id, name, url, icon_file_id, position, created_by, created_at, updated_at FROM workspace_apps WHERE workspace_id = $1 ORDER BY position, id
`

func (q *Queries) ListWorkspaceApps(ctx context.Context, workspaceID uuid.UUID) ([]WorkspaceApp, error) {
	rows, err := q.db.Query(ctx, listWorkspaceApps, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceApp{}
	for rows.Next() {
		var i WorkspaceApp
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Url,
			&i.IconFileID,
			&i.Position,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockWorkspaceApps = `-- name: LockWorkspaceApps :exec

SELECT pg_advisory_xact_lock(hashtext('calaba.apps.' || $1::uuid::text))
`

// Web apps of a workspace (ADR-0050).
// Serializes creation and reordering of one workspace's apps.
func (q *Queries) LockWorkspaceApps(ctx context.Context, workspaceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockWorkspaceApps, workspaceID)
	return err
}

const setWorkspaceAppPosition = `-- name: SetWorkspaceAppPosition :one
UPDATE workspace_apps SET position = $2, updated_at = now() WHERE id = $1
RETURNING id, workspace_id, name, url, icon_file_id, position, created_by, created_at, updated_at
`

type SetWorkspaceAppPositionParams struct {
	ID       uuid.UUID
	Position float64
}

func (q *Queries) SetWorkspaceAppPosition(ctx context.Context, arg SetWorkspaceAppPositionParams) (WorkspaceApp, error) {
	row := q.db.QueryRow(ctx, setWorkspaceAppPosition, arg.ID, arg.Position)
	var i WorkspaceApp
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Url,
		&i.IconFileID,
		&i.Position,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWorkspaceApp = `-- name: UpdateWorkspaceApp :one
UPDATE workspace_apps SET
    name         = coalesce($1, name),
    url          = coalesce($2, url),
    icon_file_id = CASE WHEN $3::boolean THEN $4::uuid ELSE icon_file_id END,
    updated_at   = now()
WHERE id = $5
RETURNING id, workspace_id, name, url, icon_file_id, position, created_by, created_at, updated_at
`

type UpdateWorkspaceAppParams struct {
	Name       *string
	Url        *string
	SetIcon    bool
	IconFileID *uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) UpdateWorkspaceApp(ctx context.Context, arg UpdateWorkspaceAppParams) (WorkspaceApp, error) {
	row := q.db.QueryRow(ctx, updateWorkspaceApp,
		arg.Name,
		arg.Url,
		arg.SetIcon,
		arg.IconFileID,
		arg.ID,
	)
	var i WorkspaceApp
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Url,
		&i.IconFileID,
		&i.Position,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
