// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backgrounds.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countWorkspaceBackgrounds = `-- name: CountWorkspaceBackgrounds :one
SELECT count(*)::integer FROM workspace_backgrounds WHERE workspace_id = $1
`

func (q *Queries) CountWorkspaceBackgrounds(ctx context.Context, workspaceID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countWorkspaceBackgrounds, workspaceID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteWorkspaceBackground = `-- name: DeleteWorkspaceBackground :execrows
DELETE FROM workspace_backgrounds WHERE id = $1 AND workspace_id = $2
`

type DeleteWorkspaceBackgroundParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) DeleteWorkspaceBackground(ctx context.Context, arg DeleteWorkspaceBackgroundParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWorkspaceBackground, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWorkspaceBackground = `-- name: GetWorkspaceBackground :one
SELECT id, workspace_id, name, file_id, position, created_at FROM workspace_backgrounds WHERE id = $1 AND workspace_id = $2
`

type GetWorkspaceBackgroundParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) GetWorkspaceBackground(ctx context.Context, arg GetWorkspaceBackgroundParams) (WorkspaceBackground, error) {
	row := q.db.QueryRow(ctx, getWorkspaceBackground, arg.ID, arg.WorkspaceID)
	var i WorkspaceBackground
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.FileID,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const insertWorkspaceBackground = `-- name: InsertWorkspaceBackground :one
INSERT INTO workspace_backgrounds (workspace_id, name, file_id, position)
VALUES ($1, $2, $3, (SELECT coalesce(max(b.position), -1) + 1 FROM workspace_backgrounds b WHERE b.workspace_id = $1)::smallint)
RETURNING id, workspace_id, name, file_id, position, created_at
`

type InsertWorkspaceBackgroundParams struct {
	WorkspaceID uuid.UUID
	Name        string
	FileID      uuid.UUID
}

func (q *Queries) InsertWorkspaceBackground(ctx context.Context, arg InsertWorkspaceBackgroundParams) (WorkspaceBackground, error) {
	row := q.db.QueryRow(ctx, insertWorkspaceBackground, arg.WorkspaceID, arg.Name, arg.FileID)
	var i WorkspaceBackground
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.FileID,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const isWorkspaceBackground = `-- name: IsWorkspaceBackground :one
SELECT EXISTS (SELECT 1 FROM workspace_backgrounds WHERE file_id = $1)::boolean
`

// The file is the picture of a camera background (files.CanRead: members of its workspace).
func (q *Queries) IsWorkspaceBackground(ctx context.Context, fileID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isWorkspaceBackground, fileID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listWorkspaceBackgrounds = `-- name: ListWorkspaceBackgrounds :many
SELECT id, workspace_id, name, file_id, position, created_at FROM workspace_backgrounds WHERE workspace_id = $1 ORDER BY position, id
`

func (q *Queries) ListWorkspaceBackgrounds(ctx context.Context, workspaceID uuid.UUID) ([]WorkspaceBackground, error) {
	rows, err := q.db.Query(ctx, listWorkspaceBackgrounds, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceBackground{}
	for rows.Next() {
		var i WorkspaceBackground
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.FileID,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockWorkspaceBackgrounds = `-- name: LockWorkspaceBackgrounds :exec

SELECT pg_advisory_xact_lock(hashtext('calaba.backgrounds.' || $1::uuid::text))
`

// Camera backgrounds of a workspace (ADR-0035).
// Serializes background creation of one workspace between the count and the insert.
func (q *Queries) LockWorkspaceBackgrounds(ctx context.Context, workspaceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockWorkspaceBackgrounds, workspaceID)
	return err
}

const renameWorkspaceBackground = `-- name: RenameWorkspaceBackground :one
UPDATE workspace_backgrounds SET name = $3
WHERE id = $1 AND workspace_id = $2
RETURNING id, workspace_id, name, file_id, position, created_at
`

type RenameWorkspaceBackgroundParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
}

func (q *Queries) RenameWorkspaceBackground(ctx context.Context, arg RenameWorkspaceBackgroundParams) (WorkspaceBackground, error) {
	row := q.db.QueryRow(ctx, renameWorkspaceBackground, arg.ID, arg.WorkspaceID, arg.Name)
	var i WorkspaceBackground
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.FileID,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}
