// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: board_webhooks.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const boardWebhookFailing = `-- name: BoardWebhookFailing :one
UPDATE board_webhooks SET failing_since = coalesce(failing_since, now()), last_error = $2
WHERE board_id = $1
RETURNING board_id, url, secret_enc, disabled_at, failing_since, last_ok_at, last_error, next_seq, created_by, created_at, updated_at
`

type BoardWebhookFailingParams struct {
	BoardID   uuid.UUID
	LastError string
}

func (q *Queries) BoardWebhookFailing(ctx context.Context, arg BoardWebhookFailingParams) (BoardWebhook, error) {
	row := q.db.QueryRow(ctx, boardWebhookFailing, arg.BoardID, arg.LastError)
	var i BoardWebhook
	err := row.Scan(
		&i.BoardID,
		&i.Url,
		&i.SecretEnc,
		&i.DisabledAt,
		&i.FailingSince,
		&i.LastOkAt,
		&i.LastError,
		&i.NextSeq,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const boardWebhookOK = `-- name: BoardWebhookOK :exec
UPDATE board_webhooks SET last_ok_at = now(), failing_since = NULL, last_error = ''
WHERE board_id = $1
`

func (q *Queries) BoardWebhookOK(ctx context.Context, boardID uuid.UUID) error {
	_, err := q.db.Exec(ctx, boardWebhookOK, boardID)
	return err
}

const claimBoardWebhookDeliveries = `-- name: ClaimBoardWebhookDeliveries :many
UPDATE board_webhook_deliveries SET next_at = now() + $1::interval
WHERE id IN (
    SELECT d.id FROM board_webhook_deliveries d
    WHERE d.delivered_at IS NULL AND d.failed_at IS NULL AND d.next_at <= now()
    ORDER BY d.next_at, d.id
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
RETURNING id, board_id, seq, event_type, payload, attempts, next_at, created_at, delivered_at, failed_at, error
`

type ClaimBoardWebhookDeliveriesParams struct {
	Lease pgtype.Interval
	Lim   int32
}

// Takes due deliveries: next_at moves one lease ahead (a crashed worker's rows come back).
func (q *Queries) ClaimBoardWebhookDeliveries(ctx context.Context, arg ClaimBoardWebhookDeliveriesParams) ([]BoardWebhookDelivery, error) {
	rows, err := q.db.Query(ctx, claimBoardWebhookDeliveries, arg.Lease, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BoardWebhookDelivery{}
	for rows.Next() {
		var i BoardWebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Seq,
			&i.EventType,
			&i.Payload,
			&i.Attempts,
			&i.NextAt,
			&i.CreatedAt,
			&i.DeliveredAt,
			&i.FailedAt,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countPendingBoardWebhookDeliveries = `-- name: CountPendingBoardWebhookDeliveries :one
SELECT count(*)::integer FROM board_webhook_deliveries
WHERE board_id = $1 AND delivered_at IS NULL AND failed_at IS NULL
`

func (q *Queries) CountPendingBoardWebhookDeliveries(ctx context.Context, boardID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countPendingBoardWebhookDeliveries, boardID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteBoardWebhook = `-- name: DeleteBoardWebhook :execrows
DELETE FROM board_webhooks WHERE board_id = $1
`

func (q *Queries) DeleteBoardWebhook(ctx context.Context, boardID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBoardWebhook, boardID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOldBoardWebhookDeliveries = `-- name: DeleteOldBoardWebhookDeliveries :execrows
DELETE FROM board_webhook_deliveries
WHERE created_at < $1 AND (delivered_at IS NOT NULL OR failed_at IS NOT NULL)
`

func (q *Queries) DeleteOldBoardWebhookDeliveries(ctx context.Context, createdAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldBoardWebhookDeliveries, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const disableBoardWebhook = `-- name: DisableBoardWebhook :one
UPDATE board_webhooks SET disabled_at = now() WHERE board_id = $1 AND disabled_at IS NULL
RETURNING board_id, url, secret_enc, disabled_at, failing_since, last_ok_at, last_error, next_seq, created_by, created_at, updated_at
`

func (q *Queries) DisableBoardWebhook(ctx context.Context, boardID uuid.UUID) (BoardWebhook, error) {
	row := q.db.QueryRow(ctx, disableBoardWebhook, boardID)
	var i BoardWebhook
	err := row.Scan(
		&i.BoardID,
		&i.Url,
		&i.SecretEnc,
		&i.DisabledAt,
		&i.FailingSince,
		&i.LastOkAt,
		&i.LastError,
		&i.NextSeq,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const enqueueBoardWebhookDelivery = `-- name: EnqueueBoardWebhookDelivery :exec
INSERT INTO board_webhook_deliveries (id, board_id, seq, event_type, payload)
VALUES ($1, $2, $3, $4, $5)
`

type EnqueueBoardWebhookDeliveryParams struct {
	ID        uuid.UUID
	BoardID   uuid.UUID
	Seq       int64
	EventType string
	Payload   []byte
}

// id is generated by the application (uuid v7): the body carries its delivery id.
func (q *Queries) EnqueueBoardWebhookDelivery(ctx context.Context, arg EnqueueBoardWebhookDeliveryParams) error {
	_, err := q.db.Exec(ctx, enqueueBoardWebhookDelivery,
		arg.ID,
		arg.BoardID,
		arg.Seq,
		arg.EventType,
		arg.Payload,
	)
	return err
}

const failPendingBoardWebhookDeliveries = `-- name: FailPendingBoardWebhookDeliveries :exec
UPDATE board_webhook_deliveries SET failed_at = now(), payload = NULL, error = $2
WHERE board_id = $1 AND delivered_at IS NULL AND failed_at IS NULL
`

type FailPendingBoardWebhookDeliveriesParams struct {
	BoardID uuid.UUID
	Error   string
}

func (q *Queries) FailPendingBoardWebhookDeliveries(ctx context.Context, arg FailPendingBoardWebhookDeliveriesParams) error {
	_, err := q.db.Exec(ctx, failPendingBoardWebhookDeliveries, arg.BoardID, arg.Error)
	return err
}

const getBoardWebhook = `-- name: GetBoardWebhook :one

SELECT board_id, url, secret_enc, disabled_at, failing_since, last_ok_at, last_error, next_seq, created_by, created_at, updated_at FROM board_webhooks WHERE board_id = $1
`

// ADR-0058 §4: the board webhook and its outbox (the bot_webhook_deliveries pattern).
func (q *Queries) GetBoardWebhook(ctx context.Context, boardID uuid.UUID) (BoardWebhook, error) {
	row := q.db.QueryRow(ctx, getBoardWebhook, boardID)
	var i BoardWebhook
	err := row.Scan(
		&i.BoardID,
		&i.Url,
		&i.SecretEnc,
		&i.DisabledAt,
		&i.FailingSince,
		&i.LastOkAt,
		&i.LastError,
		&i.NextSeq,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markBoardWebhookDelivered = `-- name: MarkBoardWebhookDelivered :exec
UPDATE board_webhook_deliveries SET delivered_at = now(), payload = NULL, attempts = attempts + 1, error = ''
WHERE id = $1
`

func (q *Queries) MarkBoardWebhookDelivered(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markBoardWebhookDelivered, id)
	return err
}

const markBoardWebhookFailed = `-- name: MarkBoardWebhookFailed :exec
UPDATE board_webhook_deliveries SET attempts = attempts + 1, failed_at = now(), payload = NULL, error = $2
WHERE id = $1
`

type MarkBoardWebhookFailedParams struct {
	ID    uuid.UUID
	Error string
}

func (q *Queries) MarkBoardWebhookFailed(ctx context.Context, arg MarkBoardWebhookFailedParams) error {
	_, err := q.db.Exec(ctx, markBoardWebhookFailed, arg.ID, arg.Error)
	return err
}

const markBoardWebhookRetry = `-- name: MarkBoardWebhookRetry :exec
UPDATE board_webhook_deliveries SET attempts = attempts + 1, next_at = $2, error = $3 WHERE id = $1
`

type MarkBoardWebhookRetryParams struct {
	ID     uuid.UUID
	NextAt time.Time
	Error  string
}

func (q *Queries) MarkBoardWebhookRetry(ctx context.Context, arg MarkBoardWebhookRetryParams) error {
	_, err := q.db.Exec(ctx, markBoardWebhookRetry, arg.ID, arg.NextAt, arg.Error)
	return err
}

const nextBoardWebhookSeq = `-- name: NextBoardWebhookSeq :one
UPDATE board_webhooks SET next_seq = next_seq + 1
WHERE board_id = $1 AND disabled_at IS NULL
RETURNING (next_seq - 1)::bigint AS seq
`

// Inside the change's transaction: takes the board's next sequence number of an enabled
// webhook (no row = no webhook or disabled: nothing to queue). The row lock serializes the
// board's writers until commit.
func (q *Queries) NextBoardWebhookSeq(ctx context.Context, boardID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, nextBoardWebhookSeq, boardID)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const upsertBoardWebhook = `-- name: UpsertBoardWebhook :one
INSERT INTO board_webhooks (board_id, url, secret_enc, created_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (board_id) DO UPDATE SET
    url = excluded.url, secret_enc = excluded.secret_enc, disabled_at = NULL,
    failing_since = NULL, last_error = '', updated_at = now()
RETURNING board_id, url, secret_enc, disabled_at, failing_since, last_ok_at, last_error, next_seq, created_by, created_at, updated_at
`

type UpsertBoardWebhookParams struct {
	BoardID   uuid.UUID
	Url       string
	SecretEnc []byte
	CreatedBy *uuid.UUID
}

// PUT: creates or replaces the webhook and (re)enables it; next_seq keeps counting.
func (q *Queries) UpsertBoardWebhook(ctx context.Context, arg UpsertBoardWebhookParams) (BoardWebhook, error) {
	row := q.db.QueryRow(ctx, upsertBoardWebhook,
		arg.BoardID,
		arg.Url,
		arg.SecretEnc,
		arg.CreatedBy,
	)
	var i BoardWebhook
	err := row.Scan(
		&i.BoardID,
		&i.Url,
		&i.SecretEnc,
		&i.DisabledAt,
		&i.FailingSince,
		&i.LastOkAt,
		&i.LastError,
		&i.NextSeq,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
