// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checklists.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countChecklistItems = `-- name: CountChecklistItems :one
SELECT count(*)::integer FROM task_checklist_items WHERE checklist_id = $1
`

func (q *Queries) CountChecklistItems(ctx context.Context, checklistID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countChecklistItems, checklistID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countTaskChecklists = `-- name: CountTaskChecklists :one
SELECT count(*)::integer FROM task_checklists WHERE task_id = $1
`

func (q *Queries) CountTaskChecklists(ctx context.Context, taskID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countTaskChecklists, taskID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createChecklistItem = `-- name: CreateChecklistItem :one
INSERT INTO task_checklist_items (checklist_id, task_id, text, position, created_by)
VALUES ($1, $2, $3,
        coalesce($4::double precision,
                 (SELECT coalesce(max(position) + 1, 0) FROM task_checklist_items WHERE checklist_id = $1)),
        $5)
RETURNING id, checklist_id, task_id, text, done, done_by, done_at, position, created_by, created_at
`

type CreateChecklistItemParams struct {
	ChecklistID uuid.UUID
	TaskID      uuid.UUID
	Text        string
	Position    *float64
	CreatedBy   *uuid.UUID
}

// position NULL = after the last item of the checklist.
func (q *Queries) CreateChecklistItem(ctx context.Context, arg CreateChecklistItemParams) (TaskChecklistItem, error) {
	row := q.db.QueryRow(ctx, createChecklistItem,
		arg.ChecklistID,
		arg.TaskID,
		arg.Text,
		arg.Position,
		arg.CreatedBy,
	)
	var i TaskChecklistItem
	err := row.Scan(
		&i.ID,
		&i.ChecklistID,
		&i.TaskID,
		&i.Text,
		&i.Done,
		&i.DoneBy,
		&i.DoneAt,
		&i.Position,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createTaskChecklist = `-- name: CreateTaskChecklist :one
INSERT INTO task_checklists (task_id, title, position, created_by)
VALUES ($1, $2,
        coalesce($3::integer,
                 (SELECT coalesce(max(position) + 1, 0) FROM task_checklists WHERE task_id = $1)),
        $4)
RETURNING id, task_id, title, position, created_by, created_at
`

type CreateTaskChecklistParams struct {
	TaskID    uuid.UUID
	Title     string
	Position  *int32
	CreatedBy *uuid.UUID
}

// position NULL = last. Lock the task row first (GetTaskRowForUpdate): count limit, positions.
func (q *Queries) CreateTaskChecklist(ctx context.Context, arg CreateTaskChecklistParams) (TaskChecklist, error) {
	row := q.db.QueryRow(ctx, createTaskChecklist,
		arg.TaskID,
		arg.Title,
		arg.Position,
		arg.CreatedBy,
	)
	var i TaskChecklist
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Title,
		&i.Position,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteChecklistItem = `-- name: DeleteChecklistItem :execrows
DELETE FROM task_checklist_items WHERE id = $1
`

func (q *Queries) DeleteChecklistItem(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChecklistItem, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTaskChecklist = `-- name: DeleteTaskChecklist :execrows
DELETE FROM task_checklists WHERE id = $1
`

func (q *Queries) DeleteTaskChecklist(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTaskChecklist, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getChecklistItem = `-- name: GetChecklistItem :one
SELECT id, checklist_id, task_id, text, done, done_by, done_at, position, created_by, created_at FROM task_checklist_items WHERE id = $1
`

func (q *Queries) GetChecklistItem(ctx context.Context, id uuid.UUID) (TaskChecklistItem, error) {
	row := q.db.QueryRow(ctx, getChecklistItem, id)
	var i TaskChecklistItem
	err := row.Scan(
		&i.ID,
		&i.ChecklistID,
		&i.TaskID,
		&i.Text,
		&i.Done,
		&i.DoneBy,
		&i.DoneAt,
		&i.Position,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getChecklistItemForUpdate = `-- name: GetChecklistItemForUpdate :one
SELECT id, checklist_id, task_id, text, done, done_by, done_at, position, created_by, created_at FROM task_checklist_items WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetChecklistItemForUpdate(ctx context.Context, id uuid.UUID) (TaskChecklistItem, error) {
	row := q.db.QueryRow(ctx, getChecklistItemForUpdate, id)
	var i TaskChecklistItem
	err := row.Scan(
		&i.ID,
		&i.ChecklistID,
		&i.TaskID,
		&i.Text,
		&i.Done,
		&i.DoneBy,
		&i.DoneAt,
		&i.Position,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getChecklistItemWorkspace = `-- name: GetChecklistItemWorkspace :one
SELECT b.workspace_id FROM task_checklist_items i
JOIN tasks t ON t.id = i.task_id JOIN boards b ON b.id = t.board_id
WHERE i.id = $1
`

func (q *Queries) GetChecklistItemWorkspace(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getChecklistItemWorkspace, id)
	var workspace_id uuid.UUID
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

const getChecklistWorkspace = `-- name: GetChecklistWorkspace :one
SELECT b.workspace_id FROM task_checklists c
JOIN tasks t ON t.id = c.task_id JOIN boards b ON b.id = t.board_id
WHERE c.id = $1
`

// The workspace of a checklist (identity route resolution).
func (q *Queries) GetChecklistWorkspace(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getChecklistWorkspace, id)
	var workspace_id uuid.UUID
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

const getTaskChecklist = `-- name: GetTaskChecklist :one
SELECT id, task_id, title, position, created_by, created_at FROM task_checklists WHERE id = $1
`

func (q *Queries) GetTaskChecklist(ctx context.Context, id uuid.UUID) (TaskChecklist, error) {
	row := q.db.QueryRow(ctx, getTaskChecklist, id)
	var i TaskChecklist
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Title,
		&i.Position,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getTaskChecklistForUpdate = `-- name: GetTaskChecklistForUpdate :one
SELECT id, task_id, title, position, created_by, created_at FROM task_checklists WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetTaskChecklistForUpdate(ctx context.Context, id uuid.UUID) (TaskChecklist, error) {
	row := q.db.QueryRow(ctx, getTaskChecklistForUpdate, id)
	var i TaskChecklist
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Title,
		&i.Position,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listChecklistItems = `-- name: ListChecklistItems :many
SELECT id, checklist_id, task_id, text, done, done_by, done_at, position, created_by, created_at FROM task_checklist_items WHERE checklist_id = $1 ORDER BY position, id
`

func (q *Queries) ListChecklistItems(ctx context.Context, checklistID uuid.UUID) ([]TaskChecklistItem, error) {
	rows, err := q.db.Query(ctx, listChecklistItems, checklistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskChecklistItem{}
	for rows.Next() {
		var i TaskChecklistItem
		if err := rows.Scan(
			&i.ID,
			&i.ChecklistID,
			&i.TaskID,
			&i.Text,
			&i.Done,
			&i.DoneBy,
			&i.DoneAt,
			&i.Position,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskChecklistItems = `-- name: ListTaskChecklistItems :many
SELECT id, checklist_id, task_id, text, done, done_by, done_at, position, created_by, created_at FROM task_checklist_items WHERE task_id = $1 ORDER BY checklist_id, position, id
`

// Every item of a task's checklists (GET /tasks/{id}), grouped by the caller.
func (q *Queries) ListTaskChecklistItems(ctx context.Context, taskID uuid.UUID) ([]TaskChecklistItem, error) {
	rows, err := q.db.Query(ctx, listTaskChecklistItems, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskChecklistItem{}
	for rows.Next() {
		var i TaskChecklistItem
		if err := rows.Scan(
			&i.ID,
			&i.ChecklistID,
			&i.TaskID,
			&i.Text,
			&i.Done,
			&i.DoneBy,
			&i.DoneAt,
			&i.Position,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskChecklists = `-- name: ListTaskChecklists :many

SELECT id, task_id, title, position, created_by, created_at FROM task_checklists WHERE task_id = $1 ORDER BY position, id
`

// ADR-0058 §2: named checklists of a task and their items.
func (q *Queries) ListTaskChecklists(ctx context.Context, taskID uuid.UUID) ([]TaskChecklist, error) {
	rows, err := q.db.Query(ctx, listTaskChecklists, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskChecklist{}
	for rows.Next() {
		var i TaskChecklist
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Title,
			&i.Position,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTaskChecklistPosition = `-- name: SetTaskChecklistPosition :exec
UPDATE task_checklists SET position = $2 WHERE id = $1
`

type SetTaskChecklistPositionParams struct {
	ID       uuid.UUID
	Position int32
}

func (q *Queries) SetTaskChecklistPosition(ctx context.Context, arg SetTaskChecklistPositionParams) error {
	_, err := q.db.Exec(ctx, setTaskChecklistPosition, arg.ID, arg.Position)
	return err
}

const taskChecklistCounts = `-- name: TaskChecklistCounts :one
SELECT count(*)::integer AS total, (count(*) FILTER (WHERE done))::integer AS done
FROM task_checklist_items WHERE task_id = $1
`

type TaskChecklistCountsRow struct {
	Total int32
	Done  int32
}

// The task's counters (Task.checklist_total / checklist_done).
func (q *Queries) TaskChecklistCounts(ctx context.Context, taskID uuid.UUID) (TaskChecklistCountsRow, error) {
	row := q.db.QueryRow(ctx, taskChecklistCounts, taskID)
	var i TaskChecklistCountsRow
	err := row.Scan(&i.Total, &i.Done)
	return i, err
}

const updateChecklistItem = `-- name: UpdateChecklistItem :one
UPDATE task_checklist_items SET
    text         = coalesce($1, text),
    position     = coalesce($2, position),
    checklist_id = coalesce($3, checklist_id),
    done_by      = CASE WHEN $4::boolean IS NULL OR $4::boolean = done THEN done_by
                        WHEN $4::boolean THEN $5::uuid ELSE NULL END,
    done_at      = CASE WHEN $4::boolean IS NULL OR $4::boolean = done THEN done_at
                        WHEN $4::boolean THEN now() ELSE NULL END,
    done         = coalesce($4::boolean, done)
WHERE id = $6
RETURNING id, checklist_id, task_id, text, done, done_by, done_at, position, created_by, created_at
`

type UpdateChecklistItemParams struct {
	Text        *string
	Position    *float64
	ChecklistID *uuid.UUID
	Done        *bool
	ActorID     *uuid.UUID
	ID          uuid.UUID
}

// done set: done_by / done_at follow (true = the actor and now, false = cleared); a repeat of
// the current value keeps them. checklist_id moves the item (same task: checked by the caller).
func (q *Queries) UpdateChecklistItem(ctx context.Context, arg UpdateChecklistItemParams) (TaskChecklistItem, error) {
	row := q.db.QueryRow(ctx, updateChecklistItem,
		arg.Text,
		arg.Position,
		arg.ChecklistID,
		arg.Done,
		arg.ActorID,
		arg.ID,
	)
	var i TaskChecklistItem
	err := row.Scan(
		&i.ID,
		&i.ChecklistID,
		&i.TaskID,
		&i.Text,
		&i.Done,
		&i.DoneBy,
		&i.DoneAt,
		&i.Position,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const updateTaskChecklist = `-- name: UpdateTaskChecklist :one
UPDATE task_checklists SET title = coalesce($1, title)
WHERE id = $2
RETURNING id, task_id, title, position, created_by, created_at
`

type UpdateTaskChecklistParams struct {
	Title *string
	ID    uuid.UUID
}

func (q *Queries) UpdateTaskChecklist(ctx context.Context, arg UpdateTaskChecklistParams) (TaskChecklist, error) {
	row := q.db.QueryRow(ctx, updateTaskChecklist, arg.Title, arg.ID)
	var i TaskChecklist
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Title,
		&i.Position,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
