// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: directory.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createDirectoryObject = `-- name: CreateDirectoryObject :one
INSERT INTO directory_objects (workspace_id, directory_id, object_guid, user_id, distinguished_name, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, workspace_id, directory_id, object_guid, user_id, distinguished_name, status, version, last_seen_run_id, missing_full_scans, updated_at
`

type CreateDirectoryObjectParams struct {
	WorkspaceID       uuid.UUID
	DirectoryID       uuid.UUID
	ObjectGuid        uuid.UUID
	UserID            *uuid.UUID
	DistinguishedName string
	Status            string
}

func (q *Queries) CreateDirectoryObject(ctx context.Context, arg CreateDirectoryObjectParams) (DirectoryObject, error) {
	row := q.db.QueryRow(ctx, createDirectoryObject,
		arg.WorkspaceID,
		arg.DirectoryID,
		arg.ObjectGuid,
		arg.UserID,
		arg.DistinguishedName,
		arg.Status,
	)
	var i DirectoryObject
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DirectoryID,
		&i.ObjectGuid,
		&i.UserID,
		&i.DistinguishedName,
		&i.Status,
		&i.Version,
		&i.LastSeenRunID,
		&i.MissingFullScans,
		&i.UpdatedAt,
	)
	return i, err
}

const createDirectorySyncObject = `-- name: CreateDirectorySyncObject :one
INSERT INTO directory_sync_objects (workspace_id, directory_id, run_id, object_guid, distinguished_name, eligible, disabled)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING workspace_id, directory_id, run_id, object_guid, distinguished_name, eligible, disabled
`

type CreateDirectorySyncObjectParams struct {
	WorkspaceID       uuid.UUID
	DirectoryID       uuid.UUID
	RunID             uuid.UUID
	ObjectGuid        uuid.UUID
	DistinguishedName string
	Eligible          bool
	Disabled          bool
}

func (q *Queries) CreateDirectorySyncObject(ctx context.Context, arg CreateDirectorySyncObjectParams) (DirectorySyncObject, error) {
	row := q.db.QueryRow(ctx, createDirectorySyncObject,
		arg.WorkspaceID,
		arg.DirectoryID,
		arg.RunID,
		arg.ObjectGuid,
		arg.DistinguishedName,
		arg.Eligible,
		arg.Disabled,
	)
	var i DirectorySyncObject
	err := row.Scan(
		&i.WorkspaceID,
		&i.DirectoryID,
		&i.RunID,
		&i.ObjectGuid,
		&i.DistinguishedName,
		&i.Eligible,
		&i.Disabled,
	)
	return i, err
}

const createDirectorySyncRun = `-- name: CreateDirectorySyncRun :one
INSERT INTO directory_sync_runs (workspace_id, directory_id, full_scan, config_version, lease_until, status, complete, objects_seen, started_at, generation)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, workspace_id, directory_id, full_scan, config_version, generation, lease_until, status, complete, objects_seen, started_at, finished_at
`

type CreateDirectorySyncRunParams struct {
	WorkspaceID   uuid.UUID
	DirectoryID   uuid.UUID
	FullScan      bool
	ConfigVersion int64
	LeaseUntil    time.Time
	Status        string
	Complete      bool
	ObjectsSeen   int32
	StartedAt     time.Time
	Generation    int64
}

func (q *Queries) CreateDirectorySyncRun(ctx context.Context, arg CreateDirectorySyncRunParams) (DirectorySyncRun, error) {
	row := q.db.QueryRow(ctx, createDirectorySyncRun,
		arg.WorkspaceID,
		arg.DirectoryID,
		arg.FullScan,
		arg.ConfigVersion,
		arg.LeaseUntil,
		arg.Status,
		arg.Complete,
		arg.ObjectsSeen,
		arg.StartedAt,
		arg.Generation,
	)
	var i DirectorySyncRun
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DirectoryID,
		&i.FullScan,
		&i.ConfigVersion,
		&i.Generation,
		&i.LeaseUntil,
		&i.Status,
		&i.Complete,
		&i.ObjectsSeen,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const createIdentityDirectory = `-- name: CreateIdentityDirectory :one

INSERT INTO workspace_directories (id, workspace_id, name, host, url, allowed_group_dns, port, base_dn, bind_dn, bind_secret_box, ca_pem, sync_interval_seconds, max_staleness_seconds)
VALUES (COALESCE($1::uuid, uuidv7()), $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, workspace_id, name, host, url, allowed_group_dns, generation, port, base_dn, bind_dn, bind_secret_box, ca_pem, sync_interval_seconds, max_staleness_seconds, version, last_success_at, cursor_box, last_error, disabled_at, created_at
`

type CreateIdentityDirectoryParams struct {
	ID                  *uuid.UUID
	WorkspaceID         uuid.UUID
	Name                string
	Host                string
	Url                 string
	AllowedGroupDns     []string
	Port                int32
	BaseDn              string
	BindDn              string
	BindSecretBox       []byte
	CaPem               string
	SyncIntervalSeconds int32
	MaxStalenessSeconds int32
}

// Identity v1 foundation, ADR-0054. Consumer mutations run with audit/outbox in one transaction.
func (q *Queries) CreateIdentityDirectory(ctx context.Context, arg CreateIdentityDirectoryParams) (WorkspaceDirectory, error) {
	row := q.db.QueryRow(ctx, createIdentityDirectory,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Host,
		arg.Url,
		arg.AllowedGroupDns,
		arg.Port,
		arg.BaseDn,
		arg.BindDn,
		arg.BindSecretBox,
		arg.CaPem,
		arg.SyncIntervalSeconds,
		arg.MaxStalenessSeconds,
	)
	var i WorkspaceDirectory
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Host,
		&i.Url,
		&i.AllowedGroupDns,
		&i.Generation,
		&i.Port,
		&i.BaseDn,
		&i.BindDn,
		&i.BindSecretBox,
		&i.CaPem,
		&i.SyncIntervalSeconds,
		&i.MaxStalenessSeconds,
		&i.Version,
		&i.LastSuccessAt,
		&i.CursorBox,
		&i.LastError,
		&i.DisabledAt,
		&i.CreatedAt,
	)
	return i, err
}

const findDirectoryObjectGUID = `-- name: FindDirectoryObjectGUID :one
SELECT id, workspace_id, directory_id, object_guid, user_id, distinguished_name, status, version, last_seen_run_id, missing_full_scans, updated_at FROM directory_objects WHERE workspace_id=$1 AND directory_id=$2 AND object_guid=$3
`

type FindDirectoryObjectGUIDParams struct {
	WorkspaceID uuid.UUID
	DirectoryID uuid.UUID
	ObjectGuid  uuid.UUID
}

func (q *Queries) FindDirectoryObjectGUID(ctx context.Context, arg FindDirectoryObjectGUIDParams) (DirectoryObject, error) {
	row := q.db.QueryRow(ctx, findDirectoryObjectGUID, arg.WorkspaceID, arg.DirectoryID, arg.ObjectGuid)
	var i DirectoryObject
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DirectoryID,
		&i.ObjectGuid,
		&i.UserID,
		&i.DistinguishedName,
		&i.Status,
		&i.Version,
		&i.LastSeenRunID,
		&i.MissingFullScans,
		&i.UpdatedAt,
	)
	return i, err
}

const finishDirectorySyncRun = `-- name: FinishDirectorySyncRun :one
UPDATE directory_sync_runs SET status=$2,complete=$3,objects_seen=$4,finished_at=clock_timestamp()
WHERE id=$1 AND status='running' RETURNING id, workspace_id, directory_id, full_scan, config_version, generation, lease_until, status, complete, objects_seen, started_at, finished_at
`

type FinishDirectorySyncRunParams struct {
	ID          uuid.UUID
	Status      string
	Complete    bool
	ObjectsSeen int32
}

func (q *Queries) FinishDirectorySyncRun(ctx context.Context, arg FinishDirectorySyncRunParams) (DirectorySyncRun, error) {
	row := q.db.QueryRow(ctx, finishDirectorySyncRun,
		arg.ID,
		arg.Status,
		arg.Complete,
		arg.ObjectsSeen,
	)
	var i DirectorySyncRun
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DirectoryID,
		&i.FullScan,
		&i.ConfigVersion,
		&i.Generation,
		&i.LeaseUntil,
		&i.Status,
		&i.Complete,
		&i.ObjectsSeen,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getDirectoryObject = `-- name: GetDirectoryObject :one
SELECT id, workspace_id, directory_id, object_guid, user_id, distinguished_name, status, version, last_seen_run_id, missing_full_scans, updated_at FROM directory_objects WHERE workspace_id = $1 AND id = $2
`

type GetDirectoryObjectParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) GetDirectoryObject(ctx context.Context, arg GetDirectoryObjectParams) (DirectoryObject, error) {
	row := q.db.QueryRow(ctx, getDirectoryObject, arg.WorkspaceID, arg.ID)
	var i DirectoryObject
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DirectoryID,
		&i.ObjectGuid,
		&i.UserID,
		&i.DistinguishedName,
		&i.Status,
		&i.Version,
		&i.LastSeenRunID,
		&i.MissingFullScans,
		&i.UpdatedAt,
	)
	return i, err
}

const getDirectorySyncObject = `-- name: GetDirectorySyncObject :one
SELECT workspace_id, directory_id, run_id, object_guid, distinguished_name, eligible, disabled FROM directory_sync_objects WHERE run_id = $1 AND object_guid = $2
`

type GetDirectorySyncObjectParams struct {
	RunID      uuid.UUID
	ObjectGuid uuid.UUID
}

func (q *Queries) GetDirectorySyncObject(ctx context.Context, arg GetDirectorySyncObjectParams) (DirectorySyncObject, error) {
	row := q.db.QueryRow(ctx, getDirectorySyncObject, arg.RunID, arg.ObjectGuid)
	var i DirectorySyncObject
	err := row.Scan(
		&i.WorkspaceID,
		&i.DirectoryID,
		&i.RunID,
		&i.ObjectGuid,
		&i.DistinguishedName,
		&i.Eligible,
		&i.Disabled,
	)
	return i, err
}

const getDirectorySyncRun = `-- name: GetDirectorySyncRun :one
SELECT id, workspace_id, directory_id, full_scan, config_version, generation, lease_until, status, complete, objects_seen, started_at, finished_at FROM directory_sync_runs WHERE workspace_id = $1 AND id = $2
`

type GetDirectorySyncRunParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) GetDirectorySyncRun(ctx context.Context, arg GetDirectorySyncRunParams) (DirectorySyncRun, error) {
	row := q.db.QueryRow(ctx, getDirectorySyncRun, arg.WorkspaceID, arg.ID)
	var i DirectorySyncRun
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DirectoryID,
		&i.FullScan,
		&i.ConfigVersion,
		&i.Generation,
		&i.LeaseUntil,
		&i.Status,
		&i.Complete,
		&i.ObjectsSeen,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getIdentityDirectory = `-- name: GetIdentityDirectory :one
SELECT id, workspace_id, name, host, url, allowed_group_dns, generation, port, base_dn, bind_dn, bind_secret_box, ca_pem, sync_interval_seconds, max_staleness_seconds, version, last_success_at, cursor_box, last_error, disabled_at, created_at FROM workspace_directories WHERE workspace_id = $1 AND id = $2
`

type GetIdentityDirectoryParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) GetIdentityDirectory(ctx context.Context, arg GetIdentityDirectoryParams) (WorkspaceDirectory, error) {
	row := q.db.QueryRow(ctx, getIdentityDirectory, arg.WorkspaceID, arg.ID)
	var i WorkspaceDirectory
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Host,
		&i.Url,
		&i.AllowedGroupDns,
		&i.Generation,
		&i.Port,
		&i.BaseDn,
		&i.BindDn,
		&i.BindSecretBox,
		&i.CaPem,
		&i.SyncIntervalSeconds,
		&i.MaxStalenessSeconds,
		&i.Version,
		&i.LastSuccessAt,
		&i.CursorBox,
		&i.LastError,
		&i.DisabledAt,
		&i.CreatedAt,
	)
	return i, err
}

const getIdentityDirectoryForUpdate = `-- name: GetIdentityDirectoryForUpdate :one
SELECT id, workspace_id, name, host, url, allowed_group_dns, generation, port, base_dn, bind_dn, bind_secret_box, ca_pem, sync_interval_seconds, max_staleness_seconds, version, last_success_at, cursor_box, last_error, disabled_at, created_at FROM workspace_directories WHERE workspace_id=$1 FOR UPDATE
`

func (q *Queries) GetIdentityDirectoryForUpdate(ctx context.Context, workspaceID uuid.UUID) (WorkspaceDirectory, error) {
	row := q.db.QueryRow(ctx, getIdentityDirectoryForUpdate, workspaceID)
	var i WorkspaceDirectory
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Host,
		&i.Url,
		&i.AllowedGroupDns,
		&i.Generation,
		&i.Port,
		&i.BaseDn,
		&i.BindDn,
		&i.BindSecretBox,
		&i.CaPem,
		&i.SyncIntervalSeconds,
		&i.MaxStalenessSeconds,
		&i.Version,
		&i.LastSuccessAt,
		&i.CursorBox,
		&i.LastError,
		&i.DisabledAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLastDirectorySuccessVersion = `-- name: GetLastDirectorySuccessVersion :one
SELECT config_version FROM directory_sync_runs
WHERE workspace_id=$1 AND directory_id=$2 AND status='succeeded' AND complete
ORDER BY started_at DESC LIMIT 1
`

type GetLastDirectorySuccessVersionParams struct {
	WorkspaceID uuid.UUID
	DirectoryID uuid.UUID
}

// Config version of the directory's latest successful full scan (the shrink guard compares
// it with the current version: the first scan after a configuration save is not guarded).
func (q *Queries) GetLastDirectorySuccessVersion(ctx context.Context, arg GetLastDirectorySuccessVersionParams) (int64, error) {
	row := q.db.QueryRow(ctx, getLastDirectorySuccessVersion, arg.WorkspaceID, arg.DirectoryID)
	var config_version int64
	err := row.Scan(&config_version)
	return config_version, err
}

const getWorkspaceIdentityDirectory = `-- name: GetWorkspaceIdentityDirectory :one
SELECT id, workspace_id, name, host, url, allowed_group_dns, generation, port, base_dn, bind_dn, bind_secret_box, ca_pem, sync_interval_seconds, max_staleness_seconds, version, last_success_at, cursor_box, last_error, disabled_at, created_at FROM workspace_directories WHERE workspace_id=$1
`

func (q *Queries) GetWorkspaceIdentityDirectory(ctx context.Context, workspaceID uuid.UUID) (WorkspaceDirectory, error) {
	row := q.db.QueryRow(ctx, getWorkspaceIdentityDirectory, workspaceID)
	var i WorkspaceDirectory
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Host,
		&i.Url,
		&i.AllowedGroupDns,
		&i.Generation,
		&i.Port,
		&i.BaseDn,
		&i.BindDn,
		&i.BindSecretBox,
		&i.CaPem,
		&i.SyncIntervalSeconds,
		&i.MaxStalenessSeconds,
		&i.Version,
		&i.LastSuccessAt,
		&i.CursorBox,
		&i.LastError,
		&i.DisabledAt,
		&i.CreatedAt,
	)
	return i, err
}

const listDirectoryObjects = `-- name: ListDirectoryObjects :many
SELECT id, workspace_id, directory_id, object_guid, user_id, distinguished_name, status, version, last_seen_run_id, missing_full_scans, updated_at FROM directory_objects WHERE workspace_id=$1 AND ($2::uuid IS NULL OR id>$2) ORDER BY id LIMIT $3
`

type ListDirectoryObjectsParams struct {
	WorkspaceID uuid.UUID
	AfterID     *uuid.UUID
	LimitCount  int32
}

func (q *Queries) ListDirectoryObjects(ctx context.Context, arg ListDirectoryObjectsParams) ([]DirectoryObject, error) {
	rows, err := q.db.Query(ctx, listDirectoryObjects, arg.WorkspaceID, arg.AfterID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DirectoryObject{}
	for rows.Next() {
		var i DirectoryObject
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.DirectoryID,
			&i.ObjectGuid,
			&i.UserID,
			&i.DistinguishedName,
			&i.Status,
			&i.Version,
			&i.LastSeenRunID,
			&i.MissingFullScans,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDirectorySyncObjects = `-- name: ListDirectorySyncObjects :many
SELECT workspace_id, directory_id, run_id, object_guid, distinguished_name, eligible, disabled FROM directory_sync_objects WHERE run_id=$1 ORDER BY object_guid
`

func (q *Queries) ListDirectorySyncObjects(ctx context.Context, runID uuid.UUID) ([]DirectorySyncObject, error) {
	rows, err := q.db.Query(ctx, listDirectorySyncObjects, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DirectorySyncObject{}
	for rows.Next() {
		var i DirectorySyncObject
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.DirectoryID,
			&i.RunID,
			&i.ObjectGuid,
			&i.DistinguishedName,
			&i.Eligible,
			&i.Disabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledIdentityDirectories = `-- name: ListEnabledIdentityDirectories :many
SELECT id, workspace_id, name, host, url, allowed_group_dns, generation, port, base_dn, bind_dn, bind_secret_box, ca_pem, sync_interval_seconds, max_staleness_seconds, version, last_success_at, cursor_box, last_error, disabled_at, created_at FROM workspace_directories WHERE disabled_at IS NULL ORDER BY id LIMIT $1
`

func (q *Queries) ListEnabledIdentityDirectories(ctx context.Context, limit int32) ([]WorkspaceDirectory, error) {
	rows, err := q.db.Query(ctx, listEnabledIdentityDirectories, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceDirectory{}
	for rows.Next() {
		var i WorkspaceDirectory
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Host,
			&i.Url,
			&i.AllowedGroupDns,
			&i.Generation,
			&i.Port,
			&i.BaseDn,
			&i.BindDn,
			&i.BindSecretBox,
			&i.CaPem,
			&i.SyncIntervalSeconds,
			&i.MaxStalenessSeconds,
			&i.Version,
			&i.LastSuccessAt,
			&i.CursorBox,
			&i.LastError,
			&i.DisabledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledIdentityDirectoriesAfter = `-- name: ListEnabledIdentityDirectoriesAfter :many
SELECT id, workspace_id, name, host, url, allowed_group_dns, generation, port, base_dn, bind_dn, bind_secret_box, ca_pem, sync_interval_seconds, max_staleness_seconds, version, last_success_at, cursor_box, last_error, disabled_at, created_at FROM workspace_directories WHERE disabled_at IS NULL
AND ($1::uuid IS NULL OR id>$1)
ORDER BY id LIMIT $2
`

type ListEnabledIdentityDirectoriesAfterParams struct {
	AfterID    *uuid.UUID
	LimitCount int32
}

func (q *Queries) ListEnabledIdentityDirectoriesAfter(ctx context.Context, arg ListEnabledIdentityDirectoriesAfterParams) ([]WorkspaceDirectory, error) {
	rows, err := q.db.Query(ctx, listEnabledIdentityDirectoriesAfter, arg.AfterID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceDirectory{}
	for rows.Next() {
		var i WorkspaceDirectory
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Host,
			&i.Url,
			&i.AllowedGroupDns,
			&i.Generation,
			&i.Port,
			&i.BaseDn,
			&i.BindDn,
			&i.BindSecretBox,
			&i.CaPem,
			&i.SyncIntervalSeconds,
			&i.MaxStalenessSeconds,
			&i.Version,
			&i.LastSuccessAt,
			&i.CursorBox,
			&i.LastError,
			&i.DisabledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishDirectorySuccess = `-- name: PublishDirectorySuccess :one
UPDATE workspace_directories d SET last_success_at=clock_timestamp(),generation=$1,cursor_box=$2,last_error=''
WHERE d.workspace_id=$3 AND d.id=$4 AND d.version=$5
AND EXISTS(SELECT FROM directory_sync_runs r WHERE r.id=$6 AND r.directory_id=d.id AND r.config_version=d.version
AND r.status='succeeded' AND r.complete AND r.full_scan AND r.generation=$1 AND r.generation>d.generation
AND r.lease_until>clock_timestamp())
RETURNING d.id, d.workspace_id, d.name, d.host, d.url, d.allowed_group_dns, d.generation, d.port, d.base_dn, d.bind_dn, d.bind_secret_box, d.ca_pem, d.sync_interval_seconds, d.max_staleness_seconds, d.version, d.last_success_at, d.cursor_box, d.last_error, d.disabled_at, d.created_at
`

type PublishDirectorySuccessParams struct {
	Generation    int64
	CursorBox     []byte
	WorkspaceID   uuid.UUID
	DirectoryID   uuid.UUID
	ConfigVersion int64
	RunID         uuid.UUID
}

func (q *Queries) PublishDirectorySuccess(ctx context.Context, arg PublishDirectorySuccessParams) (WorkspaceDirectory, error) {
	row := q.db.QueryRow(ctx, publishDirectorySuccess,
		arg.Generation,
		arg.CursorBox,
		arg.WorkspaceID,
		arg.DirectoryID,
		arg.ConfigVersion,
		arg.RunID,
	)
	var i WorkspaceDirectory
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Host,
		&i.Url,
		&i.AllowedGroupDns,
		&i.Generation,
		&i.Port,
		&i.BaseDn,
		&i.BindDn,
		&i.BindSecretBox,
		&i.CaPem,
		&i.SyncIntervalSeconds,
		&i.MaxStalenessSeconds,
		&i.Version,
		&i.LastSuccessAt,
		&i.CursorBox,
		&i.LastError,
		&i.DisabledAt,
		&i.CreatedAt,
	)
	return i, err
}

const setDirectoryError = `-- name: SetDirectoryError :exec
UPDATE workspace_directories SET last_error=$3 WHERE workspace_id=$1 AND id=$2
`

type SetDirectoryErrorParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
	LastError   string
}

func (q *Queries) SetDirectoryError(ctx context.Context, arg SetDirectoryErrorParams) error {
	_, err := q.db.Exec(ctx, setDirectoryError, arg.WorkspaceID, arg.ID, arg.LastError)
	return err
}

const setDirectoryObjectStatus = `-- name: SetDirectoryObjectStatus :one
UPDATE directory_objects SET status=$3,version=version+1,updated_at=clock_timestamp() WHERE workspace_id=$1 AND id=$2 RETURNING id, workspace_id, directory_id, object_guid, user_id, distinguished_name, status, version, last_seen_run_id, missing_full_scans, updated_at
`

type SetDirectoryObjectStatusParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
	Status      string
}

func (q *Queries) SetDirectoryObjectStatus(ctx context.Context, arg SetDirectoryObjectStatusParams) (DirectoryObject, error) {
	row := q.db.QueryRow(ctx, setDirectoryObjectStatus, arg.WorkspaceID, arg.ID, arg.Status)
	var i DirectoryObject
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DirectoryID,
		&i.ObjectGuid,
		&i.UserID,
		&i.DistinguishedName,
		&i.Status,
		&i.Version,
		&i.LastSeenRunID,
		&i.MissingFullScans,
		&i.UpdatedAt,
	)
	return i, err
}

const setDirectoryObjectUser = `-- name: SetDirectoryObjectUser :one
UPDATE directory_objects SET user_id=$3,version=version+1,updated_at=clock_timestamp() WHERE workspace_id=$1 AND id=$2 RETURNING id, workspace_id, directory_id, object_guid, user_id, distinguished_name, status, version, last_seen_run_id, missing_full_scans, updated_at
`

type SetDirectoryObjectUserParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
	UserID      *uuid.UUID
}

func (q *Queries) SetDirectoryObjectUser(ctx context.Context, arg SetDirectoryObjectUserParams) (DirectoryObject, error) {
	row := q.db.QueryRow(ctx, setDirectoryObjectUser, arg.WorkspaceID, arg.ID, arg.UserID)
	var i DirectoryObject
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DirectoryID,
		&i.ObjectGuid,
		&i.UserID,
		&i.DistinguishedName,
		&i.Status,
		&i.Version,
		&i.LastSeenRunID,
		&i.MissingFullScans,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDirectoryObjectSnapshot = `-- name: UpdateDirectoryObjectSnapshot :one
UPDATE directory_objects SET distinguished_name=$1,status=$2,
last_seen_run_id=$3,missing_full_scans=$4,
version=version+1,updated_at=clock_timestamp()
WHERE workspace_id=$5 AND directory_id=$6 AND id=$7
AND version=$8 RETURNING id, workspace_id, directory_id, object_guid, user_id, distinguished_name, status, version, last_seen_run_id, missing_full_scans, updated_at
`

type UpdateDirectoryObjectSnapshotParams struct {
	DistinguishedName string
	Status            string
	LastSeenRunID     *uuid.UUID
	MissingFullScans  int32
	WorkspaceID       uuid.UUID
	DirectoryID       uuid.UUID
	ID                uuid.UUID
	ExpectedVersion   int64
}

func (q *Queries) UpdateDirectoryObjectSnapshot(ctx context.Context, arg UpdateDirectoryObjectSnapshotParams) (DirectoryObject, error) {
	row := q.db.QueryRow(ctx, updateDirectoryObjectSnapshot,
		arg.DistinguishedName,
		arg.Status,
		arg.LastSeenRunID,
		arg.MissingFullScans,
		arg.WorkspaceID,
		arg.DirectoryID,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i DirectoryObject
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DirectoryID,
		&i.ObjectGuid,
		&i.UserID,
		&i.DistinguishedName,
		&i.Status,
		&i.Version,
		&i.LastSeenRunID,
		&i.MissingFullScans,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIdentityDirectory = `-- name: UpdateIdentityDirectory :one
UPDATE workspace_directories SET name=$1,host=$2,url=$3,
base_dn=$4,bind_dn=$5,bind_secret_box=$6,
allowed_group_dns=$7,ca_pem=$8,version=version+1,
sync_interval_seconds=$9,max_staleness_seconds=$10,
disabled_at=$11,last_success_at=NULL
WHERE workspace_id=$12 AND version=$13 RETURNING id, workspace_id, name, host, url, allowed_group_dns, generation, port, base_dn, bind_dn, bind_secret_box, ca_pem, sync_interval_seconds, max_staleness_seconds, version, last_success_at, cursor_box, last_error, disabled_at, created_at
`

type UpdateIdentityDirectoryParams struct {
	Name                string
	Host                string
	Url                 string
	BaseDn              string
	BindDn              string
	BindSecretBox       []byte
	AllowedGroupDns     []string
	CaPem               string
	SyncIntervalSeconds int32
	MaxStalenessSeconds int32
	DisabledAt          *time.Time
	WorkspaceID         uuid.UUID
	ExpectedVersion     int64
}

func (q *Queries) UpdateIdentityDirectory(ctx context.Context, arg UpdateIdentityDirectoryParams) (WorkspaceDirectory, error) {
	row := q.db.QueryRow(ctx, updateIdentityDirectory,
		arg.Name,
		arg.Host,
		arg.Url,
		arg.BaseDn,
		arg.BindDn,
		arg.BindSecretBox,
		arg.AllowedGroupDns,
		arg.CaPem,
		arg.SyncIntervalSeconds,
		arg.MaxStalenessSeconds,
		arg.DisabledAt,
		arg.WorkspaceID,
		arg.ExpectedVersion,
	)
	var i WorkspaceDirectory
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Host,
		&i.Url,
		&i.AllowedGroupDns,
		&i.Generation,
		&i.Port,
		&i.BaseDn,
		&i.BindDn,
		&i.BindSecretBox,
		&i.CaPem,
		&i.SyncIntervalSeconds,
		&i.MaxStalenessSeconds,
		&i.Version,
		&i.LastSuccessAt,
		&i.CursorBox,
		&i.LastError,
		&i.DisabledAt,
		&i.CreatedAt,
	)
	return i, err
}
