// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteFile = `-- name: DeleteFile :execrows
DELETE FROM files WHERE id = $1
`

func (q *Queries) DeleteFile(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFile, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const fileRooms = `-- name: FileRooms :many
SELECT DISTINCT m.room_id FROM message_attachments ma
JOIN messages m ON m.id = ma.message_id AND m.deleted_at IS NULL
WHERE ma.file_id = $1
`

// Rooms where the file is attached to a live message.
func (q *Queries) FileRooms(ctx context.Context, fileID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, fileRooms, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var room_id uuid.UUID
		if err := rows.Scan(&room_id); err != nil {
			return nil, err
		}
		items = append(items, room_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFile = `-- name: GetFile :one
SELECT id, workspace_id, uploader_id, key, thumbnail_key, name, mime, size, width, height, sha256, created_at FROM files WHERE id = $1
`

func (q *Queries) GetFile(ctx context.Context, id uuid.UUID) (File, error) {
	row := q.db.QueryRow(ctx, getFile, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UploaderID,
		&i.Key,
		&i.ThumbnailKey,
		&i.Name,
		&i.Mime,
		&i.Size,
		&i.Width,
		&i.Height,
		&i.Sha256,
		&i.CreatedAt,
	)
	return i, err
}

const getFilesWithUsage = `-- name: GetFilesWithUsage :many
SELECT f.id, f.workspace_id, f.uploader_id, f.key, f.thumbnail_key, f.name, f.mime, f.size, f.width, f.height, f.sha256, f.created_at, EXISTS (SELECT 1 FROM message_attachments ma WHERE ma.file_id = f.id) AS attached
FROM files f WHERE f.id = ANY($1::uuid[])
`

type GetFilesWithUsageRow struct {
	ID           uuid.UUID
	WorkspaceID  *uuid.UUID
	UploaderID   uuid.UUID
	Key          string
	ThumbnailKey *string
	Name         string
	Mime         string
	Size         int64
	Width        *int32
	Height       *int32
	Sha256       string
	CreatedAt    time.Time
	Attached     bool
}

func (q *Queries) GetFilesWithUsage(ctx context.Context, ids []uuid.UUID) ([]GetFilesWithUsageRow, error) {
	rows, err := q.db.Query(ctx, getFilesWithUsage, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFilesWithUsageRow{}
	for rows.Next() {
		var i GetFilesWithUsageRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UploaderID,
			&i.Key,
			&i.ThumbnailKey,
			&i.Name,
			&i.Mime,
			&i.Size,
			&i.Width,
			&i.Height,
			&i.Sha256,
			&i.CreatedAt,
			&i.Attached,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertFile = `-- name: InsertFile :one
INSERT INTO files (id, workspace_id, uploader_id, key, thumbnail_key, name, mime, size, width, height, sha256)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, workspace_id, uploader_id, key, thumbnail_key, name, mime, size, width, height, sha256, created_at
`

type InsertFileParams struct {
	ID           uuid.UUID
	WorkspaceID  *uuid.UUID
	UploaderID   uuid.UUID
	Key          string
	ThumbnailKey *string
	Name         string
	Mime         string
	Size         int64
	Width        *int32
	Height       *int32
	Sha256       string
}

func (q *Queries) InsertFile(ctx context.Context, arg InsertFileParams) (File, error) {
	row := q.db.QueryRow(ctx, insertFile,
		arg.ID,
		arg.WorkspaceID,
		arg.UploaderID,
		arg.Key,
		arg.ThumbnailKey,
		arg.Name,
		arg.Mime,
		arg.Size,
		arg.Width,
		arg.Height,
		arg.Sha256,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UploaderID,
		&i.Key,
		&i.ThumbnailKey,
		&i.Name,
		&i.Mime,
		&i.Size,
		&i.Width,
		&i.Height,
		&i.Sha256,
		&i.CreatedAt,
	)
	return i, err
}

const isWorkspaceIcon = `-- name: IsWorkspaceIcon :one
SELECT EXISTS (SELECT 1 FROM workspaces WHERE icon_file_id = $1)
`

func (q *Queries) IsWorkspaceIcon(ctx context.Context, iconFileID *uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isWorkspaceIcon, iconFileID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listOrphanFiles = `-- name: ListOrphanFiles :many
SELECT id, workspace_id, uploader_id, key, thumbnail_key, name, mime, size, width, height, sha256, created_at FROM files f
WHERE f.created_at < $1
  AND NOT EXISTS (SELECT 1 FROM message_attachments ma WHERE ma.file_id = f.id)
  AND NOT EXISTS (SELECT 1 FROM users u WHERE u.avatar_file_id = f.id)
  AND NOT EXISTS (SELECT 1 FROM workspaces w WHERE w.icon_file_id = f.id)
ORDER BY f.created_at
LIMIT 500
`

// Not attached, not an avatar or icon, older than the cutoff.
func (q *Queries) ListOrphanFiles(ctx context.Context, createdAt time.Time) ([]File, error) {
	rows, err := q.db.Query(ctx, listOrphanFiles, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UploaderID,
			&i.Key,
			&i.ThumbnailKey,
			&i.Name,
			&i.Mime,
			&i.Size,
			&i.Width,
			&i.Height,
			&i.Sha256,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceFileKeys = `-- name: ListWorkspaceFileKeys :many
SELECT key, thumbnail_key FROM files WHERE workspace_id = $1
`

type ListWorkspaceFileKeysRow struct {
	Key          string
	ThumbnailKey *string
}

func (q *Queries) ListWorkspaceFileKeys(ctx context.Context, workspaceID *uuid.UUID) ([]ListWorkspaceFileKeysRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceFileKeys, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceFileKeysRow{}
	for rows.Next() {
		var i ListWorkspaceFileKeysRow
		if err := rows.Scan(&i.Key, &i.ThumbnailKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseQuota = `-- name: ReleaseQuota :exec
UPDATE workspaces SET storage_used_bytes = greatest(0, storage_used_bytes - $1::bigint)
WHERE id = $2
`

type ReleaseQuotaParams struct {
	Size int64
	ID   uuid.UUID
}

func (q *Queries) ReleaseQuota(ctx context.Context, arg ReleaseQuotaParams) error {
	_, err := q.db.Exec(ctx, releaseQuota, arg.Size, arg.ID)
	return err
}

const reserveQuota = `-- name: ReserveQuota :one
UPDATE workspaces SET storage_used_bytes = storage_used_bytes + $1::bigint
WHERE id = $2 AND storage_used_bytes + $1::bigint <= storage_quota_bytes
RETURNING storage_used_bytes
`

type ReserveQuotaParams struct {
	Size int64
	ID   uuid.UUID
}

// Atomically adds size to the workspace usage if it fits the quota; no row = quota exceeded.
func (q *Queries) ReserveQuota(ctx context.Context, arg ReserveQuotaParams) (int64, error) {
	row := q.db.QueryRow(ctx, reserveQuota, arg.Size, arg.ID)
	var storage_used_bytes int64
	err := row.Scan(&storage_used_bytes)
	return storage_used_bytes, err
}

const tryAdvisoryXactLock = `-- name: TryAdvisoryXactLock :one
SELECT pg_try_advisory_xact_lock(hashtext($1::text))
`

func (q *Queries) TryAdvisoryXactLock(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRow(ctx, tryAdvisoryXactLock, name)
	var pg_try_advisory_xact_lock bool
	err := row.Scan(&pg_try_advisory_xact_lock)
	return pg_try_advisory_xact_lock, err
}
