// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: interactions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getInteraction = `-- name: GetInteraction :one
SELECT id, message_id, user_id, nonce, button_id, keyboard_revision, created_at FROM message_interactions WHERE user_id = $1 AND nonce = $2
`

type GetInteractionParams struct {
	UserID uuid.UUID
	Nonce  string
}

func (q *Queries) GetInteraction(ctx context.Context, arg GetInteractionParams) (MessageInteraction, error) {
	row := q.db.QueryRow(ctx, getInteraction, arg.UserID, arg.Nonce)
	var i MessageInteraction
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.UserID,
		&i.Nonce,
		&i.ButtonID,
		&i.KeyboardRevision,
		&i.CreatedAt,
	)
	return i, err
}

const getMessageForInteraction = `-- name: GetMessageForInteraction :one
SELECT id, room_id, author_id, content, reply_to_id, nonce, created_at, edited_at, deleted_at, pinned_at, pinned_by, embeds_hidden, kind, payload, sticker_id, forwarded_from, forward_author_id, forward_sent_at, inline_keyboard, keyboard_revision FROM messages WHERE id = $1 AND deleted_at IS NULL FOR UPDATE
`

// Text/keyboard edits and soft deletion take the same row lock.
func (q *Queries) GetMessageForInteraction(ctx context.Context, id uuid.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageForInteraction, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.AuthorID,
		&i.Content,
		&i.ReplyToID,
		&i.Nonce,
		&i.CreatedAt,
		&i.EditedAt,
		&i.DeletedAt,
		&i.PinnedAt,
		&i.PinnedBy,
		&i.EmbedsHidden,
		&i.Kind,
		&i.Payload,
		&i.StickerID,
		&i.ForwardedFrom,
		&i.ForwardAuthorID,
		&i.ForwardSentAt,
		&i.InlineKeyboard,
		&i.KeyboardRevision,
	)
	return i, err
}

const insertInteraction = `-- name: InsertInteraction :one
INSERT INTO message_interactions (message_id, user_id, nonce, button_id, keyboard_revision)
VALUES ($1, $2, $3, $4, $5) RETURNING id, message_id, user_id, nonce, button_id, keyboard_revision, created_at
`

type InsertInteractionParams struct {
	MessageID        uuid.UUID
	UserID           uuid.UUID
	Nonce            string
	ButtonID         string
	KeyboardRevision int64
}

func (q *Queries) InsertInteraction(ctx context.Context, arg InsertInteractionParams) (MessageInteraction, error) {
	row := q.db.QueryRow(ctx, insertInteraction,
		arg.MessageID,
		arg.UserID,
		arg.Nonce,
		arg.ButtonID,
		arg.KeyboardRevision,
	)
	var i MessageInteraction
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.UserID,
		&i.Nonce,
		&i.ButtonID,
		&i.KeyboardRevision,
		&i.CreatedAt,
	)
	return i, err
}

const lockInteractionNonce = `-- name: LockInteractionNonce :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 45))
`

// Serialize a caller's retries, including across messages, before locking the message.
func (q *Queries) LockInteractionNonce(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, lockInteractionNonce, key)
	return err
}
