// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invites.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeInvite = `-- name: ConsumeInvite :one
UPDATE workspace_invites SET uses = uses + 1
WHERE code = $1
  AND (expires_at IS NULL OR expires_at > now())
  AND (max_uses = 0 OR uses < max_uses)
RETURNING id, workspace_id, code, created_by, max_uses, uses, expires_at, created_at
`

// Atomically takes one use of a valid invite; no row = invalid / expired / used up.
func (q *Queries) ConsumeInvite(ctx context.Context, code string) (WorkspaceInvite, error) {
	row := q.db.QueryRow(ctx, consumeInvite, code)
	var i WorkspaceInvite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Code,
		&i.CreatedBy,
		&i.MaxUses,
		&i.Uses,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const countWorkspaceMembers = `-- name: CountWorkspaceMembers :one
SELECT count(*)::integer FROM workspace_members WHERE workspace_id = $1 AND role <> 'guest'
`

// Members without guests (public invite preview).
func (q *Queries) CountWorkspaceMembers(ctx context.Context, workspaceID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countWorkspaceMembers, workspaceID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO workspace_invites (workspace_id, code, created_by, max_uses, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workspace_id, code, created_by, max_uses, uses, expires_at, created_at
`

type CreateInviteParams struct {
	WorkspaceID uuid.UUID
	Code        string
	CreatedBy   uuid.UUID
	MaxUses     int32
	ExpiresAt   *time.Time
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (WorkspaceInvite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.WorkspaceID,
		arg.Code,
		arg.CreatedBy,
		arg.MaxUses,
		arg.ExpiresAt,
	)
	var i WorkspaceInvite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Code,
		&i.CreatedBy,
		&i.MaxUses,
		&i.Uses,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInvite = `-- name: DeleteInvite :execrows
DELETE FROM workspace_invites WHERE id = $1 AND workspace_id = $2
`

type DeleteInviteParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) DeleteInvite(ctx context.Context, arg DeleteInviteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInvite, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getInviteByCode = `-- name: GetInviteByCode :one
SELECT id, workspace_id, code, created_by, max_uses, uses, expires_at, created_at FROM workspace_invites WHERE code = $1
`

func (q *Queries) GetInviteByCode(ctx context.Context, code string) (WorkspaceInvite, error) {
	row := q.db.QueryRow(ctx, getInviteByCode, code)
	var i WorkspaceInvite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Code,
		&i.CreatedBy,
		&i.MaxUses,
		&i.Uses,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listInvites = `-- name: ListInvites :many
SELECT id, workspace_id, code, created_by, max_uses, uses, expires_at, created_at FROM workspace_invites i
WHERE i.workspace_id = $1 AND NOT EXISTS (SELECT 1 FROM email_invites e WHERE e.invite_id = i.id)
ORDER BY i.created_at DESC
`

// Links only: invitations sent by email are listed by ListEmailInvites.
func (q *Queries) ListInvites(ctx context.Context, workspaceID uuid.UUID) ([]WorkspaceInvite, error) {
	rows, err := q.db.Query(ctx, listInvites, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceInvite{}
	for rows.Next() {
		var i WorkspaceInvite
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Code,
			&i.CreatedBy,
			&i.MaxUses,
			&i.Uses,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockWorkspaceMembers = `-- name: LockWorkspaceMembers :exec
SELECT pg_advisory_xact_lock(hashtext('calaba.members:' || $1::uuid::text))
`

// Serializes the plan's members check of one workspace between the count and the insert.
func (q *Queries) LockWorkspaceMembers(ctx context.Context, workspaceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockWorkspaceMembers, workspaceID)
	return err
}
