// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mail.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimMail = `-- name: ClaimMail :many
UPDATE mail_outbox SET next_at = now() + $1::interval
WHERE id IN (
    SELECT o.id FROM mail_outbox o
    WHERE o.sent_at IS NULL AND o.failed_at IS NULL AND o.next_at <= now()
    ORDER BY o.priority, o.next_at
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
RETURNING id, to_addr, template, locale, params, priority, attempts, next_at, expires_at, created_at, sent_at, failed_at, error
`

type ClaimMailParams struct {
	Lease pgtype.Interval
	Lim   int32
}

// Takes up to `lim` due mails for sending: their next_at moves one lease ahead, so a crashed
// worker's mails are retried later and a second worker (lock lost) skips them.
func (q *Queries) ClaimMail(ctx context.Context, arg ClaimMailParams) ([]MailOutbox, error) {
	rows, err := q.db.Query(ctx, claimMail, arg.Lease, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MailOutbox{}
	for rows.Next() {
		var i MailOutbox
		if err := rows.Scan(
			&i.ID,
			&i.ToAddr,
			&i.Template,
			&i.Locale,
			&i.Params,
			&i.Priority,
			&i.Attempts,
			&i.NextAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.SentAt,
			&i.FailedAt,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteEmailCode = `-- name: DeleteEmailCode :exec
DELETE FROM email_codes WHERE user_id = $1 AND purpose = $2
`

type DeleteEmailCodeParams struct {
	UserID  uuid.UUID
	Purpose string
}

func (q *Queries) DeleteEmailCode(ctx context.Context, arg DeleteEmailCodeParams) error {
	_, err := q.db.Exec(ctx, deleteEmailCode, arg.UserID, arg.Purpose)
	return err
}

const deleteExpiredEmailCodes = `-- name: DeleteExpiredEmailCodes :execrows
DELETE FROM email_codes WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredEmailCodes(ctx context.Context, expiresAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredEmailCodes, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOldMail = `-- name: DeleteOldMail :execrows
DELETE FROM mail_outbox WHERE created_at < $1 AND (sent_at IS NOT NULL OR failed_at IS NOT NULL)
`

func (q *Queries) DeleteOldMail(ctx context.Context, createdAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldMail, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enqueueMail = `-- name: EnqueueMail :one

INSERT INTO mail_outbox (to_addr, template, locale, params, priority, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type EnqueueMailParams struct {
	ToAddr    string
	Template  string
	Locale    string
	Params    []byte
	Priority  int16
	ExpiresAt time.Time
}

// ADR-0023: mail outbox and email codes.
func (q *Queries) EnqueueMail(ctx context.Context, arg EnqueueMailParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, enqueueMail,
		arg.ToAddr,
		arg.Template,
		arg.Locale,
		arg.Params,
		arg.Priority,
		arg.ExpiresAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getEmailCode = `-- name: GetEmailCode :one
SELECT user_id, purpose, code_hash, expires_at, attempts, created_at FROM email_codes WHERE user_id = $1 AND purpose = $2
`

type GetEmailCodeParams struct {
	UserID  uuid.UUID
	Purpose string
}

func (q *Queries) GetEmailCode(ctx context.Context, arg GetEmailCodeParams) (EmailCode, error) {
	row := q.db.QueryRow(ctx, getEmailCode, arg.UserID, arg.Purpose)
	var i EmailCode
	err := row.Scan(
		&i.UserID,
		&i.Purpose,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.CreatedAt,
	)
	return i, err
}

const getMail = `-- name: GetMail :one
SELECT id, to_addr, template, locale, params, priority, attempts, next_at, expires_at, created_at, sent_at, failed_at, error FROM mail_outbox WHERE id = $1
`

func (q *Queries) GetMail(ctx context.Context, id uuid.UUID) (MailOutbox, error) {
	row := q.db.QueryRow(ctx, getMail, id)
	var i MailOutbox
	err := row.Scan(
		&i.ID,
		&i.ToAddr,
		&i.Template,
		&i.Locale,
		&i.Params,
		&i.Priority,
		&i.Attempts,
		&i.NextAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.SentAt,
		&i.FailedAt,
		&i.Error,
	)
	return i, err
}

const markMailFailed = `-- name: MarkMailFailed :exec
UPDATE mail_outbox SET attempts = attempts + 1, failed_at = now(), params = NULL, error = $2 WHERE id = $1
`

type MarkMailFailedParams struct {
	ID    uuid.UUID
	Error string
}

func (q *Queries) MarkMailFailed(ctx context.Context, arg MarkMailFailedParams) error {
	_, err := q.db.Exec(ctx, markMailFailed, arg.ID, arg.Error)
	return err
}

const markMailRetry = `-- name: MarkMailRetry :exec
UPDATE mail_outbox SET attempts = attempts + 1, next_at = $2, error = $3 WHERE id = $1
`

type MarkMailRetryParams struct {
	ID     uuid.UUID
	NextAt time.Time
	Error  string
}

func (q *Queries) MarkMailRetry(ctx context.Context, arg MarkMailRetryParams) error {
	_, err := q.db.Exec(ctx, markMailRetry, arg.ID, arg.NextAt, arg.Error)
	return err
}

const markMailSent = `-- name: MarkMailSent :exec
UPDATE mail_outbox SET sent_at = now(), params = NULL, error = '' WHERE id = $1
`

func (q *Queries) MarkMailSent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markMailSent, id)
	return err
}

const postponeMail = `-- name: PostponeMail :exec
UPDATE mail_outbox SET next_at = $2 WHERE id = $1
`

type PostponeMailParams struct {
	ID     uuid.UUID
	NextAt time.Time
}

// Server-wide send limit reached: try again later without counting an attempt.
func (q *Queries) PostponeMail(ctx context.Context, arg PostponeMailParams) error {
	_, err := q.db.Exec(ctx, postponeMail, arg.ID, arg.NextAt)
	return err
}

const putEmailCode = `-- name: PutEmailCode :one
INSERT INTO email_codes (user_id, purpose, code_hash, expires_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, purpose) DO UPDATE
SET code_hash = excluded.code_hash, expires_at = excluded.expires_at, attempts = 0, created_at = now()
WHERE email_codes.created_at < $5
RETURNING user_id, purpose, code_hash, expires_at, attempts, created_at
`

type PutEmailCodeParams struct {
	UserID       uuid.UUID
	Purpose      string
	CodeHash     string
	ExpiresAt    time.Time
	ResendBefore time.Time
}

// Replaces the code unless the current one was created after resend_before (60 s ago):
// no row = too soon. Atomic, so two parallel resends cannot both mail a code.
func (q *Queries) PutEmailCode(ctx context.Context, arg PutEmailCodeParams) (EmailCode, error) {
	row := q.db.QueryRow(ctx, putEmailCode,
		arg.UserID,
		arg.Purpose,
		arg.CodeHash,
		arg.ExpiresAt,
		arg.ResendBefore,
	)
	var i EmailCode
	err := row.Scan(
		&i.UserID,
		&i.Purpose,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.CreatedAt,
	)
	return i, err
}

const takeEmailCodeAttempt = `-- name: TakeEmailCodeAttempt :one
UPDATE email_codes SET attempts = attempts + 1
WHERE user_id = $1 AND purpose = $2 AND expires_at > now() AND attempts < $3::integer
RETURNING user_id, purpose, code_hash, expires_at, attempts, created_at
`

type TakeEmailCodeAttemptParams struct {
	UserID      uuid.UUID
	Purpose     string
	MaxAttempts int32
}

// Counts one attempt of a live code before it is checked; no row = no usable code.
func (q *Queries) TakeEmailCodeAttempt(ctx context.Context, arg TakeEmailCodeAttemptParams) (EmailCode, error) {
	row := q.db.QueryRow(ctx, takeEmailCodeAttempt, arg.UserID, arg.Purpose, arg.MaxAttempts)
	var i EmailCode
	err := row.Scan(
		&i.UserID,
		&i.Purpose,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.CreatedAt,
	)
	return i, err
}
