// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mentions.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteEveryoneMention = `-- name: DeleteEveryoneMention :exec
DELETE FROM message_everyone_mentions WHERE message_id = $1
`

func (q *Queries) DeleteEveryoneMention(ctx context.Context, messageID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEveryoneMention, messageID)
	return err
}

const deleteMentions = `-- name: DeleteMentions :exec
DELETE FROM message_mentions WHERE message_id = $1
`

func (q *Queries) DeleteMentions(ctx context.Context, messageID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMentions, messageID)
	return err
}

const deleteRoomNotificationSettings = `-- name: DeleteRoomNotificationSettings :exec
DELETE FROM room_notification_settings WHERE user_id = $1 AND room_id = $2
`

type DeleteRoomNotificationSettingsParams struct {
	UserID uuid.UUID
	RoomID uuid.UUID
}

func (q *Queries) DeleteRoomNotificationSettings(ctx context.Context, arg DeleteRoomNotificationSettingsParams) error {
	_, err := q.db.Exec(ctx, deleteRoomNotificationSettings, arg.UserID, arg.RoomID)
	return err
}

const deleteWorkspaceNotificationSettings = `-- name: DeleteWorkspaceNotificationSettings :exec
DELETE FROM workspace_notification_settings WHERE user_id = $1 AND workspace_id = $2
`

type DeleteWorkspaceNotificationSettingsParams struct {
	UserID      uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) DeleteWorkspaceNotificationSettings(ctx context.Context, arg DeleteWorkspaceNotificationSettingsParams) error {
	_, err := q.db.Exec(ctx, deleteWorkspaceNotificationSettings, arg.UserID, arg.WorkspaceID)
	return err
}

const getWorkspaceTaskLevel = `-- name: GetWorkspaceTaskLevel :one
SELECT coalesce((SELECT s.task_level FROM workspace_notification_settings s
    WHERE s.user_id = $1 AND s.workspace_id = $2), 'all')::text
`

type GetWorkspaceTaskLevelParams struct {
	UserID      uuid.UUID
	WorkspaceID uuid.UUID
}

// The stored «Задачи» level of the user in the workspace ('all' without a row, ADR-0042).
func (q *Queries) GetWorkspaceTaskLevel(ctx context.Context, arg GetWorkspaceTaskLevelParams) (string, error) {
	row := q.db.QueryRow(ctx, getWorkspaceTaskLevel, arg.UserID, arg.WorkspaceID)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const insertEveryoneMention = `-- name: InsertEveryoneMention :exec
INSERT INTO message_everyone_mentions (message_id, room_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertEveryoneMentionParams struct {
	MessageID uuid.UUID
	RoomID    uuid.UUID
}

func (q *Queries) InsertEveryoneMention(ctx context.Context, arg InsertEveryoneMentionParams) error {
	_, err := q.db.Exec(ctx, insertEveryoneMention, arg.MessageID, arg.RoomID)
	return err
}

const insertMentions = `-- name: InsertMentions :exec
INSERT INTO message_mentions (user_id, message_id, room_id)
SELECT u, $1::uuid, $2::uuid
FROM unnest($3::uuid[]) AS u
JOIN workspace_members wm ON wm.user_id = u AND wm.workspace_id = $4::uuid
WHERE u <> $5::uuid
  AND NOT EXISTS (SELECT 1 FROM bot_blocks bb WHERE bb.user_id = u AND bb.bot_user_id = $5::uuid)
ON CONFLICT DO NOTHING
`

type InsertMentionsParams struct {
	MessageID   uuid.UUID
	RoomID      uuid.UUID
	UserIds     []uuid.UUID
	WorkspaceID uuid.UUID
	AuthorID    uuid.UUID
}

// Direct mentions: only members of the room's workspace, never the author, never a person
// who blocked the author (a bot, ADR-0031).
func (q *Queries) InsertMentions(ctx context.Context, arg InsertMentionsParams) error {
	_, err := q.db.Exec(ctx, insertMentions,
		arg.MessageID,
		arg.RoomID,
		arg.UserIds,
		arg.WorkspaceID,
		arg.AuthorID,
	)
	return err
}

const listMentions = `-- name: ListMentions :many
WITH ids AS (
    (SELECT mm.message_id AS id FROM message_mentions mm
     WHERE mm.user_id = $2::uuid AND mm.room_id = ANY($3::uuid[])
       AND ($4::uuid IS NULL OR mm.message_id < $4::uuid)
     ORDER BY mm.message_id DESC LIMIT $1)
    UNION
    (SELECT e.message_id FROM message_everyone_mentions e
     JOIN messages em ON em.id = e.message_id AND em.author_id <> $2::uuid
     WHERE e.room_id = ANY($3::uuid[])
       AND ($4::uuid IS NULL OR e.message_id < $4::uuid)
     ORDER BY e.message_id DESC LIMIT $1)
)
SELECT m.id, m.room_id, m.author_id, m.content, m.reply_to_id, m.nonce, m.created_at, m.edited_at, m.deleted_at, m.pinned_at, m.pinned_by, m.embeds_hidden, m.kind, m.payload, m.sticker_id, m.forwarded_from, m.forward_author_id, m.forward_sent_at FROM messages m
JOIN ids ON ids.id = m.id
WHERE m.deleted_at IS NULL
ORDER BY m.id DESC
LIMIT $1
`

type ListMentionsParams struct {
	Lim     int32
	UserID  uuid.UUID
	RoomIds []uuid.UUID
	Before  *uuid.UUID
}

// Newest first. Each branch is an index range scan limited to one page; own messages and
// deleted ones are excluded (mention rows are removed on delete, the filter is a safety net).
func (q *Queries) ListMentions(ctx context.Context, arg ListMentionsParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMentions,
		arg.Lim,
		arg.UserID,
		arg.RoomIds,
		arg.Before,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.AuthorID,
			&i.Content,
			&i.ReplyToID,
			&i.Nonce,
			&i.CreatedAt,
			&i.EditedAt,
			&i.DeletedAt,
			&i.PinnedAt,
			&i.PinnedBy,
			&i.EmbedsHidden,
			&i.Kind,
			&i.Payload,
			&i.StickerID,
			&i.ForwardedFrom,
			&i.ForwardAuthorID,
			&i.ForwardSentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomNotificationSettings = `-- name: ListRoomNotificationSettings :many
SELECT s.user_id, s.room_id, s.level, s.muted_until FROM room_notification_settings s
WHERE s.user_id = $1::uuid AND s.room_id = ANY($2::uuid[])
`

type ListRoomNotificationSettingsParams struct {
	UserID  uuid.UUID
	RoomIds []uuid.UUID
}

// Stored settings of the given rooms (the ones the user can view now).
func (q *Queries) ListRoomNotificationSettings(ctx context.Context, arg ListRoomNotificationSettingsParams) ([]RoomNotificationSetting, error) {
	rows, err := q.db.Query(ctx, listRoomNotificationSettings, arg.UserID, arg.RoomIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoomNotificationSetting{}
	for rows.Next() {
		var i RoomNotificationSetting
		if err := rows.Scan(
			&i.UserID,
			&i.RoomID,
			&i.Level,
			&i.MutedUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceNotificationSettings = `-- name: ListWorkspaceNotificationSettings :many
SELECT s.user_id, s.workspace_id, s.level, s.muted_until, s.task_level FROM workspace_notification_settings s
JOIN workspace_members m ON m.workspace_id = s.workspace_id AND m.user_id = s.user_id
WHERE s.user_id = $1
`

// Stored settings of the workspaces the user is a member of now.
func (q *Queries) ListWorkspaceNotificationSettings(ctx context.Context, userID uuid.UUID) ([]WorkspaceNotificationSetting, error) {
	rows, err := q.db.Query(ctx, listWorkspaceNotificationSettings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceNotificationSetting{}
	for rows.Next() {
		var i WorkspaceNotificationSetting
		if err := rows.Scan(
			&i.UserID,
			&i.WorkspaceID,
			&i.Level,
			&i.MutedUntil,
			&i.TaskLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRoomNotificationSettings = `-- name: UpsertRoomNotificationSettings :one
INSERT INTO room_notification_settings (user_id, room_id, level, muted_until)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, room_id) DO UPDATE SET level = EXCLUDED.level, muted_until = EXCLUDED.muted_until
RETURNING user_id, room_id, level, muted_until
`

type UpsertRoomNotificationSettingsParams struct {
	UserID     uuid.UUID
	RoomID     uuid.UUID
	Level      string
	MutedUntil *time.Time
}

func (q *Queries) UpsertRoomNotificationSettings(ctx context.Context, arg UpsertRoomNotificationSettingsParams) (RoomNotificationSetting, error) {
	row := q.db.QueryRow(ctx, upsertRoomNotificationSettings,
		arg.UserID,
		arg.RoomID,
		arg.Level,
		arg.MutedUntil,
	)
	var i RoomNotificationSetting
	err := row.Scan(
		&i.UserID,
		&i.RoomID,
		&i.Level,
		&i.MutedUntil,
	)
	return i, err
}

const upsertWorkspaceNotificationSettings = `-- name: UpsertWorkspaceNotificationSettings :one
INSERT INTO workspace_notification_settings (user_id, workspace_id, level, muted_until, task_level)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, workspace_id) DO UPDATE SET level = EXCLUDED.level, muted_until = EXCLUDED.muted_until, task_level = EXCLUDED.task_level
RETURNING user_id, workspace_id, level, muted_until, task_level
`

type UpsertWorkspaceNotificationSettingsParams struct {
	UserID      uuid.UUID
	WorkspaceID uuid.UUID
	Level       string
	MutedUntil  *time.Time
	TaskLevel   string
}

func (q *Queries) UpsertWorkspaceNotificationSettings(ctx context.Context, arg UpsertWorkspaceNotificationSettingsParams) (WorkspaceNotificationSetting, error) {
	row := q.db.QueryRow(ctx, upsertWorkspaceNotificationSettings,
		arg.UserID,
		arg.WorkspaceID,
		arg.Level,
		arg.MutedUntil,
		arg.TaskLevel,
	)
	var i WorkspaceNotificationSetting
	err := row.Scan(
		&i.UserID,
		&i.WorkspaceID,
		&i.Level,
		&i.MutedUntil,
		&i.TaskLevel,
	)
	return i, err
}
