// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const detachMessageFiles = `-- name: DetachMessageFiles :exec
DELETE FROM message_attachments WHERE message_id = $1
`

func (q *Queries) DetachMessageFiles(ctx context.Context, messageID uuid.UUID) error {
	_, err := q.db.Exec(ctx, detachMessageFiles, messageID)
	return err
}

const getMessage = `-- name: GetMessage :one
SELECT id, room_id, author_id, content, reply_to_id, nonce, created_at, edited_at, deleted_at FROM messages WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetMessage(ctx context.Context, id uuid.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.AuthorID,
		&i.Content,
		&i.ReplyToID,
		&i.Nonce,
		&i.CreatedAt,
		&i.EditedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMessageByNonce = `-- name: GetMessageByNonce :one
SELECT id, room_id, author_id, content, reply_to_id, nonce, created_at, edited_at, deleted_at FROM messages WHERE author_id = $1 AND nonce = $2
`

type GetMessageByNonceParams struct {
	AuthorID uuid.UUID
	Nonce    *string
}

func (q *Queries) GetMessageByNonce(ctx context.Context, arg GetMessageByNonceParams) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByNonce, arg.AuthorID, arg.Nonce)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.AuthorID,
		&i.Content,
		&i.ReplyToID,
		&i.Nonce,
		&i.CreatedAt,
		&i.EditedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertAttachment = `-- name: InsertAttachment :exec
INSERT INTO message_attachments (message_id, file_id, position) VALUES ($1, $2, $3)
`

type InsertAttachmentParams struct {
	MessageID uuid.UUID
	FileID    uuid.UUID
	Position  int16
}

func (q *Queries) InsertAttachment(ctx context.Context, arg InsertAttachmentParams) error {
	_, err := q.db.Exec(ctx, insertAttachment, arg.MessageID, arg.FileID, arg.Position)
	return err
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO messages (room_id, author_id, content, reply_to_id, nonce)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (author_id, nonce) WHERE nonce IS NOT NULL DO NOTHING
RETURNING id, room_id, author_id, content, reply_to_id, nonce, created_at, edited_at, deleted_at
`

type InsertMessageParams struct {
	RoomID    uuid.UUID
	AuthorID  uuid.UUID
	Content   string
	ReplyToID *uuid.UUID
	Nonce     *string
}

// Idempotent by (author_id, nonce): no row = a message with this nonce already exists.
func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, insertMessage,
		arg.RoomID,
		arg.AuthorID,
		arg.Content,
		arg.ReplyToID,
		arg.Nonce,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.AuthorID,
		&i.Content,
		&i.ReplyToID,
		&i.Nonce,
		&i.CreatedAt,
		&i.EditedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAttachments = `-- name: ListAttachments :many
SELECT ma.message_id, f.id, f.workspace_id, f.uploader_id, f.key, f.thumbnail_key, f.name, f.mime, f.size, f.width, f.height, f.sha256, f.created_at
FROM message_attachments ma JOIN files f ON f.id = ma.file_id
WHERE ma.message_id = ANY($1::uuid[])
ORDER BY ma.message_id, ma.position
`

type ListAttachmentsRow struct {
	MessageID uuid.UUID
	File      File
}

func (q *Queries) ListAttachments(ctx context.Context, ids []uuid.UUID) ([]ListAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, listAttachments, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttachmentsRow{}
	for rows.Next() {
		var i ListAttachmentsRow
		if err := rows.Scan(
			&i.MessageID,
			&i.File.ID,
			&i.File.WorkspaceID,
			&i.File.UploaderID,
			&i.File.Key,
			&i.File.ThumbnailKey,
			&i.File.Name,
			&i.File.Mime,
			&i.File.Size,
			&i.File.Width,
			&i.File.Height,
			&i.File.Sha256,
			&i.File.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesAfter = `-- name: ListMessagesAfter :many
SELECT id, room_id, author_id, content, reply_to_id, nonce, created_at, edited_at, deleted_at FROM messages
WHERE room_id = $1 AND deleted_at IS NULL AND id > $2::uuid
ORDER BY id ASC
LIMIT $3
`

type ListMessagesAfterParams struct {
	RoomID uuid.UUID
	After  uuid.UUID
	Lim    int32
}

// Oldest first.
func (q *Queries) ListMessagesAfter(ctx context.Context, arg ListMessagesAfterParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesAfter, arg.RoomID, arg.After, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.AuthorID,
			&i.Content,
			&i.ReplyToID,
			&i.Nonce,
			&i.CreatedAt,
			&i.EditedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesBefore = `-- name: ListMessagesBefore :many
SELECT id, room_id, author_id, content, reply_to_id, nonce, created_at, edited_at, deleted_at FROM messages
WHERE room_id = $1 AND deleted_at IS NULL
  AND ($2::uuid IS NULL OR id < $2::uuid)
ORDER BY id DESC
LIMIT $3
`

type ListMessagesBeforeParams struct {
	RoomID uuid.UUID
	Before *uuid.UUID
	Lim    int32
}

// Newest first. NULL before = from the newest message.
func (q *Queries) ListMessagesBefore(ctx context.Context, arg ListMessagesBeforeParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesBefore, arg.RoomID, arg.Before, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.AuthorID,
			&i.Content,
			&i.ReplyToID,
			&i.Nonce,
			&i.CreatedAt,
			&i.EditedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadStates = `-- name: ListReadStates :many
SELECT rs.user_id, rs.room_id, rs.last_read_message_id FROM read_states rs
JOIN rooms r ON r.id = rs.room_id AND r.archived_at IS NULL
WHERE rs.user_id = $1
`

func (q *Queries) ListReadStates(ctx context.Context, userID uuid.UUID) ([]ReadState, error) {
	rows, err := q.db.Query(ctx, listReadStates, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadState{}
	for rows.Next() {
		var i ReadState
		if err := rows.Scan(&i.UserID, &i.RoomID, &i.LastReadMessageID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteMessage = `-- name: SoftDeleteMessage :execrows
UPDATE messages SET deleted_at = now(), content = ''
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteMessage(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteMessage, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateMessageContent = `-- name: UpdateMessageContent :one
UPDATE messages SET content = $2, edited_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, room_id, author_id, content, reply_to_id, nonce, created_at, edited_at, deleted_at
`

type UpdateMessageContentParams struct {
	ID      uuid.UUID
	Content string
}

func (q *Queries) UpdateMessageContent(ctx context.Context, arg UpdateMessageContentParams) (Message, error) {
	row := q.db.QueryRow(ctx, updateMessageContent, arg.ID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.AuthorID,
		&i.Content,
		&i.ReplyToID,
		&i.Nonce,
		&i.CreatedAt,
		&i.EditedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertReadState = `-- name: UpsertReadState :one
INSERT INTO read_states (user_id, room_id, last_read_message_id)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, room_id) DO UPDATE
    SET last_read_message_id = GREATEST(read_states.last_read_message_id, EXCLUDED.last_read_message_id)
RETURNING user_id, room_id, last_read_message_id
`

type UpsertReadStateParams struct {
	UserID            uuid.UUID
	RoomID            uuid.UUID
	LastReadMessageID uuid.UUID
}

// The marker only moves forward (uuidv7 order = message order).
func (q *Queries) UpsertReadState(ctx context.Context, arg UpsertReadStateParams) (ReadState, error) {
	row := q.db.QueryRow(ctx, upsertReadState, arg.UserID, arg.RoomID, arg.LastReadMessageID)
	var i ReadState
	err := row.Scan(&i.UserID, &i.RoomID, &i.LastReadMessageID)
	return i, err
}
