// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type File struct {
	ID           uuid.UUID
	WorkspaceID  *uuid.UUID
	UploaderID   uuid.UUID
	Key          string
	ThumbnailKey *string
	Name         string
	Mime         string
	Size         int64
	Width        *int32
	Height       *int32
	Sha256       string
	CreatedAt    time.Time
}

type Message struct {
	ID        uuid.UUID
	RoomID    uuid.UUID
	AuthorID  uuid.UUID
	Content   string
	ReplyToID *uuid.UUID
	Nonce     *string
	CreatedAt time.Time
	EditedAt  *time.Time
	DeletedAt *time.Time
	PinnedAt  *time.Time
	PinnedBy  *uuid.UUID
}

type MessageAttachment struct {
	MessageID uuid.UUID
	FileID    uuid.UUID
	Position  int16
}

type MessageReaction struct {
	MessageID uuid.UUID
	UserID    uuid.UUID
	Emoji     string
	CreatedAt time.Time
}

type ReadState struct {
	UserID            uuid.UUID
	RoomID            uuid.UUID
	LastReadMessageID uuid.UUID
}

type Room struct {
	ID               uuid.UUID
	WorkspaceID      uuid.UUID
	Type             string
	Name             string
	Topic            string
	Position         int32
	IsPrivate        bool
	AudioBitrateKbps *int32
	MaxStreamPreset  *string
	MaxStreams       *int32
	CreatedAt        time.Time
	ArchivedAt       *time.Time
	CategoryID       *uuid.UUID
	UserLimit        int32
}

type RoomCategory struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	Position    int32
	CreatedAt   time.Time
}

type RoomInvite struct {
	ID          uuid.UUID
	RoomID      uuid.UUID
	Code        string
	CreatedBy   uuid.UUID
	ExpiresAt   *time.Time
	MaxUses     int32
	Uses        int32
	AllowGuests bool
	AllowBits   int64
	RevokedAt   *time.Time
	CreatedAt   time.Time
}

type RoomPermission struct {
	RoomID     uuid.UUID
	TargetType string
	TargetID   string
	Allow      int64
	Deny       int64
}

type Session struct {
	ID                   uuid.UUID
	UserID               uuid.UUID
	RefreshTokenHash     []byte
	PrevRefreshTokenHash []byte
	RotatedAt            *time.Time
	DeviceName           string
	Ip                   string
	UserAgent            string
	CreatedAt            time.Time
	LastSeenAt           time.Time
	ExpiresAt            time.Time
	RevokedAt            *time.Time
}

type User struct {
	ID              uuid.UUID
	Email           *string
	PasswordHash    *string
	DisplayName     string
	AvatarFileID    *uuid.UUID
	StatusText      string
	Settings        []byte
	CreatedAt       time.Time
	DisabledAt      *time.Time
	StatusEmoji     string
	StatusExpiresAt *time.Time
	IsGuest         bool
	GuestExpiresAt  *time.Time
}

type Workspace struct {
	ID                      uuid.UUID
	Slug                    string
	Name                    string
	IconFileID              *uuid.UUID
	Visibility              string
	OwnerID                 uuid.UUID
	CreatedAt               time.Time
	DefaultAudioBitrateKbps int32
	DefaultMaxStreamPreset  string
	DefaultMaxStreams       int32
	StorageQuotaBytes       int64
	StorageUsedBytes        int64
	AllowSelfNickname       bool
}

type WorkspaceInvite struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Code        string
	CreatedBy   uuid.UUID
	MaxUses     int32
	Uses        int32
	ExpiresAt   *time.Time
	CreatedAt   time.Time
}

type WorkspaceMember struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Role        string
	Nickname    string
	JoinedAt    time.Time
}
