// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notes.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const canSeeUser = `-- name: CanSeeUser :one
SELECT (
    $1::uuid = $2::uuid
    OR EXISTS (
        SELECT 1 FROM workspace_members a
        JOIN workspace_members b ON b.workspace_id = a.workspace_id AND b.user_id = $2
        WHERE a.user_id = $1)
    OR EXISTS (
        SELECT 1 FROM dm_members a
        JOIN dm_members b ON b.room_id = a.room_id AND b.user_id = $2
        WHERE a.user_id = $1)
)::boolean
`

type CanSeeUserParams struct {
	UserID    uuid.UUID
	SubjectID uuid.UUID
}

// The subject is the user, shares a workspace with them (any role) or a DM: who may keep a
// note about whom. Disabled accounts are still visible (their messages stay).
func (q *Queries) CanSeeUser(ctx context.Context, arg CanSeeUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, canSeeUser, arg.UserID, arg.SubjectID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteNotesAbout = `-- name: DeleteNotesAbout :exec
DELETE FROM user_notes WHERE author_id = $1 OR subject_id = $1
`

// Guest anonymization (ADR-0016): notes written by the user and about them.
func (q *Queries) DeleteNotesAbout(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteNotesAbout, userID)
	return err
}

const deleteUserNote = `-- name: DeleteUserNote :exec
DELETE FROM user_notes WHERE author_id = $1 AND subject_id = $2
`

type DeleteUserNoteParams struct {
	AuthorID  uuid.UUID
	SubjectID uuid.UUID
}

func (q *Queries) DeleteUserNote(ctx context.Context, arg DeleteUserNoteParams) error {
	_, err := q.db.Exec(ctx, deleteUserNote, arg.AuthorID, arg.SubjectID)
	return err
}

const getUserNote = `-- name: GetUserNote :one

SELECT author_id, subject_id, text, updated_at FROM user_notes WHERE author_id = $1 AND subject_id = $2
`

type GetUserNoteParams struct {
	AuthorID  uuid.UUID
	SubjectID uuid.UUID
}

// Private user notes (docs/09 item 20): only the author reads and writes them.
func (q *Queries) GetUserNote(ctx context.Context, arg GetUserNoteParams) (UserNote, error) {
	row := q.db.QueryRow(ctx, getUserNote, arg.AuthorID, arg.SubjectID)
	var i UserNote
	err := row.Scan(
		&i.AuthorID,
		&i.SubjectID,
		&i.Text,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserNote = `-- name: UpsertUserNote :one
INSERT INTO user_notes (author_id, subject_id, text)
VALUES ($1, $2, $3)
ON CONFLICT (author_id, subject_id) DO UPDATE SET text = excluded.text, updated_at = now()
RETURNING author_id, subject_id, text, updated_at
`

type UpsertUserNoteParams struct {
	AuthorID  uuid.UUID
	SubjectID uuid.UUID
	Text      string
}

func (q *Queries) UpsertUserNote(ctx context.Context, arg UpsertUserNoteParams) (UserNote, error) {
	row := q.db.QueryRow(ctx, upsertUserNote, arg.AuthorID, arg.SubjectID, arg.Text)
	var i UserNote
	err := row.Scan(
		&i.AuthorID,
		&i.SubjectID,
		&i.Text,
		&i.UpdatedAt,
	)
	return i, err
}
