// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const bindOAuthRequest = `-- name: BindOAuthRequest :one
UPDATE oauth_authorization_requests SET session_id=$3,user_id=$4,csrf_hash=$5
WHERE id=$1 AND browser_hash=$2 AND session_id IS NULL AND consumed_at IS NULL AND expires_at>now() RETURNING id, workspace_id, client_id, issuer, client_version, handle_hash, browser_hash, csrf_hash, session_id, user_id, redirect_uri, scopes, state, nonce, pkce_challenge, prompt, max_age_seconds, expires_at, consumed_at, created_at
`

type BindOAuthRequestParams struct {
	ID          uuid.UUID
	BrowserHash []byte
	SessionID   *uuid.UUID
	UserID      *uuid.UUID
	CsrfHash    []byte
}

func (q *Queries) BindOAuthRequest(ctx context.Context, arg BindOAuthRequestParams) (OauthAuthorizationRequest, error) {
	row := q.db.QueryRow(ctx, bindOAuthRequest,
		arg.ID,
		arg.BrowserHash,
		arg.SessionID,
		arg.UserID,
		arg.CsrfHash,
	)
	var i OauthAuthorizationRequest
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ClientID,
		&i.Issuer,
		&i.ClientVersion,
		&i.HandleHash,
		&i.BrowserHash,
		&i.CsrfHash,
		&i.SessionID,
		&i.UserID,
		&i.RedirectUri,
		&i.Scopes,
		&i.State,
		&i.Nonce,
		&i.PkceChallenge,
		&i.Prompt,
		&i.MaxAgeSeconds,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const consumeOAuthCode = `-- name: ConsumeOAuthCode :one
UPDATE oauth_authorization_codes AS c SET consumed_at=now()
WHERE c.workspace_id=$1 AND c.client_id=$2 AND c.code_hash=$3 AND c.redirect_uri=$4 AND c.pkce_challenge=$5
AND c.consumed_at IS NULL AND c.expires_at>now()
AND EXISTS(SELECT FROM oauth_grants g WHERE g.id=c.grant_id AND g.revoked_at IS NULL AND g.expires_at>now() AND g.idle_expires_at>now())
RETURNING id, workspace_id, grant_id, user_id, client_id, code_hash, redirect_uri, pkce_challenge, nonce, created_at, expires_at, consumed_at
`

type ConsumeOAuthCodeParams struct {
	WorkspaceID   uuid.UUID
	ClientID      uuid.UUID
	CodeHash      []byte
	RedirectUri   string
	PkceChallenge string
}

func (q *Queries) ConsumeOAuthCode(ctx context.Context, arg ConsumeOAuthCodeParams) (OauthAuthorizationCode, error) {
	row := q.db.QueryRow(ctx, consumeOAuthCode,
		arg.WorkspaceID,
		arg.ClientID,
		arg.CodeHash,
		arg.RedirectUri,
		arg.PkceChallenge,
	)
	var i OauthAuthorizationCode
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.GrantID,
		&i.UserID,
		&i.ClientID,
		&i.CodeHash,
		&i.RedirectUri,
		&i.PkceChallenge,
		&i.Nonce,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const consumeOAuthRefresh = `-- name: ConsumeOAuthRefresh :one
UPDATE oauth_tokens AS t SET used_at=now() WHERE t.workspace_id=$1 AND t.client_id=$2 AND t.token_hash=$3 AND t.token_type='refresh'
AND t.used_at IS NULL AND t.revoked_at IS NULL AND t.expires_at>now()
AND EXISTS(SELECT FROM oauth_grants g WHERE g.id=t.grant_id AND g.revoked_at IS NULL AND g.expires_at>now() AND g.idle_expires_at>now())
RETURNING id, workspace_id, grant_id, user_id, client_id, token_hash, token_type, generation, parent_token_id, created_at, expires_at, used_at, revoked_at
`

type ConsumeOAuthRefreshParams struct {
	WorkspaceID uuid.UUID
	ClientID    uuid.UUID
	TokenHash   []byte
}

func (q *Queries) ConsumeOAuthRefresh(ctx context.Context, arg ConsumeOAuthRefreshParams) (OauthToken, error) {
	row := q.db.QueryRow(ctx, consumeOAuthRefresh, arg.WorkspaceID, arg.ClientID, arg.TokenHash)
	var i OauthToken
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.GrantID,
		&i.UserID,
		&i.ClientID,
		&i.TokenHash,
		&i.TokenType,
		&i.Generation,
		&i.ParentTokenID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const consumeOAuthRequest = `-- name: ConsumeOAuthRequest :one
UPDATE oauth_authorization_requests SET consumed_at=now()
WHERE id=$1 AND browser_hash=$2 AND csrf_hash=$3 AND session_id=$4 AND user_id=$5
AND consumed_at IS NULL AND expires_at>now() RETURNING id, workspace_id, client_id, issuer, client_version, handle_hash, browser_hash, csrf_hash, session_id, user_id, redirect_uri, scopes, state, nonce, pkce_challenge, prompt, max_age_seconds, expires_at, consumed_at, created_at
`

type ConsumeOAuthRequestParams struct {
	ID          uuid.UUID
	BrowserHash []byte
	CsrfHash    []byte
	SessionID   *uuid.UUID
	UserID      *uuid.UUID
}

func (q *Queries) ConsumeOAuthRequest(ctx context.Context, arg ConsumeOAuthRequestParams) (OauthAuthorizationRequest, error) {
	row := q.db.QueryRow(ctx, consumeOAuthRequest,
		arg.ID,
		arg.BrowserHash,
		arg.CsrfHash,
		arg.SessionID,
		arg.UserID,
	)
	var i OauthAuthorizationRequest
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ClientID,
		&i.Issuer,
		&i.ClientVersion,
		&i.HandleHash,
		&i.BrowserHash,
		&i.CsrfHash,
		&i.SessionID,
		&i.UserID,
		&i.RedirectUri,
		&i.Scopes,
		&i.State,
		&i.Nonce,
		&i.PkceChallenge,
		&i.Prompt,
		&i.MaxAgeSeconds,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createOAuthClient = `-- name: CreateOAuthClient :one

INSERT INTO oauth_clients (workspace_id, client_id, name, client_type, refresh_enabled, allowed_origins, auth_method, scopes, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, workspace_id, client_id, name, client_type, refresh_enabled, allowed_origins, auth_method, scopes, version, disabled_at, created_by, created_at
`

type CreateOAuthClientParams struct {
	WorkspaceID    uuid.UUID
	ClientID       string
	Name           string
	ClientType     string
	RefreshEnabled bool
	AllowedOrigins []string
	AuthMethod     string
	Scopes         []string
	CreatedBy      *uuid.UUID
}

// Identity v1 foundation, ADR-0054. Consumer mutations run with audit/outbox in one transaction.
func (q *Queries) CreateOAuthClient(ctx context.Context, arg CreateOAuthClientParams) (OauthClient, error) {
	row := q.db.QueryRow(ctx, createOAuthClient,
		arg.WorkspaceID,
		arg.ClientID,
		arg.Name,
		arg.ClientType,
		arg.RefreshEnabled,
		arg.AllowedOrigins,
		arg.AuthMethod,
		arg.Scopes,
		arg.CreatedBy,
	)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ClientID,
		&i.Name,
		&i.ClientType,
		&i.RefreshEnabled,
		&i.AllowedOrigins,
		&i.AuthMethod,
		&i.Scopes,
		&i.Version,
		&i.DisabledAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createOAuthClientRedirect = `-- name: CreateOAuthClientRedirect :one
INSERT INTO oauth_client_redirects (workspace_id, client_id, redirect_uri)
VALUES ($1, $2, $3)
RETURNING workspace_id, client_id, redirect_uri
`

type CreateOAuthClientRedirectParams struct {
	WorkspaceID uuid.UUID
	ClientID    uuid.UUID
	RedirectUri string
}

func (q *Queries) CreateOAuthClientRedirect(ctx context.Context, arg CreateOAuthClientRedirectParams) (OauthClientRedirect, error) {
	row := q.db.QueryRow(ctx, createOAuthClientRedirect, arg.WorkspaceID, arg.ClientID, arg.RedirectUri)
	var i OauthClientRedirect
	err := row.Scan(&i.WorkspaceID, &i.ClientID, &i.RedirectUri)
	return i, err
}

const createOAuthClientSecret = `-- name: CreateOAuthClientSecret :one
INSERT INTO oauth_client_secrets (workspace_id, client_id, secret_hash, valid_until)
VALUES ($1, $2, $3, $4)
RETURNING id, workspace_id, client_id, secret_hash, created_at, valid_until, revoked_at
`

type CreateOAuthClientSecretParams struct {
	WorkspaceID uuid.UUID
	ClientID    uuid.UUID
	SecretHash  []byte
	ValidUntil  time.Time
}

func (q *Queries) CreateOAuthClientSecret(ctx context.Context, arg CreateOAuthClientSecretParams) (OauthClientSecret, error) {
	row := q.db.QueryRow(ctx, createOAuthClientSecret,
		arg.WorkspaceID,
		arg.ClientID,
		arg.SecretHash,
		arg.ValidUntil,
	)
	var i OauthClientSecret
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ClientID,
		&i.SecretHash,
		&i.CreatedAt,
		&i.ValidUntil,
		&i.RevokedAt,
	)
	return i, err
}

const createOAuthCode = `-- name: CreateOAuthCode :one
INSERT INTO oauth_authorization_codes (workspace_id, grant_id, user_id, client_id, code_hash, redirect_uri, pkce_challenge, nonce, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, workspace_id, grant_id, user_id, client_id, code_hash, redirect_uri, pkce_challenge, nonce, created_at, expires_at, consumed_at
`

type CreateOAuthCodeParams struct {
	WorkspaceID   uuid.UUID
	GrantID       uuid.UUID
	UserID        uuid.UUID
	ClientID      uuid.UUID
	CodeHash      []byte
	RedirectUri   string
	PkceChallenge string
	Nonce         string
	ExpiresAt     time.Time
}

func (q *Queries) CreateOAuthCode(ctx context.Context, arg CreateOAuthCodeParams) (OauthAuthorizationCode, error) {
	row := q.db.QueryRow(ctx, createOAuthCode,
		arg.WorkspaceID,
		arg.GrantID,
		arg.UserID,
		arg.ClientID,
		arg.CodeHash,
		arg.RedirectUri,
		arg.PkceChallenge,
		arg.Nonce,
		arg.ExpiresAt,
	)
	var i OauthAuthorizationCode
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.GrantID,
		&i.UserID,
		&i.ClientID,
		&i.CodeHash,
		&i.RedirectUri,
		&i.PkceChallenge,
		&i.Nonce,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const createOAuthConsent = `-- name: CreateOAuthConsent :one
INSERT INTO oauth_consents (workspace_id, user_id, client_id, scopes, refresh_allowed)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workspace_id, user_id, client_id, scopes, version, refresh_allowed, granted_at, revoked_at
`

type CreateOAuthConsentParams struct {
	WorkspaceID    uuid.UUID
	UserID         uuid.UUID
	ClientID       uuid.UUID
	Scopes         []string
	RefreshAllowed bool
}

func (q *Queries) CreateOAuthConsent(ctx context.Context, arg CreateOAuthConsentParams) (OauthConsent, error) {
	row := q.db.QueryRow(ctx, createOAuthConsent,
		arg.WorkspaceID,
		arg.UserID,
		arg.ClientID,
		arg.Scopes,
		arg.RefreshAllowed,
	)
	var i OauthConsent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.ClientID,
		&i.Scopes,
		&i.Version,
		&i.RefreshAllowed,
		&i.GrantedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createOAuthGrant = `-- name: CreateOAuthGrant :one
INSERT INTO oauth_grants (workspace_id, user_id, client_id, consent_id, session_id, scopes, client_version, consent_version, policy_version, access_version, session_version, authenticated_at, assurance_expires_at, expires_at, idle_expires_at, entitlement_version, issuer)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
RETURNING id, workspace_id, user_id, client_id, consent_id, session_id, scopes, issuer, client_version, consent_version, policy_version, access_version, entitlement_version, session_version, authenticated_at, assurance_expires_at, created_at, expires_at, idle_expires_at, revoked_at, revoked_reason
`

type CreateOAuthGrantParams struct {
	WorkspaceID        uuid.UUID
	UserID             uuid.UUID
	ClientID           uuid.UUID
	ConsentID          uuid.UUID
	SessionID          uuid.UUID
	Scopes             []string
	ClientVersion      int64
	ConsentVersion     int64
	PolicyVersion      int64
	AccessVersion      int64
	SessionVersion     int64
	AuthenticatedAt    time.Time
	AssuranceExpiresAt *time.Time
	ExpiresAt          time.Time
	IdleExpiresAt      time.Time
	EntitlementVersion int64
	Issuer             string
}

func (q *Queries) CreateOAuthGrant(ctx context.Context, arg CreateOAuthGrantParams) (OauthGrant, error) {
	row := q.db.QueryRow(ctx, createOAuthGrant,
		arg.WorkspaceID,
		arg.UserID,
		arg.ClientID,
		arg.ConsentID,
		arg.SessionID,
		arg.Scopes,
		arg.ClientVersion,
		arg.ConsentVersion,
		arg.PolicyVersion,
		arg.AccessVersion,
		arg.SessionVersion,
		arg.AuthenticatedAt,
		arg.AssuranceExpiresAt,
		arg.ExpiresAt,
		arg.IdleExpiresAt,
		arg.EntitlementVersion,
		arg.Issuer,
	)
	var i OauthGrant
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.ClientID,
		&i.ConsentID,
		&i.SessionID,
		&i.Scopes,
		&i.Issuer,
		&i.ClientVersion,
		&i.ConsentVersion,
		&i.PolicyVersion,
		&i.AccessVersion,
		&i.EntitlementVersion,
		&i.SessionVersion,
		&i.AuthenticatedAt,
		&i.AssuranceExpiresAt,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.IdleExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
	)
	return i, err
}

const createOAuthRequest = `-- name: CreateOAuthRequest :one
INSERT INTO oauth_authorization_requests (workspace_id, client_id, client_version, handle_hash, browser_hash, csrf_hash, session_id, user_id, redirect_uri, scopes, state, nonce, pkce_challenge, prompt, max_age_seconds, expires_at, issuer)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
RETURNING id, workspace_id, client_id, issuer, client_version, handle_hash, browser_hash, csrf_hash, session_id, user_id, redirect_uri, scopes, state, nonce, pkce_challenge, prompt, max_age_seconds, expires_at, consumed_at, created_at
`

type CreateOAuthRequestParams struct {
	WorkspaceID   uuid.UUID
	ClientID      uuid.UUID
	ClientVersion int64
	HandleHash    []byte
	BrowserHash   []byte
	CsrfHash      []byte
	SessionID     *uuid.UUID
	UserID        *uuid.UUID
	RedirectUri   string
	Scopes        []string
	State         string
	Nonce         string
	PkceChallenge string
	Prompt        string
	MaxAgeSeconds *int32
	ExpiresAt     time.Time
	Issuer        string
}

func (q *Queries) CreateOAuthRequest(ctx context.Context, arg CreateOAuthRequestParams) (OauthAuthorizationRequest, error) {
	row := q.db.QueryRow(ctx, createOAuthRequest,
		arg.WorkspaceID,
		arg.ClientID,
		arg.ClientVersion,
		arg.HandleHash,
		arg.BrowserHash,
		arg.CsrfHash,
		arg.SessionID,
		arg.UserID,
		arg.RedirectUri,
		arg.Scopes,
		arg.State,
		arg.Nonce,
		arg.PkceChallenge,
		arg.Prompt,
		arg.MaxAgeSeconds,
		arg.ExpiresAt,
		arg.Issuer,
	)
	var i OauthAuthorizationRequest
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ClientID,
		&i.Issuer,
		&i.ClientVersion,
		&i.HandleHash,
		&i.BrowserHash,
		&i.CsrfHash,
		&i.SessionID,
		&i.UserID,
		&i.RedirectUri,
		&i.Scopes,
		&i.State,
		&i.Nonce,
		&i.PkceChallenge,
		&i.Prompt,
		&i.MaxAgeSeconds,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createOAuthSubject = `-- name: CreateOAuthSubject :one
INSERT INTO oauth_subjects (workspace_id, user_id, subject)
VALUES ($1, $2, $3)
RETURNING workspace_id, user_id, subject
`

type CreateOAuthSubjectParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Subject     string
}

func (q *Queries) CreateOAuthSubject(ctx context.Context, arg CreateOAuthSubjectParams) (OauthSubject, error) {
	row := q.db.QueryRow(ctx, createOAuthSubject, arg.WorkspaceID, arg.UserID, arg.Subject)
	var i OauthSubject
	err := row.Scan(&i.WorkspaceID, &i.UserID, &i.Subject)
	return i, err
}

const createOAuthToken = `-- name: CreateOAuthToken :one
INSERT INTO oauth_tokens (workspace_id, grant_id, user_id, client_id, token_hash, token_type, parent_token_id, expires_at, generation)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, workspace_id, grant_id, user_id, client_id, token_hash, token_type, generation, parent_token_id, created_at, expires_at, used_at, revoked_at
`

type CreateOAuthTokenParams struct {
	WorkspaceID   uuid.UUID
	GrantID       uuid.UUID
	UserID        uuid.UUID
	ClientID      uuid.UUID
	TokenHash     []byte
	TokenType     string
	ParentTokenID *uuid.UUID
	ExpiresAt     time.Time
	Generation    int64
}

func (q *Queries) CreateOAuthToken(ctx context.Context, arg CreateOAuthTokenParams) (OauthToken, error) {
	row := q.db.QueryRow(ctx, createOAuthToken,
		arg.WorkspaceID,
		arg.GrantID,
		arg.UserID,
		arg.ClientID,
		arg.TokenHash,
		arg.TokenType,
		arg.ParentTokenID,
		arg.ExpiresAt,
		arg.Generation,
	)
	var i OauthToken
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.GrantID,
		&i.UserID,
		&i.ClientID,
		&i.TokenHash,
		&i.TokenType,
		&i.Generation,
		&i.ParentTokenID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const deleteOAuthClientRedirects = `-- name: DeleteOAuthClientRedirects :execrows
DELETE FROM oauth_client_redirects WHERE workspace_id=$1 AND client_id=$2
`

type DeleteOAuthClientRedirectsParams struct {
	WorkspaceID uuid.UUID
	ClientID    uuid.UUID
}

func (q *Queries) DeleteOAuthClientRedirects(ctx context.Context, arg DeleteOAuthClientRedirectsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOAuthClientRedirects, arg.WorkspaceID, arg.ClientID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const disableOAuthClient = `-- name: DisableOAuthClient :one
UPDATE oauth_clients SET disabled_at=now(),version=version+1 WHERE workspace_id=$1 AND id=$2 RETURNING id, workspace_id, client_id, name, client_type, refresh_enabled, allowed_origins, auth_method, scopes, version, disabled_at, created_by, created_at
`

type DisableOAuthClientParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) DisableOAuthClient(ctx context.Context, arg DisableOAuthClientParams) (OauthClient, error) {
	row := q.db.QueryRow(ctx, disableOAuthClient, arg.WorkspaceID, arg.ID)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ClientID,
		&i.Name,
		&i.ClientType,
		&i.RefreshEnabled,
		&i.AllowedOrigins,
		&i.AuthMethod,
		&i.Scopes,
		&i.Version,
		&i.DisabledAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const expireOAuthClientSecrets = `-- name: ExpireOAuthClientSecrets :execrows
UPDATE oauth_client_secrets SET valid_until=LEAST(valid_until,$3) WHERE workspace_id=$1 AND client_id=$2 AND revoked_at IS NULL
`

type ExpireOAuthClientSecretsParams struct {
	WorkspaceID uuid.UUID
	ClientID    uuid.UUID
	ValidUntil  time.Time
}

func (q *Queries) ExpireOAuthClientSecrets(ctx context.Context, arg ExpireOAuthClientSecretsParams) (int64, error) {
	result, err := q.db.Exec(ctx, expireOAuthClientSecrets, arg.WorkspaceID, arg.ClientID, arg.ValidUntil)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findOAuthClient = `-- name: FindOAuthClient :one
SELECT id, workspace_id, client_id, name, client_type, refresh_enabled, allowed_origins, auth_method, scopes, version, disabled_at, created_by, created_at FROM oauth_clients WHERE workspace_id=$1 AND client_id=$2
`

type FindOAuthClientParams struct {
	WorkspaceID uuid.UUID
	ClientID    string
}

func (q *Queries) FindOAuthClient(ctx context.Context, arg FindOAuthClientParams) (OauthClient, error) {
	row := q.db.QueryRow(ctx, findOAuthClient, arg.WorkspaceID, arg.ClientID)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ClientID,
		&i.Name,
		&i.ClientType,
		&i.RefreshEnabled,
		&i.AllowedOrigins,
		&i.AuthMethod,
		&i.Scopes,
		&i.Version,
		&i.DisabledAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const findOAuthConsent = `-- name: FindOAuthConsent :one
SELECT id, workspace_id, user_id, client_id, scopes, version, refresh_allowed, granted_at, revoked_at FROM oauth_consents WHERE workspace_id=$1 AND user_id=$2 AND client_id=$3
`

type FindOAuthConsentParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	ClientID    uuid.UUID
}

func (q *Queries) FindOAuthConsent(ctx context.Context, arg FindOAuthConsentParams) (OauthConsent, error) {
	row := q.db.QueryRow(ctx, findOAuthConsent, arg.WorkspaceID, arg.UserID, arg.ClientID)
	var i OauthConsent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.ClientID,
		&i.Scopes,
		&i.Version,
		&i.RefreshAllowed,
		&i.GrantedAt,
		&i.RevokedAt,
	)
	return i, err
}

const findOAuthRequest = `-- name: FindOAuthRequest :one
SELECT id, workspace_id, client_id, issuer, client_version, handle_hash, browser_hash, csrf_hash, session_id, user_id, redirect_uri, scopes, state, nonce, pkce_challenge, prompt, max_age_seconds, expires_at, consumed_at, created_at FROM oauth_authorization_requests WHERE handle_hash=$1 AND browser_hash=$2
`

type FindOAuthRequestParams struct {
	HandleHash  []byte
	BrowserHash []byte
}

func (q *Queries) FindOAuthRequest(ctx context.Context, arg FindOAuthRequestParams) (OauthAuthorizationRequest, error) {
	row := q.db.QueryRow(ctx, findOAuthRequest, arg.HandleHash, arg.BrowserHash)
	var i OauthAuthorizationRequest
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ClientID,
		&i.Issuer,
		&i.ClientVersion,
		&i.HandleHash,
		&i.BrowserHash,
		&i.CsrfHash,
		&i.SessionID,
		&i.UserID,
		&i.RedirectUri,
		&i.Scopes,
		&i.State,
		&i.Nonce,
		&i.PkceChallenge,
		&i.Prompt,
		&i.MaxAgeSeconds,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const findOAuthToken = `-- name: FindOAuthToken :one
SELECT id, workspace_id, grant_id, user_id, client_id, token_hash, token_type, generation, parent_token_id, created_at, expires_at, used_at, revoked_at FROM oauth_tokens WHERE workspace_id=$1 AND token_hash=$2 AND token_type=$3
`

type FindOAuthTokenParams struct {
	WorkspaceID uuid.UUID
	TokenHash   []byte
	TokenType   string
}

func (q *Queries) FindOAuthToken(ctx context.Context, arg FindOAuthTokenParams) (OauthToken, error) {
	row := q.db.QueryRow(ctx, findOAuthToken, arg.WorkspaceID, arg.TokenHash, arg.TokenType)
	var i OauthToken
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.GrantID,
		&i.UserID,
		&i.ClientID,
		&i.TokenHash,
		&i.TokenType,
		&i.Generation,
		&i.ParentTokenID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getOAuthClient = `-- name: GetOAuthClient :one
SELECT id, workspace_id, client_id, name, client_type, refresh_enabled, allowed_origins, auth_method, scopes, version, disabled_at, created_by, created_at FROM oauth_clients WHERE workspace_id = $1 AND id = $2
`

type GetOAuthClientParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) GetOAuthClient(ctx context.Context, arg GetOAuthClientParams) (OauthClient, error) {
	row := q.db.QueryRow(ctx, getOAuthClient, arg.WorkspaceID, arg.ID)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ClientID,
		&i.Name,
		&i.ClientType,
		&i.RefreshEnabled,
		&i.AllowedOrigins,
		&i.AuthMethod,
		&i.Scopes,
		&i.Version,
		&i.DisabledAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getOAuthClientForUpdate = `-- name: GetOAuthClientForUpdate :one
SELECT id, workspace_id, client_id, name, client_type, refresh_enabled, allowed_origins, auth_method, scopes, version, disabled_at, created_by, created_at FROM oauth_clients WHERE workspace_id=$1 AND id=$2 FOR UPDATE
`

type GetOAuthClientForUpdateParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) GetOAuthClientForUpdate(ctx context.Context, arg GetOAuthClientForUpdateParams) (OauthClient, error) {
	row := q.db.QueryRow(ctx, getOAuthClientForUpdate, arg.WorkspaceID, arg.ID)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ClientID,
		&i.Name,
		&i.ClientType,
		&i.RefreshEnabled,
		&i.AllowedOrigins,
		&i.AuthMethod,
		&i.Scopes,
		&i.Version,
		&i.DisabledAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getOAuthClientRedirect = `-- name: GetOAuthClientRedirect :one
SELECT workspace_id, client_id, redirect_uri FROM oauth_client_redirects WHERE workspace_id = $1 AND client_id = $2 AND redirect_uri = $3
`

type GetOAuthClientRedirectParams struct {
	WorkspaceID uuid.UUID
	ClientID    uuid.UUID
	RedirectUri string
}

func (q *Queries) GetOAuthClientRedirect(ctx context.Context, arg GetOAuthClientRedirectParams) (OauthClientRedirect, error) {
	row := q.db.QueryRow(ctx, getOAuthClientRedirect, arg.WorkspaceID, arg.ClientID, arg.RedirectUri)
	var i OauthClientRedirect
	err := row.Scan(&i.WorkspaceID, &i.ClientID, &i.RedirectUri)
	return i, err
}

const getOAuthClientSecret = `-- name: GetOAuthClientSecret :one
SELECT id, workspace_id, client_id, secret_hash, created_at, valid_until, revoked_at FROM oauth_client_secrets WHERE workspace_id = $1 AND id = $2
`

type GetOAuthClientSecretParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) GetOAuthClientSecret(ctx context.Context, arg GetOAuthClientSecretParams) (OauthClientSecret, error) {
	row := q.db.QueryRow(ctx, getOAuthClientSecret, arg.WorkspaceID, arg.ID)
	var i OauthClientSecret
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ClientID,
		&i.SecretHash,
		&i.CreatedAt,
		&i.ValidUntil,
		&i.RevokedAt,
	)
	return i, err
}

const getOAuthCode = `-- name: GetOAuthCode :one
SELECT id, workspace_id, grant_id, user_id, client_id, code_hash, redirect_uri, pkce_challenge, nonce, created_at, expires_at, consumed_at FROM oauth_authorization_codes WHERE workspace_id = $1 AND id = $2
`

type GetOAuthCodeParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) GetOAuthCode(ctx context.Context, arg GetOAuthCodeParams) (OauthAuthorizationCode, error) {
	row := q.db.QueryRow(ctx, getOAuthCode, arg.WorkspaceID, arg.ID)
	var i OauthAuthorizationCode
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.GrantID,
		&i.UserID,
		&i.ClientID,
		&i.CodeHash,
		&i.RedirectUri,
		&i.PkceChallenge,
		&i.Nonce,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const getOAuthConsent = `-- name: GetOAuthConsent :one
SELECT id, workspace_id, user_id, client_id, scopes, version, refresh_allowed, granted_at, revoked_at FROM oauth_consents WHERE workspace_id = $1 AND id = $2
`

type GetOAuthConsentParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) GetOAuthConsent(ctx context.Context, arg GetOAuthConsentParams) (OauthConsent, error) {
	row := q.db.QueryRow(ctx, getOAuthConsent, arg.WorkspaceID, arg.ID)
	var i OauthConsent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.ClientID,
		&i.Scopes,
		&i.Version,
		&i.RefreshAllowed,
		&i.GrantedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getOAuthGrant = `-- name: GetOAuthGrant :one
SELECT id, workspace_id, user_id, client_id, consent_id, session_id, scopes, issuer, client_version, consent_version, policy_version, access_version, entitlement_version, session_version, authenticated_at, assurance_expires_at, created_at, expires_at, idle_expires_at, revoked_at, revoked_reason FROM oauth_grants WHERE workspace_id = $1 AND id = $2
`

type GetOAuthGrantParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) GetOAuthGrant(ctx context.Context, arg GetOAuthGrantParams) (OauthGrant, error) {
	row := q.db.QueryRow(ctx, getOAuthGrant, arg.WorkspaceID, arg.ID)
	var i OauthGrant
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.ClientID,
		&i.ConsentID,
		&i.SessionID,
		&i.Scopes,
		&i.Issuer,
		&i.ClientVersion,
		&i.ConsentVersion,
		&i.PolicyVersion,
		&i.AccessVersion,
		&i.EntitlementVersion,
		&i.SessionVersion,
		&i.AuthenticatedAt,
		&i.AssuranceExpiresAt,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.IdleExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
	)
	return i, err
}

const getOAuthGrantForUpdate = `-- name: GetOAuthGrantForUpdate :one
SELECT id, workspace_id, user_id, client_id, consent_id, session_id, scopes, issuer, client_version, consent_version, policy_version, access_version, entitlement_version, session_version, authenticated_at, assurance_expires_at, created_at, expires_at, idle_expires_at, revoked_at, revoked_reason FROM oauth_grants WHERE workspace_id=$1 AND id=$2 AND client_id=$3 FOR UPDATE
`

type GetOAuthGrantForUpdateParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
	ClientID    uuid.UUID
}

func (q *Queries) GetOAuthGrantForUpdate(ctx context.Context, arg GetOAuthGrantForUpdateParams) (OauthGrant, error) {
	row := q.db.QueryRow(ctx, getOAuthGrantForUpdate, arg.WorkspaceID, arg.ID, arg.ClientID)
	var i OauthGrant
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.ClientID,
		&i.ConsentID,
		&i.SessionID,
		&i.Scopes,
		&i.Issuer,
		&i.ClientVersion,
		&i.ConsentVersion,
		&i.PolicyVersion,
		&i.AccessVersion,
		&i.EntitlementVersion,
		&i.SessionVersion,
		&i.AuthenticatedAt,
		&i.AssuranceExpiresAt,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.IdleExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
	)
	return i, err
}

const getOAuthRequest = `-- name: GetOAuthRequest :one
SELECT id, workspace_id, client_id, issuer, client_version, handle_hash, browser_hash, csrf_hash, session_id, user_id, redirect_uri, scopes, state, nonce, pkce_challenge, prompt, max_age_seconds, expires_at, consumed_at, created_at FROM oauth_authorization_requests WHERE workspace_id = $1 AND id = $2
`

type GetOAuthRequestParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) GetOAuthRequest(ctx context.Context, arg GetOAuthRequestParams) (OauthAuthorizationRequest, error) {
	row := q.db.QueryRow(ctx, getOAuthRequest, arg.WorkspaceID, arg.ID)
	var i OauthAuthorizationRequest
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ClientID,
		&i.Issuer,
		&i.ClientVersion,
		&i.HandleHash,
		&i.BrowserHash,
		&i.CsrfHash,
		&i.SessionID,
		&i.UserID,
		&i.RedirectUri,
		&i.Scopes,
		&i.State,
		&i.Nonce,
		&i.PkceChallenge,
		&i.Prompt,
		&i.MaxAgeSeconds,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOAuthSubject = `-- name: GetOAuthSubject :one
SELECT workspace_id, user_id, subject FROM oauth_subjects WHERE workspace_id = $1 AND user_id = $2
`

type GetOAuthSubjectParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) GetOAuthSubject(ctx context.Context, arg GetOAuthSubjectParams) (OauthSubject, error) {
	row := q.db.QueryRow(ctx, getOAuthSubject, arg.WorkspaceID, arg.UserID)
	var i OauthSubject
	err := row.Scan(&i.WorkspaceID, &i.UserID, &i.Subject)
	return i, err
}

const getOAuthToken = `-- name: GetOAuthToken :one
SELECT id, workspace_id, grant_id, user_id, client_id, token_hash, token_type, generation, parent_token_id, created_at, expires_at, used_at, revoked_at FROM oauth_tokens WHERE workspace_id = $1 AND id = $2
`

type GetOAuthTokenParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) GetOAuthToken(ctx context.Context, arg GetOAuthTokenParams) (OauthToken, error) {
	row := q.db.QueryRow(ctx, getOAuthToken, arg.WorkspaceID, arg.ID)
	var i OauthToken
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.GrantID,
		&i.UserID,
		&i.ClientID,
		&i.TokenHash,
		&i.TokenType,
		&i.Generation,
		&i.ParentTokenID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getOAuthTokenForUpdate = `-- name: GetOAuthTokenForUpdate :one
SELECT id, workspace_id, grant_id, user_id, client_id, token_hash, token_type, generation, parent_token_id, created_at, expires_at, used_at, revoked_at FROM oauth_tokens WHERE workspace_id=$1 AND client_id=$2 AND token_hash=$3 AND token_type=$4 FOR UPDATE
`

type GetOAuthTokenForUpdateParams struct {
	WorkspaceID uuid.UUID
	ClientID    uuid.UUID
	TokenHash   []byte
	TokenType   string
}

func (q *Queries) GetOAuthTokenForUpdate(ctx context.Context, arg GetOAuthTokenForUpdateParams) (OauthToken, error) {
	row := q.db.QueryRow(ctx, getOAuthTokenForUpdate,
		arg.WorkspaceID,
		arg.ClientID,
		arg.TokenHash,
		arg.TokenType,
	)
	var i OauthToken
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.GrantID,
		&i.UserID,
		&i.ClientID,
		&i.TokenHash,
		&i.TokenType,
		&i.Generation,
		&i.ParentTokenID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listOAuthClientRedirects = `-- name: ListOAuthClientRedirects :many
SELECT workspace_id, client_id, redirect_uri FROM oauth_client_redirects WHERE workspace_id=$1 AND client_id=$2 ORDER BY redirect_uri
`

type ListOAuthClientRedirectsParams struct {
	WorkspaceID uuid.UUID
	ClientID    uuid.UUID
}

func (q *Queries) ListOAuthClientRedirects(ctx context.Context, arg ListOAuthClientRedirectsParams) ([]OauthClientRedirect, error) {
	rows, err := q.db.Query(ctx, listOAuthClientRedirects, arg.WorkspaceID, arg.ClientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OauthClientRedirect{}
	for rows.Next() {
		var i OauthClientRedirect
		if err := rows.Scan(&i.WorkspaceID, &i.ClientID, &i.RedirectUri); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOAuthClientSecrets = `-- name: ListOAuthClientSecrets :many
SELECT id, workspace_id, client_id, secret_hash, created_at, valid_until, revoked_at FROM oauth_client_secrets WHERE workspace_id=$1 AND client_id=$2 AND revoked_at IS NULL AND valid_until>now() ORDER BY created_at DESC
`

type ListOAuthClientSecretsParams struct {
	WorkspaceID uuid.UUID
	ClientID    uuid.UUID
}

func (q *Queries) ListOAuthClientSecrets(ctx context.Context, arg ListOAuthClientSecretsParams) ([]OauthClientSecret, error) {
	rows, err := q.db.Query(ctx, listOAuthClientSecrets, arg.WorkspaceID, arg.ClientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OauthClientSecret{}
	for rows.Next() {
		var i OauthClientSecret
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ClientID,
			&i.SecretHash,
			&i.CreatedAt,
			&i.ValidUntil,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOAuthClients = `-- name: ListOAuthClients :many
SELECT id, workspace_id, client_id, name, client_type, refresh_enabled, allowed_origins, auth_method, scopes, version, disabled_at, created_by, created_at FROM oauth_clients WHERE workspace_id=$1 ORDER BY created_at
`

func (q *Queries) ListOAuthClients(ctx context.Context, workspaceID uuid.UUID) ([]OauthClient, error) {
	rows, err := q.db.Query(ctx, listOAuthClients, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OauthClient{}
	for rows.Next() {
		var i OauthClient
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ClientID,
			&i.Name,
			&i.ClientType,
			&i.RefreshEnabled,
			&i.AllowedOrigins,
			&i.AuthMethod,
			&i.Scopes,
			&i.Version,
			&i.DisabledAt,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserOAuthGrants = `-- name: ListUserOAuthGrants :many
SELECT id, workspace_id, user_id, client_id, consent_id, session_id, scopes, issuer, client_version, consent_version, policy_version, access_version, entitlement_version, session_version, authenticated_at, assurance_expires_at, created_at, expires_at, idle_expires_at, revoked_at, revoked_reason FROM oauth_grants WHERE user_id=$1 AND ($2::uuid IS NULL OR workspace_id=$2) ORDER BY created_at DESC
`

type ListUserOAuthGrantsParams struct {
	UserID      uuid.UUID
	WorkspaceID *uuid.UUID
}

func (q *Queries) ListUserOAuthGrants(ctx context.Context, arg ListUserOAuthGrantsParams) ([]OauthGrant, error) {
	rows, err := q.db.Query(ctx, listUserOAuthGrants, arg.UserID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OauthGrant{}
	for rows.Next() {
		var i OauthGrant
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.ClientID,
			&i.ConsentID,
			&i.SessionID,
			&i.Scopes,
			&i.Issuer,
			&i.ClientVersion,
			&i.ConsentVersion,
			&i.PolicyVersion,
			&i.AccessVersion,
			&i.EntitlementVersion,
			&i.SessionVersion,
			&i.AuthenticatedAt,
			&i.AssuranceExpiresAt,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.IdleExpiresAt,
			&i.RevokedAt,
			&i.RevokedReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeOAuthClientSecrets = `-- name: RevokeOAuthClientSecrets :execrows
UPDATE oauth_client_secrets SET revoked_at=now() WHERE workspace_id=$1 AND client_id=$2 AND revoked_at IS NULL
`

type RevokeOAuthClientSecretsParams struct {
	WorkspaceID uuid.UUID
	ClientID    uuid.UUID
}

func (q *Queries) RevokeOAuthClientSecrets(ctx context.Context, arg RevokeOAuthClientSecretsParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeOAuthClientSecrets, arg.WorkspaceID, arg.ClientID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeOAuthConsent = `-- name: RevokeOAuthConsent :one
UPDATE oauth_consents SET revoked_at=now(),version=version+1 WHERE workspace_id=$1 AND user_id=$2 AND client_id=$3 RETURNING id, workspace_id, user_id, client_id, scopes, version, refresh_allowed, granted_at, revoked_at
`

type RevokeOAuthConsentParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	ClientID    uuid.UUID
}

func (q *Queries) RevokeOAuthConsent(ctx context.Context, arg RevokeOAuthConsentParams) (OauthConsent, error) {
	row := q.db.QueryRow(ctx, revokeOAuthConsent, arg.WorkspaceID, arg.UserID, arg.ClientID)
	var i OauthConsent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.ClientID,
		&i.Scopes,
		&i.Version,
		&i.RefreshAllowed,
		&i.GrantedAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeOAuthGrant = `-- name: RevokeOAuthGrant :execrows
UPDATE oauth_grants SET revoked_at=now(),revoked_reason=$4 WHERE workspace_id=$1 AND id=$2 AND user_id=$3 AND revoked_at IS NULL
`

type RevokeOAuthGrantParams struct {
	WorkspaceID   uuid.UUID
	ID            uuid.UUID
	UserID        uuid.UUID
	RevokedReason *string
}

func (q *Queries) RevokeOAuthGrant(ctx context.Context, arg RevokeOAuthGrantParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeOAuthGrant,
		arg.WorkspaceID,
		arg.ID,
		arg.UserID,
		arg.RevokedReason,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeOAuthGrantForReplay = `-- name: RevokeOAuthGrantForReplay :one
UPDATE oauth_grants g SET revoked_at=now(),revoked_reason='refresh_reuse'
WHERE g.workspace_id=$1 AND g.client_id=$2 AND g.revoked_at IS NULL
AND EXISTS(SELECT FROM oauth_tokens t WHERE t.grant_id=g.id AND t.client_id=$2 AND t.token_hash=$3 AND t.token_type='refresh' AND t.used_at IS NOT NULL)
RETURNING g.id, g.workspace_id, g.user_id, g.client_id, g.consent_id, g.session_id, g.scopes, g.issuer, g.client_version, g.consent_version, g.policy_version, g.access_version, g.entitlement_version, g.session_version, g.authenticated_at, g.assurance_expires_at, g.created_at, g.expires_at, g.idle_expires_at, g.revoked_at, g.revoked_reason
`

type RevokeOAuthGrantForReplayParams struct {
	WorkspaceID uuid.UUID
	ClientID    uuid.UUID
	TokenHash   []byte
}

func (q *Queries) RevokeOAuthGrantForReplay(ctx context.Context, arg RevokeOAuthGrantForReplayParams) (OauthGrant, error) {
	row := q.db.QueryRow(ctx, revokeOAuthGrantForReplay, arg.WorkspaceID, arg.ClientID, arg.TokenHash)
	var i OauthGrant
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.ClientID,
		&i.ConsentID,
		&i.SessionID,
		&i.Scopes,
		&i.Issuer,
		&i.ClientVersion,
		&i.ConsentVersion,
		&i.PolicyVersion,
		&i.AccessVersion,
		&i.EntitlementVersion,
		&i.SessionVersion,
		&i.AuthenticatedAt,
		&i.AssuranceExpiresAt,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.IdleExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
	)
	return i, err
}

const revokeWorkspaceOAuthGrants = `-- name: RevokeWorkspaceOAuthGrants :execrows
UPDATE oauth_grants SET revoked_at=now(),revoked_reason=$1
WHERE workspace_id=$2 AND revoked_at IS NULL
AND ($3::uuid IS NULL OR user_id=$3)
AND ($4::uuid IS NULL OR session_id=$4)
AND ($5::uuid IS NULL OR client_id=$5)
`

type RevokeWorkspaceOAuthGrantsParams struct {
	Reason      *string
	WorkspaceID uuid.UUID
	UserID      *uuid.UUID
	SessionID   *uuid.UUID
	ClientID    *uuid.UUID
}

func (q *Queries) RevokeWorkspaceOAuthGrants(ctx context.Context, arg RevokeWorkspaceOAuthGrantsParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeWorkspaceOAuthGrants,
		arg.Reason,
		arg.WorkspaceID,
		arg.UserID,
		arg.SessionID,
		arg.ClientID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchOAuthGrant = `-- name: TouchOAuthGrant :one
UPDATE oauth_grants SET idle_expires_at=LEAST(expires_at,now()+interval '30 minutes')
WHERE workspace_id=$1 AND id=$2 AND client_id=$3 AND revoked_at IS NULL AND expires_at>now() AND idle_expires_at>now() RETURNING id, workspace_id, user_id, client_id, consent_id, session_id, scopes, issuer, client_version, consent_version, policy_version, access_version, entitlement_version, session_version, authenticated_at, assurance_expires_at, created_at, expires_at, idle_expires_at, revoked_at, revoked_reason
`

type TouchOAuthGrantParams struct {
	WorkspaceID uuid.UUID
	ID          uuid.UUID
	ClientID    uuid.UUID
}

func (q *Queries) TouchOAuthGrant(ctx context.Context, arg TouchOAuthGrantParams) (OauthGrant, error) {
	row := q.db.QueryRow(ctx, touchOAuthGrant, arg.WorkspaceID, arg.ID, arg.ClientID)
	var i OauthGrant
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.ClientID,
		&i.ConsentID,
		&i.SessionID,
		&i.Scopes,
		&i.Issuer,
		&i.ClientVersion,
		&i.ConsentVersion,
		&i.PolicyVersion,
		&i.AccessVersion,
		&i.EntitlementVersion,
		&i.SessionVersion,
		&i.AuthenticatedAt,
		&i.AssuranceExpiresAt,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.IdleExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
	)
	return i, err
}

const updateOAuthClient = `-- name: UpdateOAuthClient :one
UPDATE oauth_clients SET name=$1,scopes=$2,refresh_enabled=$3,
allowed_origins=$4,version=version+1
WHERE workspace_id=$5 AND id=$6 AND version=$7 RETURNING id, workspace_id, client_id, name, client_type, refresh_enabled, allowed_origins, auth_method, scopes, version, disabled_at, created_by, created_at
`

type UpdateOAuthClientParams struct {
	Name            string
	Scopes          []string
	RefreshEnabled  bool
	AllowedOrigins  []string
	WorkspaceID     uuid.UUID
	ID              uuid.UUID
	ExpectedVersion int64
}

func (q *Queries) UpdateOAuthClient(ctx context.Context, arg UpdateOAuthClientParams) (OauthClient, error) {
	row := q.db.QueryRow(ctx, updateOAuthClient,
		arg.Name,
		arg.Scopes,
		arg.RefreshEnabled,
		arg.AllowedOrigins,
		arg.WorkspaceID,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ClientID,
		&i.Name,
		&i.ClientType,
		&i.RefreshEnabled,
		&i.AllowedOrigins,
		&i.AuthMethod,
		&i.Scopes,
		&i.Version,
		&i.DisabledAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const upsertOAuthConsent = `-- name: UpsertOAuthConsent :one
INSERT INTO oauth_consents(workspace_id,user_id,client_id,scopes,refresh_allowed) VALUES($1,$2,$3,$4,$5)
ON CONFLICT(workspace_id,user_id,client_id) DO UPDATE SET scopes=EXCLUDED.scopes,refresh_allowed=EXCLUDED.refresh_allowed,
version=oauth_consents.version+1,granted_at=now(),revoked_at=NULL RETURNING id, workspace_id, user_id, client_id, scopes, version, refresh_allowed, granted_at, revoked_at
`

type UpsertOAuthConsentParams struct {
	WorkspaceID    uuid.UUID
	UserID         uuid.UUID
	ClientID       uuid.UUID
	Scopes         []string
	RefreshAllowed bool
}

func (q *Queries) UpsertOAuthConsent(ctx context.Context, arg UpsertOAuthConsentParams) (OauthConsent, error) {
	row := q.db.QueryRow(ctx, upsertOAuthConsent,
		arg.WorkspaceID,
		arg.UserID,
		arg.ClientID,
		arg.Scopes,
		arg.RefreshAllowed,
	)
	var i OauthConsent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.ClientID,
		&i.Scopes,
		&i.Version,
		&i.RefreshAllowed,
		&i.GrantedAt,
		&i.RevokedAt,
	)
	return i, err
}

const upsertOAuthSubject = `-- name: UpsertOAuthSubject :one
INSERT INTO oauth_subjects(workspace_id,user_id,subject) VALUES($1,$2,$3)
ON CONFLICT(workspace_id,user_id) DO UPDATE SET subject=oauth_subjects.subject RETURNING workspace_id, user_id, subject
`

type UpsertOAuthSubjectParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Subject     string
}

func (q *Queries) UpsertOAuthSubject(ctx context.Context, arg UpsertOAuthSubjectParams) (OauthSubject, error) {
	row := q.db.QueryRow(ctx, upsertOAuthSubject, arg.WorkspaceID, arg.UserID, arg.Subject)
	var i OauthSubject
	err := row.Scan(&i.WorkspaceID, &i.UserID, &i.Subject)
	return i, err
}
