// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rooms.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const archiveRoom = `-- name: ArchiveRoom :execrows
UPDATE rooms SET archived_at = now() WHERE id = $1 AND archived_at IS NULL
`

func (q *Queries) ArchiveRoom(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, archiveRoom, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearVoiceStatus = `-- name: ClearVoiceStatus :execrows
UPDATE rooms SET voice_status = NULL WHERE id = $1 AND voice_status IS NOT NULL
`

// The call ended: the status goes with it.
func (q *Queries) ClearVoiceStatus(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, clearVoiceStatus, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO room_categories (workspace_id, name, position)
VALUES ($1, $2,
        coalesce($3::integer,
                 (SELECT coalesce(max(position) + 1, 0) FROM room_categories WHERE workspace_id = $1)))
RETURNING id, workspace_id, name, position, created_at
`

type CreateCategoryParams struct {
	WorkspaceID uuid.UUID
	Name        string
	Position    *int32
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (RoomCategory, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.WorkspaceID, arg.Name, arg.Position)
	var i RoomCategory
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (workspace_id, type, name, topic, position, is_private,
                   audio_bitrate_kbps, max_stream_preset, max_streams, category_id, user_limit, camera_limit)
VALUES ($1::uuid, $2, $3, $4,
        coalesce($5::integer,
                 (SELECT coalesce(max(position) + 1, 0) FROM rooms
                  WHERE workspace_id = $1::uuid AND archived_at IS NULL)),
        $6, $7, $8,
        $9, $10, $11, $12)
RETURNING id, workspace_id, type, name, topic, position, is_private, audio_bitrate_kbps, max_stream_preset, max_streams, created_at, archived_at, category_id, user_limit, voice_status, camera_limit, dm_key, allow_recording, restricted, emoji, guest_approval
`

type CreateRoomParams struct {
	WorkspaceID      uuid.UUID
	Type             string
	Name             string
	Topic            string
	Position         *int32
	IsPrivate        bool
	AudioBitrateKbps *int32
	MaxStreamPreset  *string
	MaxStreams       *int32
	CategoryID       *uuid.UUID
	UserLimit        int32
	CameraLimit      *int32
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom,
		arg.WorkspaceID,
		arg.Type,
		arg.Name,
		arg.Topic,
		arg.Position,
		arg.IsPrivate,
		arg.AudioBitrateKbps,
		arg.MaxStreamPreset,
		arg.MaxStreams,
		arg.CategoryID,
		arg.UserLimit,
		arg.CameraLimit,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Type,
		&i.Name,
		&i.Topic,
		&i.Position,
		&i.IsPrivate,
		&i.AudioBitrateKbps,
		&i.MaxStreamPreset,
		&i.MaxStreams,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.CategoryID,
		&i.UserLimit,
		&i.VoiceStatus,
		&i.CameraLimit,
		&i.DmKey,
		&i.AllowRecording,
		&i.Restricted,
		&i.Emoji,
		&i.GuestApproval,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :many
WITH base AS (
    SELECT coalesce(max(r.position) + 1, 0) AS p FROM rooms r
    WHERE r.workspace_id = (SELECT c.workspace_id FROM room_categories c WHERE c.id = $1::uuid)
      AND r.category_id IS NULL AND r.archived_at IS NULL
), ordered AS (
    SELECT r.id, row_number() OVER (ORDER BY r.position, r.name, r.id) - 1 AS n FROM rooms r
    WHERE r.category_id = $1::uuid AND r.archived_at IS NULL
), moved AS (
    UPDATE rooms SET category_id = NULL, position = base.p + ordered.n
    FROM base, ordered
    WHERE rooms.id = ordered.id
    RETURNING rooms.id
), gone AS (
    DELETE FROM room_categories WHERE room_categories.id = $1::uuid
)
SELECT id FROM moved
`

// Deletes a category; returns the rooms that were in it. They move to the top level, after the
// rooms already there, in their order (docs/09 P1 #19): no position ties with top-level rooms.
func (q *Queries) DeleteCategory(ctx context.Context, id uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, deleteCategory, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteRoomOverrides = `-- name: DeleteRoomOverrides :exec
DELETE FROM room_permissions WHERE room_id = $1
`

func (q *Queries) DeleteRoomOverrides(ctx context.Context, roomID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRoomOverrides, roomID)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT id, workspace_id, name, position, created_at FROM room_categories WHERE id = $1
`

func (q *Queries) GetCategory(ctx context.Context, id uuid.UUID) (RoomCategory, error) {
	row := q.db.QueryRow(ctx, getCategory, id)
	var i RoomCategory
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const getRoom = `-- name: GetRoom :one
SELECT id, workspace_id, type, name, topic, position, is_private, audio_bitrate_kbps, max_stream_preset, max_streams, created_at, archived_at, category_id, user_limit, voice_status, camera_limit, dm_key, allow_recording, restricted, emoji, guest_approval FROM rooms WHERE id = $1 AND archived_at IS NULL
`

func (q *Queries) GetRoom(ctx context.Context, id uuid.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, getRoom, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Type,
		&i.Name,
		&i.Topic,
		&i.Position,
		&i.IsPrivate,
		&i.AudioBitrateKbps,
		&i.MaxStreamPreset,
		&i.MaxStreams,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.CategoryID,
		&i.UserLimit,
		&i.VoiceStatus,
		&i.CameraLimit,
		&i.DmKey,
		&i.AllowRecording,
		&i.Restricted,
		&i.Emoji,
		&i.GuestApproval,
	)
	return i, err
}

const getRoomAccess = `-- name: GetRoomAccess :one
SELECT r.workspace_id,
       r.type,
       r.restricted,
       m.role,
       coalesce(mr.ids, '{}')::uuid[] AS role_ids,
       coalesce(mr.positions, '{}')::integer[] AS role_positions,
       coalesce(mr.perms, '{}')::bigint[] AS role_permissions,
       coalesce(mr.allows, '{}')::bigint[] AS role_allows,
       coalesce(mr.denies, '{}')::bigint[] AS role_denies,
       uo.allow AS user_allow, uo.deny AS user_deny,
       (CASE WHEN r.type IN ('dm', 'notes') THEN ARRAY(SELECT d.user_id FROM dm_members d WHERE d.room_id = r.id ORDER BY d.user_id)
             ELSE '{}'::uuid[] END)::uuid[] AS dm_members,
       (w.suspended_at IS NOT NULL)::boolean AS suspended
FROM rooms r
LEFT JOIN workspaces w ON w.id = r.workspace_id
LEFT JOIN workspace_members m ON m.workspace_id = r.workspace_id AND m.user_id = $1
LEFT JOIN LATERAL (
    SELECT array_agg(wr.id ORDER BY wr.position) AS ids,
           array_agg(wr.position ORDER BY wr.position) AS positions,
           array_agg(wr.permissions ORDER BY wr.position) AS perms,
           array_agg(coalesce(ro.allow, 0) ORDER BY wr.position) AS allows,
           array_agg(coalesce(ro.deny, 0) ORDER BY wr.position) AS denies
    FROM member_roles x
    JOIN workspace_roles wr ON wr.id = x.role_id
    LEFT JOIN room_permissions ro ON ro.room_id = r.id AND ro.target_type = 'role' AND ro.target_id = wr.id::text
    WHERE x.workspace_id = m.workspace_id AND x.user_id = m.user_id
) mr ON true
LEFT JOIN room_permissions uo ON uo.room_id = r.id AND uo.target_type = 'user' AND uo.target_id = $1::text
WHERE r.id = $2 AND r.archived_at IS NULL
`

type GetRoomAccessParams struct {
	UserID uuid.UUID
	RoomID uuid.UUID
}

type GetRoomAccessRow struct {
	WorkspaceID     *uuid.UUID
	Type            string
	Restricted      bool
	Role            *string
	RoleIds         []uuid.UUID
	RolePositions   []int32
	RolePermissions []int64
	RoleAllows      []int64
	RoleDenies      []int64
	UserAllow       *int64
	UserDeny        *int64
	DmMembers       []uuid.UUID
	Suspended       bool
}

// Everything needed to compute a user's permissions in a room, in one round trip. Workspace
// rooms: the membership (role NULL = not a member), the member's roles lowest position first
// (ADR-0026) with each role's override in this room (0/0 = none) and the user override. DMs
// and notes shelves (workspace_id NULL): the participants (a shelf: its owner). suspended: the workspace is suspended (item 32).
// restricted: ADMINISTRATOR gives no bypass in the room (ADR-0029).
func (q *Queries) GetRoomAccess(ctx context.Context, arg GetRoomAccessParams) (GetRoomAccessRow, error) {
	row := q.db.QueryRow(ctx, getRoomAccess, arg.UserID, arg.RoomID)
	var i GetRoomAccessRow
	err := row.Scan(
		&i.WorkspaceID,
		&i.Type,
		&i.Restricted,
		&i.Role,
		&i.RoleIds,
		&i.RolePositions,
		&i.RolePermissions,
		&i.RoleAllows,
		&i.RoleDenies,
		&i.UserAllow,
		&i.UserDeny,
		&i.DmMembers,
		&i.Suspended,
	)
	return i, err
}

const getRoomForUpdate = `-- name: GetRoomForUpdate :one
SELECT id, workspace_id, type, name, topic, position, is_private, audio_bitrate_kbps, max_stream_preset, max_streams, created_at, archived_at, category_id, user_limit, voice_status, camera_limit, dm_key, allow_recording, restricted, emoji, guest_approval FROM rooms WHERE id = $1 AND archived_at IS NULL FOR UPDATE
`

// The live room, locked for the rest of the transaction (PATCH restricted, ADR-0029).
func (q *Queries) GetRoomForUpdate(ctx context.Context, id uuid.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomForUpdate, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Type,
		&i.Name,
		&i.Topic,
		&i.Position,
		&i.IsPrivate,
		&i.AudioBitrateKbps,
		&i.MaxStreamPreset,
		&i.MaxStreams,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.CategoryID,
		&i.UserLimit,
		&i.VoiceStatus,
		&i.CameraLimit,
		&i.DmKey,
		&i.AllowRecording,
		&i.Restricted,
		&i.Emoji,
		&i.GuestApproval,
	)
	return i, err
}

const insertRoomOverride = `-- name: InsertRoomOverride :exec
INSERT INTO room_permissions (room_id, target_type, target_id, allow, deny)
VALUES ($1, $2, $3, $4, $5)
`

type InsertRoomOverrideParams struct {
	RoomID     uuid.UUID
	TargetType string
	TargetID   string
	Allow      int64
	Deny       int64
}

func (q *Queries) InsertRoomOverride(ctx context.Context, arg InsertRoomOverrideParams) error {
	_, err := q.db.Exec(ctx, insertRoomOverride,
		arg.RoomID,
		arg.TargetType,
		arg.TargetID,
		arg.Allow,
		arg.Deny,
	)
	return err
}

const listCategories = `-- name: ListCategories :many
SELECT id, workspace_id, name, position, created_at FROM room_categories WHERE workspace_id = $1 ORDER BY position, id
`

func (q *Queries) ListCategories(ctx context.Context, workspaceID uuid.UUID) ([]RoomCategory, error) {
	rows, err := q.db.Query(ctx, listCategories, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoomCategory{}
	for rows.Next() {
		var i RoomCategory
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomOverrides = `-- name: ListRoomOverrides :many
SELECT room_id, target_type, target_id, allow, deny FROM room_permissions WHERE room_id = $1 ORDER BY target_type, target_id
`

func (q *Queries) ListRoomOverrides(ctx context.Context, roomID uuid.UUID) ([]RoomPermission, error) {
	rows, err := q.db.Query(ctx, listRoomOverrides, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoomPermission{}
	for rows.Next() {
		var i RoomPermission
		if err := rows.Scan(
			&i.RoomID,
			&i.TargetType,
			&i.TargetID,
			&i.Allow,
			&i.Deny,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRooms = `-- name: ListRooms :many
SELECT id, workspace_id, type, name, topic, position, is_private, audio_bitrate_kbps, max_stream_preset, max_streams, created_at, archived_at, category_id, user_limit, voice_status, camera_limit, dm_key, allow_recording, restricted, emoji, guest_approval FROM rooms
WHERE workspace_id = $1::uuid AND archived_at IS NULL
ORDER BY position, id
`

func (q *Queries) ListRooms(ctx context.Context, workspaceID uuid.UUID) ([]Room, error) {
	rows, err := q.db.Query(ctx, listRooms, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Type,
			&i.Name,
			&i.Topic,
			&i.Position,
			&i.IsPrivate,
			&i.AudioBitrateKbps,
			&i.MaxStreamPreset,
			&i.MaxStreams,
			&i.CreatedAt,
			&i.ArchivedAt,
			&i.CategoryID,
			&i.UserLimit,
			&i.VoiceStatus,
			&i.CameraLimit,
			&i.DmKey,
			&i.AllowRecording,
			&i.Restricted,
			&i.Emoji,
			&i.GuestApproval,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceRoomOverrides = `-- name: ListWorkspaceRoomOverrides :many
SELECT rp.room_id, rp.target_type, rp.target_id, rp.allow, rp.deny FROM room_permissions rp
JOIN rooms r ON r.id = rp.room_id
WHERE r.workspace_id = $1::uuid AND r.archived_at IS NULL
ORDER BY rp.room_id, rp.target_type, rp.target_id
`

func (q *Queries) ListWorkspaceRoomOverrides(ctx context.Context, workspaceID uuid.UUID) ([]RoomPermission, error) {
	rows, err := q.db.Query(ctx, listWorkspaceRoomOverrides, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoomPermission{}
	for rows.Next() {
		var i RoomPermission
		if err := rows.Scan(
			&i.RoomID,
			&i.TargetType,
			&i.TargetID,
			&i.Allow,
			&i.Deny,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCategoryPosition = `-- name: SetCategoryPosition :one
UPDATE room_categories SET position = $1
WHERE id = $2 AND workspace_id = $3
RETURNING id, workspace_id, name, position, created_at
`

type SetCategoryPositionParams struct {
	Position    int32
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) SetCategoryPosition(ctx context.Context, arg SetCategoryPositionParams) (RoomCategory, error) {
	row := q.db.QueryRow(ctx, setCategoryPosition, arg.Position, arg.ID, arg.WorkspaceID)
	var i RoomCategory
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const setRoomPlacement = `-- name: SetRoomPlacement :one
UPDATE rooms SET position = $1, category_id = $2
WHERE id = $3 AND workspace_id = $4::uuid AND archived_at IS NULL
RETURNING id, workspace_id, type, name, topic, position, is_private, audio_bitrate_kbps, max_stream_preset, max_streams, created_at, archived_at, category_id, user_limit, voice_status, camera_limit, dm_key, allow_recording, restricted, emoji, guest_approval
`

type SetRoomPlacementParams struct {
	Position    int32
	CategoryID  *uuid.UUID
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) SetRoomPlacement(ctx context.Context, arg SetRoomPlacementParams) (Room, error) {
	row := q.db.QueryRow(ctx, setRoomPlacement,
		arg.Position,
		arg.CategoryID,
		arg.ID,
		arg.WorkspaceID,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Type,
		&i.Name,
		&i.Topic,
		&i.Position,
		&i.IsPrivate,
		&i.AudioBitrateKbps,
		&i.MaxStreamPreset,
		&i.MaxStreams,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.CategoryID,
		&i.UserLimit,
		&i.VoiceStatus,
		&i.CameraLimit,
		&i.DmKey,
		&i.AllowRecording,
		&i.Restricted,
		&i.Emoji,
		&i.GuestApproval,
	)
	return i, err
}

const setVoiceStatus = `-- name: SetVoiceStatus :one
UPDATE rooms SET voice_status = $1 WHERE id = $2 AND archived_at IS NULL
RETURNING id, workspace_id, type, name, topic, position, is_private, audio_bitrate_kbps, max_stream_preset, max_streams, created_at, archived_at, category_id, user_limit, voice_status, camera_limit, dm_key, allow_recording, restricted, emoji, guest_approval
`

type SetVoiceStatusParams struct {
	Status *string
	ID     uuid.UUID
}

func (q *Queries) SetVoiceStatus(ctx context.Context, arg SetVoiceStatusParams) (Room, error) {
	row := q.db.QueryRow(ctx, setVoiceStatus, arg.Status, arg.ID)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Type,
		&i.Name,
		&i.Topic,
		&i.Position,
		&i.IsPrivate,
		&i.AudioBitrateKbps,
		&i.MaxStreamPreset,
		&i.MaxStreams,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.CategoryID,
		&i.UserLimit,
		&i.VoiceStatus,
		&i.CameraLimit,
		&i.DmKey,
		&i.AllowRecording,
		&i.Restricted,
		&i.Emoji,
		&i.GuestApproval,
	)
	return i, err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE room_categories SET
    name     = coalesce($1, name),
    position = coalesce($2, position)
WHERE id = $3
RETURNING id, workspace_id, name, position, created_at
`

type UpdateCategoryParams struct {
	Name     *string
	Position *int32
	ID       uuid.UUID
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (RoomCategory, error) {
	row := q.db.QueryRow(ctx, updateCategory, arg.Name, arg.Position, arg.ID)
	var i RoomCategory
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const updateRoom = `-- name: UpdateRoom :one
UPDATE rooms SET
    name     = coalesce($1, name),
    topic    = coalesce($2, topic),
    position = coalesce($3, position),
    user_limit = coalesce($4, user_limit),
    allow_recording = coalesce($5, allow_recording),
    restricted = coalesce($6, restricted),
    guest_approval = coalesce($7, guest_approval),
    audio_bitrate_kbps = CASE WHEN $8::boolean THEN $9::integer ELSE audio_bitrate_kbps END,
    max_stream_preset  = CASE WHEN $8::boolean THEN $10::text ELSE max_stream_preset END,
    max_streams        = CASE WHEN $8::boolean THEN $11::integer ELSE max_streams END,
    camera_limit       = CASE WHEN $8::boolean THEN $12::integer ELSE camera_limit END,
    category_id        = CASE WHEN $13::boolean THEN $14::uuid ELSE category_id END
WHERE id = $15 AND archived_at IS NULL
RETURNING id, workspace_id, type, name, topic, position, is_private, audio_bitrate_kbps, max_stream_preset, max_streams, created_at, archived_at, category_id, user_limit, voice_status, camera_limit, dm_key, allow_recording, restricted, emoji, guest_approval
`

type UpdateRoomParams struct {
	Name             *string
	Topic            *string
	Position         *int32
	UserLimit        *int32
	AllowRecording   *bool
	Restricted       *bool
	GuestApproval    *bool
	SetMedia         bool
	AudioBitrateKbps *int32
	MaxStreamPreset  *string
	MaxStreams       *int32
	CameraLimit      *int32
	SetCategory      bool
	CategoryID       *uuid.UUID
	ID               uuid.UUID
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, updateRoom,
		arg.Name,
		arg.Topic,
		arg.Position,
		arg.UserLimit,
		arg.AllowRecording,
		arg.Restricted,
		arg.GuestApproval,
		arg.SetMedia,
		arg.AudioBitrateKbps,
		arg.MaxStreamPreset,
		arg.MaxStreams,
		arg.CameraLimit,
		arg.SetCategory,
		arg.CategoryID,
		arg.ID,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Type,
		&i.Name,
		&i.Topic,
		&i.Position,
		&i.IsPrivate,
		&i.AudioBitrateKbps,
		&i.MaxStreamPreset,
		&i.MaxStreams,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.CategoryID,
		&i.UserLimit,
		&i.VoiceStatus,
		&i.CameraLimit,
		&i.DmKey,
		&i.AllowRecording,
		&i.Restricted,
		&i.Emoji,
		&i.GuestApproval,
	)
	return i, err
}
