// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shelves.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countNotes = `-- name: CountNotes :one
SELECT count(*)::integer FROM dm_members d
JOIN rooms r ON r.id = d.room_id AND r.type = 'notes' AND r.archived_at IS NULL
WHERE d.user_id = $1
`

func (q *Queries) CountNotes(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countNotes, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createNotesRoom = `-- name: CreateNotesRoom :one
INSERT INTO rooms (workspace_id, type, name, emoji, position)
VALUES (NULL, 'notes', $1, $2,
        (SELECT coalesce(max(r.position) + 1, 0) FROM dm_members d
         JOIN rooms r ON r.id = d.room_id AND r.type = 'notes'
         WHERE d.user_id = $3))
RETURNING id, workspace_id, type, name, topic, position, is_private, audio_bitrate_kbps, max_stream_preset, max_streams, created_at, archived_at, category_id, user_limit, voice_status, camera_limit, dm_key, allow_recording, restricted, emoji
`

type CreateNotesRoomParams struct {
	Name   string
	Emoji  string
	UserID uuid.UUID
}

// A new shelf goes last among the user's shelves.
func (q *Queries) CreateNotesRoom(ctx context.Context, arg CreateNotesRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createNotesRoom, arg.Name, arg.Emoji, arg.UserID)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Type,
		&i.Name,
		&i.Topic,
		&i.Position,
		&i.IsPrivate,
		&i.AudioBitrateKbps,
		&i.MaxStreamPreset,
		&i.MaxStreams,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.CategoryID,
		&i.UserLimit,
		&i.VoiceStatus,
		&i.CameraLimit,
		&i.DmKey,
		&i.AllowRecording,
		&i.Restricted,
		&i.Emoji,
	)
	return i, err
}

const deleteNotesRoom = `-- name: DeleteNotesRoom :execrows
DELETE FROM rooms WHERE id = $1 AND type = 'notes'
`

// Messages, reactions, pins, read state and membership go by cascade; the shelf's own uploads
// become orphans for the file cleanup.
func (q *Queries) DeleteNotesRoom(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNotesRoom, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getNotesRoom = `-- name: GetNotesRoom :one
SELECT r.id, r.workspace_id, r.type, r.name, r.topic, r.position, r.is_private, r.audio_bitrate_kbps, r.max_stream_preset, r.max_streams, r.created_at, r.archived_at, r.category_id, r.user_limit, r.voice_status, r.camera_limit, r.dm_key, r.allow_recording, r.restricted, r.emoji FROM rooms r
JOIN dm_members d ON d.room_id = r.id AND d.user_id = $1
WHERE r.id = $2 AND r.type = 'notes' AND r.archived_at IS NULL
`

type GetNotesRoomParams struct {
	UserID uuid.UUID
	RoomID uuid.UUID
}

// The user's shelf (no row = not theirs, not a shelf, or gone).
func (q *Queries) GetNotesRoom(ctx context.Context, arg GetNotesRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, getNotesRoom, arg.UserID, arg.RoomID)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Type,
		&i.Name,
		&i.Topic,
		&i.Position,
		&i.IsPrivate,
		&i.AudioBitrateKbps,
		&i.MaxStreamPreset,
		&i.MaxStreams,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.CategoryID,
		&i.UserLimit,
		&i.VoiceStatus,
		&i.CameraLimit,
		&i.DmKey,
		&i.AllowRecording,
		&i.Restricted,
		&i.Emoji,
	)
	return i, err
}

const listNotes = `-- name: ListNotes :many
SELECT r.id, r.workspace_id, r.type, r.name, r.topic, r.position, r.is_private, r.audio_bitrate_kbps, r.max_stream_preset, r.max_streams, r.created_at, r.archived_at, r.category_id, r.user_limit, r.voice_status, r.camera_limit, r.dm_key, r.allow_recording, r.restricted, r.emoji,
       (lm.id IS NOT NULL)::boolean AS has_messages,
       coalesce(lm.id, r.id)::uuid AS last_message_id,
       coalesce(lm.created_at, r.created_at)::timestamptz AS last_message_at,
       coalesce(lm.author_id, d.user_id)::uuid AS last_author_id,
       coalesce(lm.preview, '')::text AS last_preview,
       coalesce(lm.attachments, 0)::integer AS last_attachments,
       coalesce(lm.sticker_emoji, '')::text AS last_sticker_emoji
FROM dm_members d
JOIN rooms r ON r.id = d.room_id AND r.type = 'notes' AND r.archived_at IS NULL
LEFT JOIN LATERAL (
    SELECT m.id, m.created_at, m.author_id, left(m.content, 200) AS preview,
           (SELECT count(*) FROM message_attachments ma WHERE ma.message_id = m.id) AS attachments,
           (SELECT st.emoji FROM stickers st WHERE st.id = m.sticker_id) AS sticker_emoji
    FROM messages m
    WHERE m.room_id = r.id AND m.deleted_at IS NULL
    ORDER BY m.id DESC
    LIMIT 1
) lm ON true
WHERE d.user_id = $1
  AND ($2::uuid IS NULL OR r.id = $2::uuid)
ORDER BY r.position, r.id
`

type ListNotesParams struct {
	UserID uuid.UUID
	RoomID *uuid.UUID
}

type ListNotesRow struct {
	Room             Room
	HasMessages      bool
	LastMessageID    uuid.UUID
	LastMessageAt    time.Time
	LastAuthorID     uuid.UUID
	LastPreview      string
	LastAttachments  int32
	LastStickerEmoji string
}

// The user's shelves by position with the newest live message as the list preview (as
// ListDMs: author, first 200 characters, attachment and sticker). room_id NULL = all.
func (q *Queries) ListNotes(ctx context.Context, arg ListNotesParams) ([]ListNotesRow, error) {
	rows, err := q.db.Query(ctx, listNotes, arg.UserID, arg.RoomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotesRow{}
	for rows.Next() {
		var i ListNotesRow
		if err := rows.Scan(
			&i.Room.ID,
			&i.Room.WorkspaceID,
			&i.Room.Type,
			&i.Room.Name,
			&i.Room.Topic,
			&i.Room.Position,
			&i.Room.IsPrivate,
			&i.Room.AudioBitrateKbps,
			&i.Room.MaxStreamPreset,
			&i.Room.MaxStreams,
			&i.Room.CreatedAt,
			&i.Room.ArchivedAt,
			&i.Room.CategoryID,
			&i.Room.UserLimit,
			&i.Room.VoiceStatus,
			&i.Room.CameraLimit,
			&i.Room.DmKey,
			&i.Room.AllowRecording,
			&i.Room.Restricted,
			&i.Room.Emoji,
			&i.HasMessages,
			&i.LastMessageID,
			&i.LastMessageAt,
			&i.LastAuthorID,
			&i.LastPreview,
			&i.LastAttachments,
			&i.LastStickerEmoji,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockNotes = `-- name: LockNotes :exec

SELECT pg_advisory_xact_lock(hashtext('calaba.notes:' || $1::uuid::text))
`

// Notes shelves (ADR-0039). A shelf is a room with type 'notes', no workspace and exactly one
// row in dm_members: its owner. (user_notes in notes.sql are private notes about people.)
// Serializes a user's shelf creations (the per-user cap) and reorders.
func (q *Queries) LockNotes(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockNotes, userID)
	return err
}

const personalStorageBytes = `-- name: PersonalStorageBytes :one
SELECT coalesce(sum(f.size), 0)::bigint FROM files f
WHERE f.uploader_id = $1 AND f.workspace_id IS NULL
  AND NOT EXISTS (SELECT 1 FROM users u WHERE u.avatar_file_id = f.id)
  AND (NOT EXISTS (SELECT 1 FROM message_attachments ma WHERE ma.file_id = f.id)
       OR EXISTS (SELECT 1 FROM message_attachments ma
                  JOIN messages m ON m.id = ma.message_id AND m.deleted_at IS NULL
                  JOIN rooms r ON r.id = m.room_id AND r.type = 'notes'
                  WHERE ma.file_id = f.id))
`

// The user's personal quota usage (ADR-0039 §5): their user-scoped uploads (no workspace, not
// the avatar) that are not attached yet or are attached to a live message of a shelf.
func (q *Queries) PersonalStorageBytes(ctx context.Context, uploaderID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, personalStorageBytes, uploaderID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const setUserStorageQuota = `-- name: SetUserStorageQuota :one
UPDATE users SET storage_quota_bytes = $1 WHERE id = $2
RETURNING storage_quota_bytes
`

type SetUserStorageQuotaParams struct {
	Quota *int64
	ID    uuid.UUID
}

// Superadmin: the user's personal quota (NULL = the server default).
func (q *Queries) SetUserStorageQuota(ctx context.Context, arg SetUserStorageQuotaParams) (*int64, error) {
	row := q.db.QueryRow(ctx, setUserStorageQuota, arg.Quota, arg.ID)
	var storage_quota_bytes *int64
	err := row.Scan(&storage_quota_bytes)
	return storage_quota_bytes, err
}

const updateNotesRoom = `-- name: UpdateNotesRoom :one
UPDATE rooms SET
    name     = coalesce($1, name),
    emoji    = coalesce($2, emoji),
    position = coalesce($3, position)
WHERE id = $4 AND type = 'notes'
RETURNING id, workspace_id, type, name, topic, position, is_private, audio_bitrate_kbps, max_stream_preset, max_streams, created_at, archived_at, category_id, user_limit, voice_status, camera_limit, dm_key, allow_recording, restricted, emoji
`

type UpdateNotesRoomParams struct {
	Name     *string
	Emoji    *string
	Position *int32
	ID       uuid.UUID
}

func (q *Queries) UpdateNotesRoom(ctx context.Context, arg UpdateNotesRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, updateNotesRoom,
		arg.Name,
		arg.Emoji,
		arg.Position,
		arg.ID,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Type,
		&i.Name,
		&i.Topic,
		&i.Position,
		&i.IsPrivate,
		&i.AudioBitrateKbps,
		&i.MaxStreamPreset,
		&i.MaxStreams,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.CategoryID,
		&i.UserLimit,
		&i.VoiceStatus,
		&i.CameraLimit,
		&i.DmKey,
		&i.AllowRecording,
		&i.Restricted,
		&i.Emoji,
	)
	return i, err
}
