// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sounds.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countWorkspaceSounds = `-- name: CountWorkspaceSounds :one
SELECT count(*)::integer FROM workspace_sounds WHERE workspace_id = $1
`

func (q *Queries) CountWorkspaceSounds(ctx context.Context, workspaceID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countWorkspaceSounds, workspaceID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteWorkspaceSound = `-- name: DeleteWorkspaceSound :execrows
DELETE FROM workspace_sounds WHERE id = $1 AND workspace_id = $2
`

type DeleteWorkspaceSoundParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) DeleteWorkspaceSound(ctx context.Context, arg DeleteWorkspaceSoundParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWorkspaceSound, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWorkspaceSound = `-- name: GetWorkspaceSound :one
SELECT id, workspace_id, name, emoji, file_id, duration_ms, position, created_at FROM workspace_sounds WHERE id = $1 AND workspace_id = $2
`

type GetWorkspaceSoundParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) GetWorkspaceSound(ctx context.Context, arg GetWorkspaceSoundParams) (WorkspaceSound, error) {
	row := q.db.QueryRow(ctx, getWorkspaceSound, arg.ID, arg.WorkspaceID)
	var i WorkspaceSound
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Emoji,
		&i.FileID,
		&i.DurationMs,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const insertWorkspaceSound = `-- name: InsertWorkspaceSound :one
INSERT INTO workspace_sounds (workspace_id, name, emoji, file_id, duration_ms, position)
VALUES ($1, $2, $3, $4, $5, (SELECT coalesce(max(s.position), -1) + 1 FROM workspace_sounds s WHERE s.workspace_id = $1)::smallint)
RETURNING id, workspace_id, name, emoji, file_id, duration_ms, position, created_at
`

type InsertWorkspaceSoundParams struct {
	WorkspaceID uuid.UUID
	Name        string
	Emoji       string
	FileID      uuid.UUID
	DurationMs  int32
}

func (q *Queries) InsertWorkspaceSound(ctx context.Context, arg InsertWorkspaceSoundParams) (WorkspaceSound, error) {
	row := q.db.QueryRow(ctx, insertWorkspaceSound,
		arg.WorkspaceID,
		arg.Name,
		arg.Emoji,
		arg.FileID,
		arg.DurationMs,
	)
	var i WorkspaceSound
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Emoji,
		&i.FileID,
		&i.DurationMs,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const isWorkspaceSound = `-- name: IsWorkspaceSound :one
SELECT EXISTS (SELECT 1 FROM workspace_sounds WHERE file_id = $1)::boolean
`

// The file is the clip of a sound (files.CanRead: members of its workspace).
func (q *Queries) IsWorkspaceSound(ctx context.Context, fileID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isWorkspaceSound, fileID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listWorkspaceSounds = `-- name: ListWorkspaceSounds :many
SELECT id, workspace_id, name, emoji, file_id, duration_ms, position, created_at FROM workspace_sounds WHERE workspace_id = $1 ORDER BY position, id
`

func (q *Queries) ListWorkspaceSounds(ctx context.Context, workspaceID uuid.UUID) ([]WorkspaceSound, error) {
	rows, err := q.db.Query(ctx, listWorkspaceSounds, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceSound{}
	for rows.Next() {
		var i WorkspaceSound
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Emoji,
			&i.FileID,
			&i.DurationMs,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockWorkspaceSounds = `-- name: LockWorkspaceSounds :exec

SELECT pg_advisory_xact_lock(hashtext('calaba.sounds.' || $1::uuid::text))
`

// Soundboard of a workspace (ADR-0036).
// Serializes changes of one workspace's library (count + insert, reorder).
func (q *Queries) LockWorkspaceSounds(ctx context.Context, workspaceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockWorkspaceSounds, workspaceID)
	return err
}

const setWorkspaceSoundPosition = `-- name: SetWorkspaceSoundPosition :exec
UPDATE workspace_sounds SET position = $3 WHERE id = $1 AND workspace_id = $2
`

type SetWorkspaceSoundPositionParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Position    int16
}

func (q *Queries) SetWorkspaceSoundPosition(ctx context.Context, arg SetWorkspaceSoundPositionParams) error {
	_, err := q.db.Exec(ctx, setWorkspaceSoundPosition, arg.ID, arg.WorkspaceID, arg.Position)
	return err
}

const updateWorkspaceSound = `-- name: UpdateWorkspaceSound :one
UPDATE workspace_sounds SET name = $3, emoji = $4, file_id = $5, duration_ms = $6
WHERE id = $1 AND workspace_id = $2
RETURNING id, workspace_id, name, emoji, file_id, duration_ms, position, created_at
`

type UpdateWorkspaceSoundParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	Emoji       string
	FileID      uuid.UUID
	DurationMs  int32
}

func (q *Queries) UpdateWorkspaceSound(ctx context.Context, arg UpdateWorkspaceSoundParams) (WorkspaceSound, error) {
	row := q.db.QueryRow(ctx, updateWorkspaceSound,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Emoji,
		arg.FileID,
		arg.DurationMs,
	)
	var i WorkspaceSound
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Emoji,
		&i.FileID,
		&i.DurationMs,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}
