// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stickers.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countNonGuestMembers = `-- name: CountNonGuestMembers :one
SELECT count(*)::integer FROM workspace_members
WHERE workspace_id = $1 AND user_id = ANY($2::uuid[]) AND role <> 'guest'
`

type CountNonGuestMembersParams struct {
	WorkspaceID uuid.UUID
	UserIds     []uuid.UUID
}

// How many of the users are members of the workspace with a role other than guest.
func (q *Queries) CountNonGuestMembers(ctx context.Context, arg CountNonGuestMembersParams) (int32, error) {
	row := q.db.QueryRow(ctx, countNonGuestMembers, arg.WorkspaceID, arg.UserIds)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countPackStickers = `-- name: CountPackStickers :one
SELECT count(*)::integer FROM stickers WHERE pack_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountPackStickers(ctx context.Context, packID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countPackStickers, packID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countUserStickerPacks = `-- name: CountUserStickerPacks :one
SELECT count(*)::integer FROM user_sticker_packs WHERE user_id = $1
`

func (q *Queries) CountUserStickerPacks(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countUserStickerPacks, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countWorkspaceStickerPacks = `-- name: CountWorkspaceStickerPacks :one
SELECT count(*)::integer FROM sticker_packs WHERE workspace_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountWorkspaceStickerPacks(ctx context.Context, workspaceID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countWorkspaceStickerPacks, workspaceID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countWorkspaceStickers = `-- name: CountWorkspaceStickers :one
SELECT count(*)::integer FROM stickers s
JOIN sticker_packs p ON p.id = s.pack_id AND p.deleted_at IS NULL
WHERE p.workspace_id = $1 AND s.deleted_at IS NULL
`

func (q *Queries) CountWorkspaceStickers(ctx context.Context, workspaceID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countWorkspaceStickers, workspaceID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteStickerIfUnreferenced = `-- name: DeleteStickerIfUnreferenced :execrows
DELETE FROM stickers s WHERE s.id = $1
  AND NOT EXISTS (SELECT 1 FROM messages m WHERE m.sticker_id = s.id)
`

func (q *Queries) DeleteStickerIfUnreferenced(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStickerIfUnreferenced, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStickerPackIfEmpty = `-- name: DeleteStickerPackIfEmpty :exec
DELETE FROM sticker_packs p WHERE p.id = $1 AND p.deleted_at IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM stickers s WHERE s.pack_id = p.id)
`

// A deleted pack without stickers left (none shown by messages) goes for good.
func (q *Queries) DeleteStickerPackIfEmpty(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteStickerPackIfEmpty, id)
	return err
}

const deleteUnreferencedPackStickers = `-- name: DeleteUnreferencedPackStickers :exec
DELETE FROM stickers s WHERE s.pack_id = $1
  AND NOT EXISTS (SELECT 1 FROM messages m WHERE m.sticker_id = s.id)
`

// Stickers of the pack that no message shows are removed; their files become orphans.
func (q *Queries) DeleteUnreferencedPackStickers(ctx context.Context, packID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUnreferencedPackStickers, packID)
	return err
}

const getSticker = `-- name: GetSticker :one
SELECT s.id, s.pack_id, s.file_id, s.emoji, s.position, s.width, s.height, s.animated, s.created_at, s.deleted_at, f.size AS file_size, p.workspace_id FROM stickers s
JOIN files f ON f.id = s.file_id
JOIN sticker_packs p ON p.id = s.pack_id AND p.deleted_at IS NULL
WHERE s.id = $1 AND s.deleted_at IS NULL
`

type GetStickerRow struct {
	Sticker     Sticker
	FileSize    int64
	WorkspaceID uuid.UUID
}

// A live sticker of a live pack, with its workspace.
func (q *Queries) GetSticker(ctx context.Context, id uuid.UUID) (GetStickerRow, error) {
	row := q.db.QueryRow(ctx, getSticker, id)
	var i GetStickerRow
	err := row.Scan(
		&i.Sticker.ID,
		&i.Sticker.PackID,
		&i.Sticker.FileID,
		&i.Sticker.Emoji,
		&i.Sticker.Position,
		&i.Sticker.Width,
		&i.Sticker.Height,
		&i.Sticker.Animated,
		&i.Sticker.CreatedAt,
		&i.Sticker.DeletedAt,
		&i.FileSize,
		&i.WorkspaceID,
	)
	return i, err
}

const getStickerFileWorkspace = `-- name: GetStickerFileWorkspace :one
SELECT p.workspace_id FROM stickers s JOIN sticker_packs p ON p.id = s.pack_id WHERE s.file_id = $1
`

// The workspace of the pack whose sticker is this file (no row = not a sticker file).
func (q *Queries) GetStickerFileWorkspace(ctx context.Context, fileID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getStickerFileWorkspace, fileID)
	var workspace_id uuid.UUID
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

const getStickerPack = `-- name: GetStickerPack :one
SELECT id, workspace_id, name, short_name, cover_sticker_id, created_by, created_at, updated_at, deleted_at FROM sticker_packs WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetStickerPack(ctx context.Context, id uuid.UUID) (StickerPack, error) {
	row := q.db.QueryRow(ctx, getStickerPack, id)
	var i StickerPack
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.ShortName,
		&i.CoverStickerID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertSticker = `-- name: InsertSticker :one
INSERT INTO stickers (pack_id, file_id, emoji, position, width, height, animated)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, pack_id, file_id, emoji, position, width, height, animated, created_at, deleted_at
`

type InsertStickerParams struct {
	PackID   uuid.UUID
	FileID   uuid.UUID
	Emoji    string
	Position int32
	Width    int32
	Height   int32
	Animated bool
}

func (q *Queries) InsertSticker(ctx context.Context, arg InsertStickerParams) (Sticker, error) {
	row := q.db.QueryRow(ctx, insertSticker,
		arg.PackID,
		arg.FileID,
		arg.Emoji,
		arg.Position,
		arg.Width,
		arg.Height,
		arg.Animated,
	)
	var i Sticker
	err := row.Scan(
		&i.ID,
		&i.PackID,
		&i.FileID,
		&i.Emoji,
		&i.Position,
		&i.Width,
		&i.Height,
		&i.Animated,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertStickerPack = `-- name: InsertStickerPack :one
INSERT INTO sticker_packs (workspace_id, name, short_name, created_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (workspace_id, short_name) WHERE deleted_at IS NULL DO NOTHING
RETURNING id, workspace_id, name, short_name, cover_sticker_id, created_by, created_at, updated_at, deleted_at
`

type InsertStickerPackParams struct {
	WorkspaceID uuid.UUID
	Name        string
	ShortName   string
	CreatedBy   *uuid.UUID
}

// No row = the short name is taken in the workspace.
func (q *Queries) InsertStickerPack(ctx context.Context, arg InsertStickerPackParams) (StickerPack, error) {
	row := q.db.QueryRow(ctx, insertStickerPack,
		arg.WorkspaceID,
		arg.Name,
		arg.ShortName,
		arg.CreatedBy,
	)
	var i StickerPack
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.ShortName,
		&i.CoverStickerID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const installStickerPack = `-- name: InstallStickerPack :execrows
INSERT INTO user_sticker_packs (user_id, pack_id, position)
VALUES ($1, $2,
        (SELECT coalesce(min(position), 1) - 1 FROM user_sticker_packs WHERE user_id = $1))
ON CONFLICT (user_id, pack_id) DO NOTHING
`

type InstallStickerPackParams struct {
	UserID uuid.UUID
	PackID uuid.UUID
}

// First in the user's order; 0 rows = already installed.
func (q *Queries) InstallStickerPack(ctx context.Context, arg InstallStickerPackParams) (int64, error) {
	result, err := q.db.Exec(ctx, installStickerPack, arg.UserID, arg.PackID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAvailableStickerPacks = `-- name: ListAvailableStickerPacks :many
SELECT p.id, p.workspace_id, p.name, p.short_name, p.cover_sticker_id, p.created_by, p.created_at, p.updated_at, p.deleted_at FROM sticker_packs p
JOIN workspace_members m ON m.workspace_id = p.workspace_id AND m.user_id = $1 AND m.role <> 'guest'
WHERE p.deleted_at IS NULL
  AND NOT EXISTS (SELECT 1 FROM user_sticker_packs u WHERE u.user_id = $1 AND u.pack_id = p.id)
ORDER BY p.workspace_id, p.id
LIMIT 200
`

// Live packs of the user's workspaces (not as a guest) that the user has not installed.
func (q *Queries) ListAvailableStickerPacks(ctx context.Context, userID uuid.UUID) ([]StickerPack, error) {
	rows, err := q.db.Query(ctx, listAvailableStickerPacks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StickerPack{}
	for rows.Next() {
		var i StickerPack
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.ShortName,
			&i.CoverStickerID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPackStickers = `-- name: ListPackStickers :many
SELECT s.id, s.pack_id, s.file_id, s.emoji, s.position, s.width, s.height, s.animated, s.created_at, s.deleted_at, f.size AS file_size FROM stickers s
JOIN files f ON f.id = s.file_id
WHERE s.pack_id = ANY($1::uuid[]) AND s.deleted_at IS NULL
ORDER BY s.pack_id, s.position, s.id
`

type ListPackStickersRow struct {
	Sticker  Sticker
	FileSize int64
}

// Live stickers of the packs with their file size, in pack order.
func (q *Queries) ListPackStickers(ctx context.Context, packIds []uuid.UUID) ([]ListPackStickersRow, error) {
	rows, err := q.db.Query(ctx, listPackStickers, packIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPackStickersRow{}
	for rows.Next() {
		var i ListPackStickersRow
		if err := rows.Scan(
			&i.Sticker.ID,
			&i.Sticker.PackID,
			&i.Sticker.FileID,
			&i.Sticker.Emoji,
			&i.Sticker.Position,
			&i.Sticker.Width,
			&i.Sticker.Height,
			&i.Sticker.Animated,
			&i.Sticker.CreatedAt,
			&i.Sticker.DeletedAt,
			&i.FileSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStickersByID = `-- name: ListStickersByID :many
SELECT s.id, s.pack_id, s.file_id, s.emoji, s.position, s.width, s.height, s.animated, s.created_at, s.deleted_at, f.size AS file_size, p.workspace_id FROM stickers s
JOIN files f ON f.id = s.file_id
JOIN sticker_packs p ON p.id = s.pack_id
WHERE s.id = ANY($1::uuid[])
`

type ListStickersByIDRow struct {
	Sticker     Sticker
	FileSize    int64
	WorkspaceID uuid.UUID
}

// Stickers shown by messages (deleted ones included) with their file size and workspace.
func (q *Queries) ListStickersByID(ctx context.Context, ids []uuid.UUID) ([]ListStickersByIDRow, error) {
	rows, err := q.db.Query(ctx, listStickersByID, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStickersByIDRow{}
	for rows.Next() {
		var i ListStickersByIDRow
		if err := rows.Scan(
			&i.Sticker.ID,
			&i.Sticker.PackID,
			&i.Sticker.FileID,
			&i.Sticker.Emoji,
			&i.Sticker.Position,
			&i.Sticker.Width,
			&i.Sticker.Height,
			&i.Sticker.Animated,
			&i.Sticker.CreatedAt,
			&i.Sticker.DeletedAt,
			&i.FileSize,
			&i.WorkspaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserStickerPackIDs = `-- name: ListUserStickerPackIDs :many
SELECT pack_id FROM user_sticker_packs WHERE user_id = $1
`

func (q *Queries) ListUserStickerPackIDs(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listUserStickerPackIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var pack_id uuid.UUID
		if err := rows.Scan(&pack_id); err != nil {
			return nil, err
		}
		items = append(items, pack_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserStickerPacks = `-- name: ListUserStickerPacks :many

SELECT p.id, p.workspace_id, p.name, p.short_name, p.cover_sticker_id, p.created_by, p.created_at, p.updated_at, p.deleted_at FROM user_sticker_packs u
JOIN sticker_packs p ON p.id = u.pack_id AND p.deleted_at IS NULL
JOIN workspace_members m ON m.workspace_id = p.workspace_id AND m.user_id = u.user_id AND m.role <> 'guest'
WHERE u.user_id = $1
ORDER BY u.position, u.added_at
`

// ---- the user's installed packs
// Installed live packs in the user's order, of workspaces where the user is not a guest.
func (q *Queries) ListUserStickerPacks(ctx context.Context, userID uuid.UUID) ([]StickerPack, error) {
	rows, err := q.db.Query(ctx, listUserStickerPacks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StickerPack{}
	for rows.Next() {
		var i StickerPack
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.ShortName,
			&i.CoverStickerID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceStickerPacks = `-- name: ListWorkspaceStickerPacks :many
SELECT id, workspace_id, name, short_name, cover_sticker_id, created_by, created_at, updated_at, deleted_at FROM sticker_packs WHERE workspace_id = $1 AND deleted_at IS NULL ORDER BY id
`

func (q *Queries) ListWorkspaceStickerPacks(ctx context.Context, workspaceID uuid.UUID) ([]StickerPack, error) {
	rows, err := q.db.Query(ctx, listWorkspaceStickerPacks, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StickerPack{}
	for rows.Next() {
		var i StickerPack
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.ShortName,
			&i.CoverStickerID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockWorkspaceStickers = `-- name: LockWorkspaceStickers :exec

SELECT pg_advisory_xact_lock(hashtext('calaba.stickers.' || $1::uuid::text))
`

// Sticker packs (ADR-0030). "Live" = deleted_at IS NULL; soft-deleted packs / stickers only
// stay for the messages that show them.
// Serializes pack / sticker creation of one workspace between the plan-limit count and the insert.
func (q *Queries) LockWorkspaceStickers(ctx context.Context, workspaceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockWorkspaceStickers, workspaceID)
	return err
}

const nextStickerPosition = `-- name: NextStickerPosition :one
SELECT (coalesce(max(position), -1) + 1)::integer FROM stickers WHERE pack_id = $1
`

func (q *Queries) NextStickerPosition(ctx context.Context, packID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextStickerPosition, packID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const setStickerPositions = `-- name: SetStickerPositions :exec
UPDATE stickers s SET position = o.ord::integer - 1
FROM unnest($2::uuid[]) WITH ORDINALITY AS o(id, ord)
WHERE s.id = o.id AND s.pack_id = $1
`

type SetStickerPositionsParams struct {
	PackID uuid.UUID
	Ids    []uuid.UUID
}

// Positions 0.. in the given order (the caller passes the pack's complete live set).
func (q *Queries) SetStickerPositions(ctx context.Context, arg SetStickerPositionsParams) error {
	_, err := q.db.Exec(ctx, setStickerPositions, arg.PackID, arg.Ids)
	return err
}

const setUserStickerPackOrder = `-- name: SetUserStickerPackOrder :exec
UPDATE user_sticker_packs u SET position = o.ord::integer - 1
FROM unnest($2::uuid[]) WITH ORDINALITY AS o(id, ord)
WHERE u.user_id = $1 AND u.pack_id = o.id
`

type SetUserStickerPackOrderParams struct {
	UserID  uuid.UUID
	PackIds []uuid.UUID
}

func (q *Queries) SetUserStickerPackOrder(ctx context.Context, arg SetUserStickerPackOrderParams) error {
	_, err := q.db.Exec(ctx, setUserStickerPackOrder, arg.UserID, arg.PackIds)
	return err
}

const softDeletePackStickers = `-- name: SoftDeletePackStickers :exec
UPDATE stickers SET deleted_at = now() WHERE pack_id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeletePackStickers(ctx context.Context, packID uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeletePackStickers, packID)
	return err
}

const softDeleteSticker = `-- name: SoftDeleteSticker :exec
UPDATE stickers SET deleted_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteSticker(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteSticker, id)
	return err
}

const softDeleteStickerPack = `-- name: SoftDeleteStickerPack :execrows
UPDATE sticker_packs SET deleted_at = now(), updated_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteStickerPack(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteStickerPack, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const stickerFileRooms = `-- name: StickerFileRooms :many
SELECT DISTINCT m.room_id FROM stickers s
JOIN messages m ON m.sticker_id = s.id AND m.deleted_at IS NULL
WHERE s.file_id = $1
LIMIT 50
`

// Rooms where a live message shows the sticker of this file.
func (q *Queries) StickerFileRooms(ctx context.Context, fileID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, stickerFileRooms, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var room_id uuid.UUID
		if err := rows.Scan(&room_id); err != nil {
			return nil, err
		}
		items = append(items, room_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchStickerPack = `-- name: TouchStickerPack :exec
UPDATE sticker_packs SET updated_at = now() WHERE id = $1
`

func (q *Queries) TouchStickerPack(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchStickerPack, id)
	return err
}

const uninstallStickerPack = `-- name: UninstallStickerPack :execrows
DELETE FROM user_sticker_packs WHERE user_id = $1 AND pack_id = $2
`

type UninstallStickerPackParams struct {
	UserID uuid.UUID
	PackID uuid.UUID
}

func (q *Queries) UninstallStickerPack(ctx context.Context, arg UninstallStickerPackParams) (int64, error) {
	result, err := q.db.Exec(ctx, uninstallStickerPack, arg.UserID, arg.PackID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const uninstallStickerPackForAll = `-- name: UninstallStickerPackForAll :exec
DELETE FROM user_sticker_packs WHERE pack_id = $1
`

func (q *Queries) UninstallStickerPackForAll(ctx context.Context, packID uuid.UUID) error {
	_, err := q.db.Exec(ctx, uninstallStickerPackForAll, packID)
	return err
}

const updateStickerEmoji = `-- name: UpdateStickerEmoji :exec
UPDATE stickers SET emoji = $2 WHERE id = $1 AND deleted_at IS NULL
`

type UpdateStickerEmojiParams struct {
	ID    uuid.UUID
	Emoji string
}

func (q *Queries) UpdateStickerEmoji(ctx context.Context, arg UpdateStickerEmojiParams) error {
	_, err := q.db.Exec(ctx, updateStickerEmoji, arg.ID, arg.Emoji)
	return err
}

const updateStickerPack = `-- name: UpdateStickerPack :one
UPDATE sticker_packs SET
    name = coalesce($1, name),
    short_name = coalesce($2, short_name),
    cover_sticker_id = CASE WHEN $3::boolean THEN $4::uuid ELSE cover_sticker_id END,
    updated_at = now()
WHERE id = $5 AND deleted_at IS NULL
RETURNING id, workspace_id, name, short_name, cover_sticker_id, created_by, created_at, updated_at, deleted_at
`

type UpdateStickerPackParams struct {
	Name           *string
	ShortName      *string
	SetCover       bool
	CoverStickerID *uuid.UUID
	ID             uuid.UUID
}

func (q *Queries) UpdateStickerPack(ctx context.Context, arg UpdateStickerPackParams) (StickerPack, error) {
	row := q.db.QueryRow(ctx, updateStickerPack,
		arg.Name,
		arg.ShortName,
		arg.SetCover,
		arg.CoverStickerID,
		arg.ID,
	)
	var i StickerPack
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.ShortName,
		&i.CoverStickerID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
