// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, display_name, settings)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, display_name, avatar_file_id, status_text, settings, created_at, disabled_at, status_emoji, status_expires_at, is_guest, guest_expires_at
`

type CreateUserParams struct {
	Email        *string
	PasswordHash *string
	DisplayName  string
	Settings     []byte
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.Settings,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarFileID,
		&i.StatusText,
		&i.Settings,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.StatusEmoji,
		&i.StatusExpiresAt,
		&i.IsGuest,
		&i.GuestExpiresAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, password_hash, display_name, avatar_file_id, status_text, settings, created_at, disabled_at, status_emoji, status_expires_at, is_guest, guest_expires_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarFileID,
		&i.StatusText,
		&i.Settings,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.StatusEmoji,
		&i.StatusExpiresAt,
		&i.IsGuest,
		&i.GuestExpiresAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, display_name, avatar_file_id, status_text, settings, created_at, disabled_at, status_emoji, status_expires_at, is_guest, guest_expires_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarFileID,
		&i.StatusText,
		&i.Settings,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.StatusEmoji,
		&i.StatusExpiresAt,
		&i.IsGuest,
		&i.GuestExpiresAt,
	)
	return i, err
}

const lockRegistration = `-- name: LockRegistration :exec
SELECT pg_advisory_xact_lock(hashtext('calaba.registration'))
`

// Serializes the first-user bootstrap check (see auth.Register).
func (q *Queries) LockRegistration(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockRegistration)
	return err
}

const updateStatus = `-- name: UpdateStatus :one
UPDATE users SET status_text = $2, status_emoji = $3, status_expires_at = $4
WHERE id = $1
RETURNING id, email, password_hash, display_name, avatar_file_id, status_text, settings, created_at, disabled_at, status_emoji, status_expires_at, is_guest, guest_expires_at
`

type UpdateStatusParams struct {
	ID              uuid.UUID
	StatusText      string
	StatusEmoji     string
	StatusExpiresAt *time.Time
}

func (q *Queries) UpdateStatus(ctx context.Context, arg UpdateStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, updateStatus,
		arg.ID,
		arg.StatusText,
		arg.StatusEmoji,
		arg.StatusExpiresAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarFileID,
		&i.StatusText,
		&i.Settings,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.StatusEmoji,
		&i.StatusExpiresAt,
		&i.IsGuest,
		&i.GuestExpiresAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
    display_name   = coalesce($1, display_name),
    status_text    = coalesce($2, status_text),
    avatar_file_id = CASE WHEN $3::boolean THEN $4::uuid ELSE avatar_file_id END,
    settings       = coalesce($5, settings)
WHERE id = $6
RETURNING id, email, password_hash, display_name, avatar_file_id, status_text, settings, created_at, disabled_at, status_emoji, status_expires_at, is_guest, guest_expires_at
`

type UpdateUserParams struct {
	DisplayName  *string
	StatusText   *string
	SetAvatar    bool
	AvatarFileID *uuid.UUID
	Settings     []byte
	ID           uuid.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.DisplayName,
		arg.StatusText,
		arg.SetAvatar,
		arg.AvatarFileID,
		arg.Settings,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarFileID,
		&i.StatusText,
		&i.Settings,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.StatusEmoji,
		&i.StatusExpiresAt,
		&i.IsGuest,
		&i.GuestExpiresAt,
	)
	return i, err
}
