// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, display_name, settings)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, display_name, avatar_file_id, status_text, settings, created_at, disabled_at, status_emoji, status_expires_at, is_guest, guest_expires_at, timezone
`

type CreateUserParams struct {
	Email        *string
	PasswordHash *string
	DisplayName  string
	Settings     []byte
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.Settings,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarFileID,
		&i.StatusText,
		&i.Settings,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.StatusEmoji,
		&i.StatusExpiresAt,
		&i.IsGuest,
		&i.GuestExpiresAt,
		&i.Timezone,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, password_hash, display_name, avatar_file_id, status_text, settings, created_at, disabled_at, status_emoji, status_expires_at, is_guest, guest_expires_at, timezone FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarFileID,
		&i.StatusText,
		&i.Settings,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.StatusEmoji,
		&i.StatusExpiresAt,
		&i.IsGuest,
		&i.GuestExpiresAt,
		&i.Timezone,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, display_name, avatar_file_id, status_text, settings, created_at, disabled_at, status_emoji, status_expires_at, is_guest, guest_expires_at, timezone FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarFileID,
		&i.StatusText,
		&i.Settings,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.StatusEmoji,
		&i.StatusExpiresAt,
		&i.IsGuest,
		&i.GuestExpiresAt,
		&i.Timezone,
	)
	return i, err
}

const lockPasswordHash = `-- name: LockPasswordHash :one
SELECT password_hash FROM users WHERE id = $1 FOR SHARE
`

// Login re-reads the hash under a share lock in the session transaction: a concurrent
// password change either waits for the new session (and then revokes it) or has already
// replaced the hash (and the login fails).
func (q *Queries) LockPasswordHash(ctx context.Context, id uuid.UUID) (*string, error) {
	row := q.db.QueryRow(ctx, lockPasswordHash, id)
	var password_hash *string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const lockRegistration = `-- name: LockRegistration :exec
SELECT pg_advisory_xact_lock(hashtext('calaba.registration'))
`

// Serializes the first-user bootstrap check (see auth.Register).
func (q *Queries) LockRegistration(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockRegistration)
	return err
}

const setEmail = `-- name: SetEmail :one
UPDATE users SET email = $2 WHERE id = $1
RETURNING id, email, password_hash, display_name, avatar_file_id, status_text, settings, created_at, disabled_at, status_emoji, status_expires_at, is_guest, guest_expires_at, timezone
`

type SetEmailParams struct {
	ID    uuid.UUID
	Email *string
}

func (q *Queries) SetEmail(ctx context.Context, arg SetEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, setEmail, arg.ID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarFileID,
		&i.StatusText,
		&i.Settings,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.StatusEmoji,
		&i.StatusExpiresAt,
		&i.IsGuest,
		&i.GuestExpiresAt,
		&i.Timezone,
	)
	return i, err
}

const setPasswordHash = `-- name: SetPasswordHash :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type SetPasswordHashParams struct {
	ID           uuid.UUID
	PasswordHash *string
}

func (q *Queries) SetPasswordHash(ctx context.Context, arg SetPasswordHashParams) error {
	_, err := q.db.Exec(ctx, setPasswordHash, arg.ID, arg.PasswordHash)
	return err
}

const updateStatus = `-- name: UpdateStatus :one
UPDATE users SET status_text = $2, status_emoji = $3, status_expires_at = $4
WHERE id = $1
RETURNING id, email, password_hash, display_name, avatar_file_id, status_text, settings, created_at, disabled_at, status_emoji, status_expires_at, is_guest, guest_expires_at, timezone
`

type UpdateStatusParams struct {
	ID              uuid.UUID
	StatusText      string
	StatusEmoji     string
	StatusExpiresAt *time.Time
}

func (q *Queries) UpdateStatus(ctx context.Context, arg UpdateStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, updateStatus,
		arg.ID,
		arg.StatusText,
		arg.StatusEmoji,
		arg.StatusExpiresAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarFileID,
		&i.StatusText,
		&i.Settings,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.StatusEmoji,
		&i.StatusExpiresAt,
		&i.IsGuest,
		&i.GuestExpiresAt,
		&i.Timezone,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
    display_name   = coalesce($1, display_name),
    status_text    = coalesce($2, status_text),
    avatar_file_id = CASE WHEN $3::boolean THEN $4::uuid ELSE avatar_file_id END,
    settings       = coalesce($5, settings),
    timezone       = CASE WHEN $6::boolean THEN $7::text ELSE timezone END
WHERE id = $8
RETURNING id, email, password_hash, display_name, avatar_file_id, status_text, settings, created_at, disabled_at, status_emoji, status_expires_at, is_guest, guest_expires_at, timezone
`

type UpdateUserParams struct {
	DisplayName  *string
	StatusText   *string
	SetAvatar    bool
	AvatarFileID *uuid.UUID
	Settings     []byte
	SetTimezone  bool
	Timezone     *string
	ID           uuid.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.DisplayName,
		arg.StatusText,
		arg.SetAvatar,
		arg.AvatarFileID,
		arg.Settings,
		arg.SetTimezone,
		arg.Timezone,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarFileID,
		&i.StatusText,
		&i.Settings,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.StatusEmoji,
		&i.StatusExpiresAt,
		&i.IsGuest,
		&i.GuestExpiresAt,
		&i.Timezone,
	)
	return i, err
}
